/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuario;

//import Ventanas.*;
import java.awt.Color;
import javax.swing.JPanel;
import Clases.Manejadora;
import Clases.Personal;

import Ventanas_Administracion.Administrar_Mesas;
import Ventanas_Administracion.Administrar_Proveedor;
import Ventanas_Administracion.Administrar_datos_personal;
import Ventanas_Administracion.Menu_principal;
import Vista.Factura.Interfaz_Factura;
import Vista.Ingrediente.interfaz_Ingrediente;
import Vista.Recetario.interfaz_Recetario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Interfaz_Eliminar_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Interfaz_Eliminar_Usuario() {
        initComponents();
        this.setLocationRelativeTo(this);
        setColor(btn_inicio_elim_usuario); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_elim_usuario,btn_ingred_elim_usuario,btn_admmes_elim_usuario}, new JPanel[]{ind_2,ind_3, ind_4});
        //jProgressBar1.setValue(50);
      
        btn_buscar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Busca a un personal mediante su rut.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        btn_volver.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Regresa una ventana atras.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        btn_eliminar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Elimina el personal seleccionado.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        side_pane6 = new javax.swing.JPanel();
        side_pane3 = new javax.swing.JPanel();
        side_pane5 = new javax.swing.JPanel();
        side_pane4 = new javax.swing.JPanel();
        side_pane7 = new javax.swing.JPanel();
        side_pane1 = new javax.swing.JPanel();
        lbl_logoazul_restau = new javax.swing.JLabel();
        btn_mostrar = new javax.swing.JButton();
        side_pane = new javax.swing.JPanel();
        btn_inicio_elim_usuario = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lbl_inicio_elim_usario = new javax.swing.JLabel();
        btn_datper_elim_usuario = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbl_datper_elim_usuario = new javax.swing.JLabel();
        btn_ingred_elim_usuario = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbl_ingre_elim_usuario = new javax.swing.JLabel();
        btn_admmes_elim_usuario = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbl_adm_mesa_elim_usuario = new javax.swing.JLabel();
        btn_prove_elim_personal = new javax.swing.JPanel();
        ind_9 = new javax.swing.JPanel();
        lbl_proveedores_elim_usuario = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        btn_modulo_documento = new javax.swing.JPanel();
        ind_13 = new javax.swing.JPanel();
        lbl_documentos = new javax.swing.JLabel();
        btn_recetario = new javax.swing.JPanel();
        ind_12 = new javax.swing.JPanel();
        lbl_recetario = new javax.swing.JLabel();
        pnl_barra_superior_elim_usuario = new javax.swing.JPanel();
        lbl_tipo_usuario = new javax.swing.JLabel();
        lbl_icono_usuario = new javax.swing.JLabel();
        lbl_titulo_adm_perso = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        lbl_rut_usuario = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_mostrar = new javax.swing.JTable();
        lbl_fondo_interfaz_elim_usuario = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane6.setBackground(new java.awt.Color(251, 243, 0));
        side_pane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 10, 290));

        side_pane3.setBackground(new java.awt.Color(251, 243, 0));
        side_pane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane5.setBackground(new java.awt.Color(251, 243, 0));
        side_pane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane3.add(side_pane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        getContentPane().add(side_pane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 740, 10));

        side_pane4.setBackground(new java.awt.Color(251, 243, 0));
        side_pane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 730, 10));

        side_pane7.setBackground(new java.awt.Color(251, 243, 0));
        side_pane7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 10, 290));

        side_pane1.setBackground(new java.awt.Color(251, 243, 0));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 10, 500));

        lbl_logoazul_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_superior_blanco.png"))); // NOI18N
        lbl_logoazul_restau.setText("jLabel17");
        getContentPane().add(lbl_logoazul_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 205, 110));

        btn_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Read.png"))); // NOI18N
        btn_mostrar.setText("Mostrar");
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 150, -1));

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio_elim_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_inicio_elim_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicio_elim_usuarioMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_inicio_elim_usario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_inicio_elim_usario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio_elim_usario.setText(" Inicio");

        javax.swing.GroupLayout btn_inicio_elim_usuarioLayout = new javax.swing.GroupLayout(btn_inicio_elim_usuario);
        btn_inicio_elim_usuario.setLayout(btn_inicio_elim_usuarioLayout);
        btn_inicio_elim_usuarioLayout.setHorizontalGroup(
            btn_inicio_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_elim_usuarioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lbl_inicio_elim_usario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        btn_inicio_elim_usuarioLayout.setVerticalGroup(
            btn_inicio_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_elim_usuarioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_inicio_elim_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inicio_elim_usario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_inicio_elim_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        btn_datper_elim_usuario.setBackground(new java.awt.Color(251, 243, 0));
        btn_datper_elim_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_datper_elim_usuarioMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_datper_elim_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_datper_elim_usuario.setText("Datos de personal");

        javax.swing.GroupLayout btn_datper_elim_usuarioLayout = new javax.swing.GroupLayout(btn_datper_elim_usuario);
        btn_datper_elim_usuario.setLayout(btn_datper_elim_usuarioLayout);
        btn_datper_elim_usuarioLayout.setHorizontalGroup(
            btn_datper_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_elim_usuarioLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_datper_elim_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );
        btn_datper_elim_usuarioLayout.setVerticalGroup(
            btn_datper_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_elim_usuarioLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_datper_elim_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_datper_elim_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_datper_elim_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 130, -1));

        btn_ingred_elim_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_ingred_elim_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingred_elim_usuarioMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_ingre_elim_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_ingre_elim_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingre_elim_usuario.setText("Ingredientes");

        javax.swing.GroupLayout btn_ingred_elim_usuarioLayout = new javax.swing.GroupLayout(btn_ingred_elim_usuario);
        btn_ingred_elim_usuario.setLayout(btn_ingred_elim_usuarioLayout);
        btn_ingred_elim_usuarioLayout.setHorizontalGroup(
            btn_ingred_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_elim_usuarioLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingre_elim_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        btn_ingred_elim_usuarioLayout.setVerticalGroup(
            btn_ingred_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_elim_usuarioLayout.createSequentialGroup()
                .addGroup(btn_ingred_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingre_elim_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_pane.add(btn_ingred_elim_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 120, 40));

        btn_admmes_elim_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_admmes_elim_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_admmes_elim_usuarioMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_adm_mesa_elim_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_adm_mesa_elim_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_adm_mesa_elim_usuario.setText("Administrar Mesas");

        javax.swing.GroupLayout btn_admmes_elim_usuarioLayout = new javax.swing.GroupLayout(btn_admmes_elim_usuario);
        btn_admmes_elim_usuario.setLayout(btn_admmes_elim_usuarioLayout);
        btn_admmes_elim_usuarioLayout.setHorizontalGroup(
            btn_admmes_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_elim_usuarioLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_adm_mesa_elim_usuario)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btn_admmes_elim_usuarioLayout.setVerticalGroup(
            btn_admmes_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_elim_usuarioLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_admmes_elim_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adm_mesa_elim_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_admmes_elim_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, -1));

        btn_prove_elim_personal.setBackground(new java.awt.Color(23, 35, 51));
        btn_prove_elim_personal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_prove_elim_personalMouseReleased(evt);
            }
        });

        ind_9.setOpaque(false);
        ind_9.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_9Layout = new javax.swing.GroupLayout(ind_9);
        ind_9.setLayout(ind_9Layout);
        ind_9Layout.setHorizontalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_9Layout.setVerticalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_proveedores_elim_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_proveedores_elim_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_proveedores_elim_usuario.setText("Proveedores");

        javax.swing.GroupLayout btn_prove_elim_personalLayout = new javax.swing.GroupLayout(btn_prove_elim_personal);
        btn_prove_elim_personal.setLayout(btn_prove_elim_personalLayout);
        btn_prove_elim_personalLayout.setHorizontalGroup(
            btn_prove_elim_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_elim_personalLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_proveedores_elim_usuario)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        btn_prove_elim_personalLayout.setVerticalGroup(
            btn_prove_elim_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_elim_personalLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_prove_elim_personalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_proveedores_elim_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_prove_elim_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 130, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        side_pane.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 30, 46));

        btn_modulo_documento.setBackground(new java.awt.Color(23, 35, 51));
        btn_modulo_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_modulo_documentoMouseReleased(evt);
            }
        });

        ind_13.setOpaque(false);
        ind_13.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_13Layout = new javax.swing.GroupLayout(ind_13);
        ind_13.setLayout(ind_13Layout);
        ind_13Layout.setHorizontalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_13Layout.setVerticalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_documentos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_documentos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_documentos.setText("Documentos");

        javax.swing.GroupLayout btn_modulo_documentoLayout = new javax.swing.GroupLayout(btn_modulo_documento);
        btn_modulo_documento.setLayout(btn_modulo_documentoLayout);
        btn_modulo_documentoLayout.setHorizontalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btn_modulo_documentoLayout.setVerticalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_documentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_modulo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 140, -1));

        btn_recetario.setBackground(new java.awt.Color(23, 35, 51));
        btn_recetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_recetarioMouseReleased(evt);
            }
        });

        ind_12.setOpaque(false);
        ind_12.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_12Layout = new javax.swing.GroupLayout(ind_12);
        ind_12.setLayout(ind_12Layout);
        ind_12Layout.setHorizontalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_12Layout.setVerticalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_recetario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_recetario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_recetario.setText("Recetario");

        javax.swing.GroupLayout btn_recetarioLayout = new javax.swing.GroupLayout(btn_recetario);
        btn_recetario.setLayout(btn_recetarioLayout);
        btn_recetarioLayout.setHorizontalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_recetario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_recetarioLayout.setVerticalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_recetario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_recetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 590));

        pnl_barra_superior_elim_usuario.setBackground(new java.awt.Color(23, 35, 51));
        pnl_barra_superior_elim_usuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barra_superior_elim_usuarioMouseDragged(evt);
            }
        });
        pnl_barra_superior_elim_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barra_superior_elim_usuarioMousePressed(evt);
            }
        });

        lbl_tipo_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_tipo_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_usuario.setText("Usuario: Administrador");

        lbl_icono_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_48px.png"))); // NOI18N

        lbl_titulo_adm_perso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo_adm_perso.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo_adm_perso.setText("ELIMINAR USUARIO");

        javax.swing.GroupLayout pnl_barra_superior_elim_usuarioLayout = new javax.swing.GroupLayout(pnl_barra_superior_elim_usuario);
        pnl_barra_superior_elim_usuario.setLayout(pnl_barra_superior_elim_usuarioLayout);
        pnl_barra_superior_elim_usuarioLayout.setHorizontalGroup(
            pnl_barra_superior_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barra_superior_elim_usuarioLayout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addComponent(lbl_titulo_adm_perso)
                .addGap(182, 182, 182)
                .addComponent(lbl_icono_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_barra_superior_elim_usuarioLayout.setVerticalGroup(
            pnl_barra_superior_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_elim_usuarioLayout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addComponent(lbl_icono_usuario))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_elim_usuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_barra_superior_elim_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_elim_usuarioLayout.createSequentialGroup()
                        .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_elim_usuarioLayout.createSequentialGroup()
                        .addComponent(lbl_titulo_adm_perso)
                        .addGap(27, 27, 27))))
        );

        getContentPane().add(pnl_barra_superior_elim_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 90));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 170, -1));

        btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 80, -1));

        lbl_rut_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_rut_usuario.setText("Rut:");
        getContentPane().add(lbl_rut_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        txtrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutActionPerformed(evt);
            }
        });
        txtrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutKeyTyped(evt);
            }
        });
        getContentPane().add(txtrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 130, -1));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_P.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 130, 30));

        jTable_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_mostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 720, 270));

        lbl_fondo_interfaz_elim_usuario.setBackground(new java.awt.Color(83, 83, 83));
        lbl_fondo_interfaz_elim_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_personal_final.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo_interfaz_elim_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 930, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void pnl_barra_superior_elim_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_superior_elim_usuarioMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnl_barra_superior_elim_usuarioMousePressed

    private void pnl_barra_superior_elim_usuarioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_superior_elim_usuarioMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_pnl_barra_superior_elim_usuarioMouseDragged

    private void btn_inicio_elim_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicio_elim_usuarioMousePressed
        // TODO add your handling code here:
        setColor(btn_inicio_elim_usuario);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_elim_usuario,btn_ingred_elim_usuario,btn_admmes_elim_usuario}, new JPanel[]{ind_2,ind_3, ind_4});
        Menu_principal mp = new Menu_principal();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicio_elim_usuarioMousePressed

    private void btn_datper_elim_usuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datper_elim_usuarioMouseReleased
        // TODO add your handling code here:
        setColor(btn_datper_elim_usuario);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_inicio_elim_usuario,btn_ingred_elim_usuario,btn_admmes_elim_usuario}, new JPanel[]{ind_1,ind_3, ind_4});
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_datper_elim_usuarioMouseReleased

    private void btn_ingred_elim_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingred_elim_usuarioMousePressed
        // TODO add your handling code here:
        setColor(btn_ingred_elim_usuario);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_elim_usuario,btn_inicio_elim_usuario,btn_admmes_elim_usuario}, new JPanel[]{ind_2,ind_1, ind_4});
        interfaz_Ingrediente adm_ingre = new interfaz_Ingrediente();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingred_elim_usuarioMousePressed

    private void btn_admmes_elim_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_admmes_elim_usuarioMousePressed
        // TODO add your handling code here:
        setColor(btn_admmes_elim_usuario);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_elim_usuario,btn_ingred_elim_usuario,btn_inicio_elim_usuario}, new JPanel[]{ind_2,ind_3, ind_1});
        Administrar_Mesas adm_mesa = new Administrar_Mesas();
        adm_mesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_admmes_elim_usuarioMousePressed

    private void btn_prove_elim_personalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prove_elim_personalMouseReleased
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_prove_elim_personalMouseReleased

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?");
        if (JOptionPane.OK_OPTION == exit)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitMousePressed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:

        int selec;
        selec = (Integer)this.jTable_mostrar.getSelectedRow();

        if (selec==-1)
        {
            JOptionPane.showMessageDialog(this,"No se ha seleccionado ninguna fila");
        }
        else
        {

            int conf = JOptionPane.showConfirmDialog(this,"Esta seguro de eliminar seleccionado?");
            if (JOptionPane.OK_OPTION == conf) {

                selec = (Integer)this.jTable_mostrar.getSelectedRow();
                String rut;
                rut = this.jTable_mostrar.getValueAt(selec, 0).toString();
                try {
                    Manejadora.eliminarPersonal(conf, rut);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Interfaz_Eliminar_Usuario.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this,"Registro eliminado");
                this.txtrut.setText(null);
                this.txtrut.setText(null);
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        try
        {
            DefaultTableModel modelo= new DefaultTableModel();
            modelo.addColumn("Rut");
            modelo.addColumn("Digito verificador");
            modelo.addColumn("Nombre personal");
            modelo.addColumn("Apellido personal");
            modelo.addColumn("Celular");
            modelo.addColumn("Correo");
            this.jTable_mostrar.setModel(modelo);
            try {
                ResultSet rs = Manejadora.buscarPersonal(this.txtrut.getText());
                String [] datos = new String[6];
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    modelo.addRow(datos);
                    this.jTable_mostrar.setModel(modelo);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se ha ingresado rut");
        }

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txtrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutActionPerformed

    private void txtrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txtrutKeyTyped

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("Rut");
        modelo.addColumn("Digito verificador");
        modelo.addColumn("Nombre personal");
        modelo.addColumn("Apellido personal");
        modelo.addColumn("Correo");
        modelo.addColumn("Celular:");
        modelo.addColumn("Tipo Personal:");
        this.jTable_mostrar.setModel(modelo);

        try {
            ResultSet rs = Manejadora.mostrarPersonal();
            String [] datos = new String[7];
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                modelo.addRow(datos);
                this.jTable_mostrar.setModel(modelo);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_mostrarActionPerformed

    private void btn_modulo_documentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulo_documentoMouseReleased
        Interfaz_Factura adm_ingre = new Interfaz_Factura();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modulo_documentoMouseReleased

    private void btn_recetarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recetarioMouseReleased
        interfaz_Recetario adm_ingre = new interfaz_Recetario();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_recetarioMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Eliminar_Usuario().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_admmes_elim_usuario;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JPanel btn_datper_elim_usuario;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel btn_ingred_elim_usuario;
    private javax.swing.JPanel btn_inicio_elim_usuario;
    private javax.swing.JPanel btn_modulo_documento;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JPanel btn_prove_elim_personal;
    private javax.swing.JPanel btn_recetario;
    private javax.swing.JButton btn_volver;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_12;
    private javax.swing.JPanel ind_13;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_mostrar;
    private javax.swing.JLabel lbl_adm_mesa_elim_usuario;
    private javax.swing.JLabel lbl_datper_elim_usuario;
    private javax.swing.JLabel lbl_documentos;
    private javax.swing.JLabel lbl_fondo_interfaz_elim_usuario;
    private javax.swing.JLabel lbl_icono_usuario;
    private javax.swing.JLabel lbl_ingre_elim_usuario;
    private javax.swing.JLabel lbl_inicio_elim_usario;
    private javax.swing.JLabel lbl_logoazul_restau;
    private javax.swing.JLabel lbl_proveedores_elim_usuario;
    private javax.swing.JLabel lbl_recetario;
    private javax.swing.JLabel lbl_rut_usuario;
    private javax.swing.JLabel lbl_tipo_usuario;
    private javax.swing.JLabel lbl_titulo_adm_perso;
    private javax.swing.JPanel pnl_barra_superior_elim_usuario;
    private javax.swing.JPanel side_pane;
    private javax.swing.JPanel side_pane1;
    private javax.swing.JPanel side_pane3;
    private javax.swing.JPanel side_pane4;
    private javax.swing.JPanel side_pane5;
    private javax.swing.JPanel side_pane6;
    private javax.swing.JPanel side_pane7;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables
}
