/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuario;

//import Ventanas.*;
import java.awt.Color;
import javax.swing.JPanel;
import Clases.Manejadora;
import Clases.Personal;
import Ventanas_Administracion.Administrar_Mesas;
import Ventanas_Administracion.Administrar_Proveedor;
import Ventanas_Administracion.Administrar_datos_personal;
import Ventanas_Administracion.Menu_principal;
import Vista.Factura.Interfaz_Factura;
import Vista.Ingrediente.interfaz_Ingrediente;
import Vista.Recetario.interfaz_Recetario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Interfaz_mostrar_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Interfaz_mostrar_Usuario() {
        initComponents();
        this.setLocationRelativeTo(this);
        setColor(btn_inicio_most_usuario); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_most_usuario,btn_ingred_most_usuario,btn_admmes_most_usuario}, new JPanel[]{ind_2,ind_3, ind_4});
        //jProgressBar1.setValue(50);
        btn_buscar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Busca un personal mediante su rut y digito verificador.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
                btn_volver.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Regresa una ventana atras.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
                btn_mostrar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Mostrara los datos de todos los personales.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
                jl_info_rut.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese el rut y digito verificador del personal.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        side_pane6 = new javax.swing.JPanel();
        side_pane2 = new javax.swing.JPanel();
        side_pane5 = new javax.swing.JPanel();
        side_pane8 = new javax.swing.JPanel();
        side_pane9 = new javax.swing.JPanel();
        side_pane3 = new javax.swing.JPanel();
        side_pane4 = new javax.swing.JPanel();
        side_pane1 = new javax.swing.JPanel();
        lbl_logoazul_restau = new javax.swing.JLabel();
        side_pane = new javax.swing.JPanel();
        btn_inicio_most_usuario = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lbl_inicio_most_usuario = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        btn_datper_most_usuario = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbl_dtos_perso_most_usuario = new javax.swing.JLabel();
        btn_ingred_most_usuario = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbl_ingre_most_usuario = new javax.swing.JLabel();
        btn_admmes_most_usuario = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbl_adm_mesa_most_usuario = new javax.swing.JLabel();
        btn_prove_most_usuario = new javax.swing.JPanel();
        ind_9 = new javax.swing.JPanel();
        lbl_proveedores_most_usuario = new javax.swing.JLabel();
        btn_modulo_documento = new javax.swing.JPanel();
        ind_13 = new javax.swing.JPanel();
        lbl_documentos = new javax.swing.JLabel();
        btn_recetario = new javax.swing.JPanel();
        ind_12 = new javax.swing.JPanel();
        lbl_recetario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_tipo_usuario = new javax.swing.JLabel();
        lbl_icono_usuario = new javax.swing.JLabel();
        lbl_titulo_adm_perso = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_mostrar = new javax.swing.JTable();
        txt_rut = new javax.swing.JTextField();
        lbl_rut = new javax.swing.JLabel();
        btn_mostrar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        jl_info_rut = new javax.swing.JLabel();
        lbl_fondo_interfaz_most_usuario = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane6.setBackground(new java.awt.Color(251, 243, 0));
        side_pane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 10, 310));

        side_pane2.setBackground(new java.awt.Color(251, 243, 0));
        side_pane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane5.setBackground(new java.awt.Color(251, 243, 0));
        side_pane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane2.add(side_pane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane8.setBackground(new java.awt.Color(251, 243, 0));
        side_pane8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane9.setBackground(new java.awt.Color(251, 243, 0));
        side_pane9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane8.add(side_pane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane2.add(side_pane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 690, 10));

        getContentPane().add(side_pane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 690, 10));

        side_pane3.setBackground(new java.awt.Color(251, 243, 0));
        side_pane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 710, 10));

        side_pane4.setBackground(new java.awt.Color(251, 243, 0));
        side_pane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 10, 310));

        side_pane1.setBackground(new java.awt.Color(251, 243, 0));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 10, 500));

        lbl_logoazul_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_superior_blanco.png"))); // NOI18N
        lbl_logoazul_restau.setText("jLabel17");
        getContentPane().add(lbl_logoazul_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 205, 80));

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio_most_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_inicio_most_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicio_most_usuarioMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_inicio_most_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_inicio_most_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio_most_usuario.setText("Inicio");

        javax.swing.GroupLayout btn_inicio_most_usuarioLayout = new javax.swing.GroupLayout(btn_inicio_most_usuario);
        btn_inicio_most_usuario.setLayout(btn_inicio_most_usuarioLayout);
        btn_inicio_most_usuarioLayout.setHorizontalGroup(
            btn_inicio_most_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_most_usuarioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbl_inicio_most_usuario)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        btn_inicio_most_usuarioLayout.setVerticalGroup(
            btn_inicio_most_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_most_usuarioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_inicio_most_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inicio_most_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_inicio_most_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        side_pane.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 30, 46));

        btn_datper_most_usuario.setBackground(new java.awt.Color(251, 243, 0));
        btn_datper_most_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_datper_most_usuarioMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_dtos_perso_most_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_dtos_perso_most_usuario.setText("Datos de personal");

        javax.swing.GroupLayout btn_datper_most_usuarioLayout = new javax.swing.GroupLayout(btn_datper_most_usuario);
        btn_datper_most_usuario.setLayout(btn_datper_most_usuarioLayout);
        btn_datper_most_usuarioLayout.setHorizontalGroup(
            btn_datper_most_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_most_usuarioLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_dtos_perso_most_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );
        btn_datper_most_usuarioLayout.setVerticalGroup(
            btn_datper_most_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_most_usuarioLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_datper_most_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dtos_perso_most_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_datper_most_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, -1));

        btn_ingred_most_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_ingred_most_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingred_most_usuarioMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_ingre_most_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_ingre_most_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingre_most_usuario.setText("Ingredientes");

        javax.swing.GroupLayout btn_ingred_most_usuarioLayout = new javax.swing.GroupLayout(btn_ingred_most_usuario);
        btn_ingred_most_usuario.setLayout(btn_ingred_most_usuarioLayout);
        btn_ingred_most_usuarioLayout.setHorizontalGroup(
            btn_ingred_most_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_most_usuarioLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingre_most_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        btn_ingred_most_usuarioLayout.setVerticalGroup(
            btn_ingred_most_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_most_usuarioLayout.createSequentialGroup()
                .addGroup(btn_ingred_most_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingre_most_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_pane.add(btn_ingred_most_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));

        btn_admmes_most_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_admmes_most_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_admmes_most_usuarioMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_adm_mesa_most_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_adm_mesa_most_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_adm_mesa_most_usuario.setText("Administrar Mesas");

        javax.swing.GroupLayout btn_admmes_most_usuarioLayout = new javax.swing.GroupLayout(btn_admmes_most_usuario);
        btn_admmes_most_usuario.setLayout(btn_admmes_most_usuarioLayout);
        btn_admmes_most_usuarioLayout.setHorizontalGroup(
            btn_admmes_most_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_most_usuarioLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_adm_mesa_most_usuario)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btn_admmes_most_usuarioLayout.setVerticalGroup(
            btn_admmes_most_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_most_usuarioLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_admmes_most_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adm_mesa_most_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_admmes_most_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, -1));

        btn_prove_most_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_prove_most_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_prove_most_usuarioMouseReleased(evt);
            }
        });

        ind_9.setOpaque(false);
        ind_9.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_9Layout = new javax.swing.GroupLayout(ind_9);
        ind_9.setLayout(ind_9Layout);
        ind_9Layout.setHorizontalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_9Layout.setVerticalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_proveedores_most_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_proveedores_most_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_proveedores_most_usuario.setText("Proveedores");

        javax.swing.GroupLayout btn_prove_most_usuarioLayout = new javax.swing.GroupLayout(btn_prove_most_usuario);
        btn_prove_most_usuario.setLayout(btn_prove_most_usuarioLayout);
        btn_prove_most_usuarioLayout.setHorizontalGroup(
            btn_prove_most_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_most_usuarioLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_proveedores_most_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_prove_most_usuarioLayout.setVerticalGroup(
            btn_prove_most_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_most_usuarioLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_prove_most_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_proveedores_most_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_prove_most_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, -1));

        btn_modulo_documento.setBackground(new java.awt.Color(23, 35, 51));
        btn_modulo_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_modulo_documentoMouseReleased(evt);
            }
        });

        ind_13.setOpaque(false);
        ind_13.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_13Layout = new javax.swing.GroupLayout(ind_13);
        ind_13.setLayout(ind_13Layout);
        ind_13Layout.setHorizontalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_13Layout.setVerticalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_documentos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_documentos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_documentos.setText("Documentos");

        javax.swing.GroupLayout btn_modulo_documentoLayout = new javax.swing.GroupLayout(btn_modulo_documento);
        btn_modulo_documento.setLayout(btn_modulo_documentoLayout);
        btn_modulo_documentoLayout.setHorizontalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btn_modulo_documentoLayout.setVerticalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_documentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_modulo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 140, -1));

        btn_recetario.setBackground(new java.awt.Color(23, 35, 51));
        btn_recetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_recetarioMouseReleased(evt);
            }
        });

        ind_12.setOpaque(false);
        ind_12.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_12Layout = new javax.swing.GroupLayout(ind_12);
        ind_12.setLayout(ind_12Layout);
        ind_12Layout.setHorizontalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_12Layout.setVerticalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_recetario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_recetario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_recetario.setText("Recetario");

        javax.swing.GroupLayout btn_recetarioLayout = new javax.swing.GroupLayout(btn_recetario);
        btn_recetario.setLayout(btn_recetarioLayout);
        btn_recetarioLayout.setHorizontalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_recetario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_recetarioLayout.setVerticalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_recetario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_recetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 590));

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        lbl_tipo_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_tipo_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_usuario.setText("Usuario: Administrador");

        lbl_icono_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_48px.png"))); // NOI18N

        lbl_titulo_adm_perso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo_adm_perso.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo_adm_perso.setText("MOSTRAR USUARIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(lbl_titulo_adm_perso)
                .addGap(151, 151, 151)
                .addComponent(lbl_icono_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_icono_usuario))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_tipo_usuario)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_titulo_adm_perso)
                        .addGap(28, 28, 28))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 940, 90));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_P.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 111, -1));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable_mostrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        jTable_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_mostrar);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 690, 294));

        txt_rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rutKeyTyped(evt);
            }
        });
        getContentPane().add(txt_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 130, -1));

        lbl_rut.setForeground(new java.awt.Color(255, 255, 255));
        lbl_rut.setText("Rut:");
        getContentPane().add(lbl_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        btn_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Read.png"))); // NOI18N
        btn_mostrar.setText("Mostrar");
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 130, -1));

        btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 100, -1));

        jl_info_rut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jl_info_rut.setForeground(new java.awt.Color(255, 255, 255));
        jl_info_rut.setText("(?)");
        getContentPane().add(jl_info_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        lbl_fondo_interfaz_most_usuario.setBackground(new java.awt.Color(83, 83, 83));
        lbl_fondo_interfaz_most_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_personal_final.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo_interfaz_most_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 930, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_inicio_most_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicio_most_usuarioMousePressed
        // TODO add your handling code here:
        setColor(btn_inicio_most_usuario);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_most_usuario,btn_ingred_most_usuario,btn_admmes_most_usuario}, new JPanel[]{ind_2,ind_3, ind_4});
        Menu_principal mp = new Menu_principal();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicio_most_usuarioMousePressed

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?");
        if (JOptionPane.OK_OPTION == exit)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitMousePressed

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("Rut");
        modelo.addColumn("Digito verificador");
        modelo.addColumn("Nombre personal");
        modelo.addColumn("Apellido personal");
        modelo.addColumn("Correo");
        modelo.addColumn("Celular:");
        modelo.addColumn("Tipo Personal:");
        this.jTable_mostrar.setModel(modelo);

        try {
            ResultSet rs = Manejadora.mostrarPersonal();
            String [] datos = new String[7];
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                modelo.addRow(datos);
                this.jTable_mostrar.setModel(modelo);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_mostrarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        Ventanas_Administracion.Administrar_datos_personal dp = new Ventanas_Administracion.Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_volverActionPerformed

    private void txt_rutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rutKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txt_rutKeyTyped

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        try
        {
            DefaultTableModel modelo= new DefaultTableModel();
            modelo.addColumn("Rut");
            modelo.addColumn("Digito verificador");
            modelo.addColumn("Nombre personal");
            modelo.addColumn("Apellido personal");
            modelo.addColumn("Celular");
            modelo.addColumn("Correo");
            modelo.addColumn("Tipo personal");
            this.jTable_mostrar.setModel(modelo);
            try {
                ResultSet rs = Manejadora.buscarPersonal(this.txt_rut.getText());
                String [] datos = new String[7];
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    modelo.addRow(datos);
                    this.jTable_mostrar.setModel(modelo);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se ha ingresado un rut");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_datper_most_usuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datper_most_usuarioMouseReleased
        // TODO add your handling code here:
        setColor(btn_datper_most_usuario);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_inicio_most_usuario,btn_ingred_most_usuario,btn_admmes_most_usuario}, new JPanel[]{ind_1,ind_3, ind_4});
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_datper_most_usuarioMouseReleased

    private void btn_ingred_most_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingred_most_usuarioMousePressed
        // TODO add your handling code here:
        setColor(btn_ingred_most_usuario);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_most_usuario,btn_inicio_most_usuario,btn_admmes_most_usuario}, new JPanel[]{ind_2,ind_1, ind_4});
        interfaz_Ingrediente adm_ingre = new interfaz_Ingrediente();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingred_most_usuarioMousePressed

    private void btn_admmes_most_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_admmes_most_usuarioMousePressed
        // TODO add your handling code here:
        setColor(btn_admmes_most_usuario);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_most_usuario,btn_ingred_most_usuario,btn_inicio_most_usuario}, new JPanel[]{ind_2,ind_3, ind_1});
        Administrar_Mesas adm_mesa = new Administrar_Mesas();
        adm_mesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_admmes_most_usuarioMousePressed

    private void btn_prove_most_usuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prove_most_usuarioMouseReleased
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_prove_most_usuarioMouseReleased

    private void btn_modulo_documentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulo_documentoMouseReleased
        Interfaz_Factura adm_ingre = new Interfaz_Factura();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modulo_documentoMouseReleased

    private void btn_recetarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recetarioMouseReleased
        interfaz_Recetario adm_ingre = new interfaz_Recetario();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_recetarioMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_mostrar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_mostrar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_mostrar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_mostrar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_mostrar_Usuario().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_admmes_most_usuario;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JPanel btn_datper_most_usuario;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel btn_ingred_most_usuario;
    private javax.swing.JPanel btn_inicio_most_usuario;
    private javax.swing.JPanel btn_modulo_documento;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JPanel btn_prove_most_usuario;
    private javax.swing.JPanel btn_recetario;
    private javax.swing.JButton btn_volver;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_12;
    private javax.swing.JPanel ind_13;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_mostrar;
    private javax.swing.JLabel jl_info_rut;
    private javax.swing.JLabel lbl_adm_mesa_most_usuario;
    private javax.swing.JLabel lbl_documentos;
    private javax.swing.JLabel lbl_dtos_perso_most_usuario;
    private javax.swing.JLabel lbl_fondo_interfaz_most_usuario;
    private javax.swing.JLabel lbl_icono_usuario;
    private javax.swing.JLabel lbl_ingre_most_usuario;
    private javax.swing.JLabel lbl_inicio_most_usuario;
    private javax.swing.JLabel lbl_logoazul_restau;
    private javax.swing.JLabel lbl_proveedores_most_usuario;
    private javax.swing.JLabel lbl_recetario;
    private javax.swing.JLabel lbl_rut;
    private javax.swing.JLabel lbl_tipo_usuario;
    private javax.swing.JLabel lbl_titulo_adm_perso;
    private javax.swing.JPanel side_pane;
    private javax.swing.JPanel side_pane1;
    private javax.swing.JPanel side_pane2;
    private javax.swing.JPanel side_pane3;
    private javax.swing.JPanel side_pane4;
    private javax.swing.JPanel side_pane5;
    private javax.swing.JPanel side_pane6;
    private javax.swing.JPanel side_pane8;
    private javax.swing.JPanel side_pane9;
    private javax.swing.JTextField txt_rut;
    // End of variables declaration//GEN-END:variables
}
