/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuario;

import Clases.Manejadora;
import Clases.Personal;
import Ventanas_Administracion.Administrar_Mesas;
import Ventanas_Administracion.Administrar_Proveedor;
import Ventanas_Administracion.Administrar_datos_personal;
import Ventanas_Administracion.Menu_principal;
import Vista.Factura.Interfaz_Factura;
import Vista.Ingrediente.interfaz_Ingrediente;
import Vista.Recetario.interfaz_Recetario;
//import Ventanas.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Interfaz_Agregar_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Interfaz_Agregar_Usuario() {
        initComponents();
        this.setLocationRelativeTo(this);
        setColor(btn_inicio_agre_usuario); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_agre_usuario,btn_ingred_agre_usuario,btn_admmes_agre_usuario}, new JPanel[]{ind_2,ind_3, ind_4});
        //jProgressBar1.setValue(50);
        jl_info_rut.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese su rut con digito verificador.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        jb_info_nombre.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese su primer nombre o los dos nombres.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        jb_info_apellido.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese su primer apellido o los dos apellido.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        btn_agregar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Agrega los datos ingresados.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        btn_volver.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Regresa una ventana atras.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_rut_personal = new javax.swing.JLabel();
        txt_rut_personal = new javax.swing.JTextField();
        txt_verificador = new javax.swing.JTextField();
        jl_info_rut = new javax.swing.JLabel();
        lbl_nombre_personal = new javax.swing.JLabel();
        txt_nombre_personal = new javax.swing.JTextField();
        jb_info_nombre = new javax.swing.JLabel();
        lbl_ape_paterno = new javax.swing.JLabel();
        txt_ape_personal = new javax.swing.JTextField();
        jb_info_apellido = new javax.swing.JLabel();
        lbl_celular = new javax.swing.JLabel();
        txt_celular = new javax.swing.JTextField();
        lbl_logoazul_restau = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        side_pane = new javax.swing.JPanel();
        btn_inicio_agre_usuario = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lbl_inicio_agre_usuario = new javax.swing.JLabel();
        btn_datper_agre_usuario = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbl_dtos_perso_agre_usuario = new javax.swing.JLabel();
        btn_ingred_agre_usuario = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbl_ingre_agre_usuario = new javax.swing.JLabel();
        btn_admmes_agre_usuario = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbl_adm_mesa_agre_usuario = new javax.swing.JLabel();
        btn_prove_agre_usuario = new javax.swing.JPanel();
        ind_9 = new javax.swing.JPanel();
        lbl_proveedores_agre_usuario = new javax.swing.JLabel();
        side_pane1 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JLabel();
        btn_recetario = new javax.swing.JPanel();
        ind_12 = new javax.swing.JPanel();
        lbl_recetario = new javax.swing.JLabel();
        btn_modulo_documento = new javax.swing.JPanel();
        ind_13 = new javax.swing.JPanel();
        lbl_documentos = new javax.swing.JLabel();
        lbl_tipo_personal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        lbl_tipo_usuario = new javax.swing.JLabel();
        lbl_icono_usuario = new javax.swing.JLabel();
        lbl_titulo_agre_personal = new javax.swing.JLabel();
        cbo_tipo_personal = new javax.swing.JComboBox<>();
        lbl_logorojo_restau = new javax.swing.JLabel();
        lbl_fondo_interfaz_agre_personal = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_rut_personal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_rut_personal.setText("Rut personal:");
        getContentPane().add(lbl_rut_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 94, -1));

        txt_rut_personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rut_personalActionPerformed(evt);
            }
        });
        txt_rut_personal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rut_personalKeyTyped(evt);
            }
        });
        getContentPane().add(txt_rut_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 72, -1));

        txt_verificador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_verificadorKeyTyped(evt);
            }
        });
        getContentPane().add(txt_verificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 21, -1));

        jl_info_rut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jl_info_rut.setForeground(new java.awt.Color(255, 255, 255));
        jl_info_rut.setText("(?)");
        getContentPane().add(jl_info_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        lbl_nombre_personal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre_personal.setText("Nombre Personal:");
        getContentPane().add(lbl_nombre_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        txt_nombre_personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_personalActionPerformed(evt);
            }
        });
        txt_nombre_personal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_personalKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 190, -1));

        jb_info_nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_info_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jb_info_nombre.setText("(?)");
        getContentPane().add(jb_info_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 21, -1));

        lbl_ape_paterno.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ape_paterno.setText("Apellido Personal:");
        getContentPane().add(lbl_ape_paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 111, -1));

        txt_ape_personal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ape_personalKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ape_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 190, -1));

        jb_info_apellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_info_apellido.setForeground(new java.awt.Color(255, 255, 255));
        jb_info_apellido.setText("(?)");
        getContentPane().add(jb_info_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        lbl_celular.setForeground(new java.awt.Color(255, 255, 255));
        lbl_celular.setText("Celular:");
        getContentPane().add(lbl_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        txt_celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_celularKeyTyped(evt);
            }
        });
        getContentPane().add(txt_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 190, -1));

        lbl_logoazul_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_superior_blanco.png"))); // NOI18N
        getContentPane().add(lbl_logoazul_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 90));

        lbl_correo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_correo.setText("Correo:");
        getContentPane().add(lbl_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 190, -1));

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save.png"))); // NOI18N
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 110, -1));

        btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 80, -1));

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio_agre_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_inicio_agre_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicio_agre_usuarioMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_inicio_agre_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_inicio_agre_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio_agre_usuario.setText("Inicio");

        javax.swing.GroupLayout btn_inicio_agre_usuarioLayout = new javax.swing.GroupLayout(btn_inicio_agre_usuario);
        btn_inicio_agre_usuario.setLayout(btn_inicio_agre_usuarioLayout);
        btn_inicio_agre_usuarioLayout.setHorizontalGroup(
            btn_inicio_agre_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_agre_usuarioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbl_inicio_agre_usuario)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_inicio_agre_usuarioLayout.setVerticalGroup(
            btn_inicio_agre_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_agre_usuarioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_inicio_agre_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inicio_agre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_inicio_agre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        btn_datper_agre_usuario.setBackground(new java.awt.Color(251, 243, 0));
        btn_datper_agre_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_datper_agre_usuarioMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_dtos_perso_agre_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_dtos_perso_agre_usuario.setText("Datos de personal");

        javax.swing.GroupLayout btn_datper_agre_usuarioLayout = new javax.swing.GroupLayout(btn_datper_agre_usuario);
        btn_datper_agre_usuario.setLayout(btn_datper_agre_usuarioLayout);
        btn_datper_agre_usuarioLayout.setHorizontalGroup(
            btn_datper_agre_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_agre_usuarioLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_dtos_perso_agre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );
        btn_datper_agre_usuarioLayout.setVerticalGroup(
            btn_datper_agre_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_agre_usuarioLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_datper_agre_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dtos_perso_agre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_datper_agre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, -1));

        btn_ingred_agre_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_ingred_agre_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingred_agre_usuarioMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_ingre_agre_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_ingre_agre_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingre_agre_usuario.setText("Ingredientes");

        javax.swing.GroupLayout btn_ingred_agre_usuarioLayout = new javax.swing.GroupLayout(btn_ingred_agre_usuario);
        btn_ingred_agre_usuario.setLayout(btn_ingred_agre_usuarioLayout);
        btn_ingred_agre_usuarioLayout.setHorizontalGroup(
            btn_ingred_agre_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_agre_usuarioLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingre_agre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        btn_ingred_agre_usuarioLayout.setVerticalGroup(
            btn_ingred_agre_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_agre_usuarioLayout.createSequentialGroup()
                .addGroup(btn_ingred_agre_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingre_agre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_pane.add(btn_ingred_agre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));

        btn_admmes_agre_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_admmes_agre_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_admmes_agre_usuarioMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_adm_mesa_agre_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_adm_mesa_agre_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_adm_mesa_agre_usuario.setText("Administrar Mesas");

        javax.swing.GroupLayout btn_admmes_agre_usuarioLayout = new javax.swing.GroupLayout(btn_admmes_agre_usuario);
        btn_admmes_agre_usuario.setLayout(btn_admmes_agre_usuarioLayout);
        btn_admmes_agre_usuarioLayout.setHorizontalGroup(
            btn_admmes_agre_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_agre_usuarioLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_adm_mesa_agre_usuario)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btn_admmes_agre_usuarioLayout.setVerticalGroup(
            btn_admmes_agre_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_agre_usuarioLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_admmes_agre_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adm_mesa_agre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_admmes_agre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, -1));

        btn_prove_agre_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_prove_agre_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_prove_agre_usuarioMouseReleased(evt);
            }
        });

        ind_9.setOpaque(false);
        ind_9.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_9Layout = new javax.swing.GroupLayout(ind_9);
        ind_9.setLayout(ind_9Layout);
        ind_9Layout.setHorizontalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_9Layout.setVerticalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_proveedores_agre_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_proveedores_agre_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_proveedores_agre_usuario.setText("Proveedores");

        javax.swing.GroupLayout btn_prove_agre_usuarioLayout = new javax.swing.GroupLayout(btn_prove_agre_usuario);
        btn_prove_agre_usuario.setLayout(btn_prove_agre_usuarioLayout);
        btn_prove_agre_usuarioLayout.setHorizontalGroup(
            btn_prove_agre_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_agre_usuarioLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_proveedores_agre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_prove_agre_usuarioLayout.setVerticalGroup(
            btn_prove_agre_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_agre_usuarioLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_prove_agre_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_proveedores_agre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_prove_agre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, -1));

        side_pane1.setBackground(new java.awt.Color(251, 243, 0));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane.add(side_pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 10, 500));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        side_pane.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 30, 46));

        btn_recetario.setBackground(new java.awt.Color(23, 35, 51));
        btn_recetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_recetarioMouseReleased(evt);
            }
        });

        ind_12.setOpaque(false);
        ind_12.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_12Layout = new javax.swing.GroupLayout(ind_12);
        ind_12.setLayout(ind_12Layout);
        ind_12Layout.setHorizontalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_12Layout.setVerticalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_recetario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_recetario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_recetario.setText("Recetario");

        javax.swing.GroupLayout btn_recetarioLayout = new javax.swing.GroupLayout(btn_recetario);
        btn_recetario.setLayout(btn_recetarioLayout);
        btn_recetarioLayout.setHorizontalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_recetario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_recetarioLayout.setVerticalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_recetario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_recetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, -1));

        btn_modulo_documento.setBackground(new java.awt.Color(23, 35, 51));
        btn_modulo_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_modulo_documentoMouseReleased(evt);
            }
        });

        ind_13.setOpaque(false);
        ind_13.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_13Layout = new javax.swing.GroupLayout(ind_13);
        ind_13.setLayout(ind_13Layout);
        ind_13Layout.setHorizontalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_13Layout.setVerticalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_documentos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_documentos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_documentos.setText("Documentos");

        javax.swing.GroupLayout btn_modulo_documentoLayout = new javax.swing.GroupLayout(btn_modulo_documento);
        btn_modulo_documento.setLayout(btn_modulo_documentoLayout);
        btn_modulo_documentoLayout.setHorizontalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btn_modulo_documentoLayout.setVerticalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_documentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_modulo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 140, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 590));

        lbl_tipo_personal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_personal.setText("Tipo Personal:");
        getContentPane().add(lbl_tipo_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(123, 156, 225));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setPreferredSize(new java.awt.Dimension(2, 20));

        lbl_tipo_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_tipo_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_usuario.setText("Usuario: Administrador");

        lbl_icono_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_48px.png"))); // NOI18N

        lbl_titulo_agre_personal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo_agre_personal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo_agre_personal.setText("AGREGAR USUARIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_titulo_agre_personal)
                        .addGap(115, 115, 115)
                        .addComponent(lbl_icono_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_icono_usuario)
                            .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbl_titulo_agre_personal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 90));

        cbo_tipo_personal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrador", "Jefe Personal", "Guardia", "Garzon/a", "Encargado del bar", "Cocinero" }));
        cbo_tipo_personal.setDoubleBuffered(true);
        getContentPane().add(cbo_tipo_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 190, -1));

        lbl_logorojo_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_final.png"))); // NOI18N
        lbl_logorojo_restau.setText("jLabel17");
        getContentPane().add(lbl_logorojo_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 260, 320));

        lbl_fondo_interfaz_agre_personal.setBackground(new java.awt.Color(83, 83, 83));
        lbl_fondo_interfaz_agre_personal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_personal_final.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo_interfaz_agre_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 920, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_inicio_agre_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicio_agre_usuarioMousePressed
        // TODO add your handling code here:
        setColor(btn_inicio_agre_usuario);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_agre_usuario,btn_ingred_agre_usuario,btn_admmes_agre_usuario}, new JPanel[]{ind_2,ind_3, ind_4});
        Menu_principal  mp = new Menu_principal();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicio_agre_usuarioMousePressed

    private void btn_datper_agre_usuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datper_agre_usuarioMouseReleased
        // TODO add your handling code here:
        setColor(btn_datper_agre_usuario);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_inicio_agre_usuario,btn_ingred_agre_usuario,btn_admmes_agre_usuario}, new JPanel[]{ind_1,ind_3, ind_4});
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_datper_agre_usuarioMouseReleased

    private void btn_ingred_agre_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingred_agre_usuarioMousePressed
        // TODO add your handling code here:
        setColor(btn_ingred_agre_usuario);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_agre_usuario,btn_inicio_agre_usuario,btn_admmes_agre_usuario}, new JPanel[]{ind_2,ind_1, ind_4});
       interfaz_Ingrediente adm_ingre = new interfaz_Ingrediente();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingred_agre_usuarioMousePressed

    private void btn_admmes_agre_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_admmes_agre_usuarioMousePressed
        // TODO add your handling code here:
        setColor(btn_admmes_agre_usuario);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_agre_usuario,btn_ingred_agre_usuario,btn_inicio_agre_usuario}, new JPanel[]{ind_2,ind_3, ind_1});
        Administrar_Mesas adm_mesa = new Administrar_Mesas();
        adm_mesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_admmes_agre_usuarioMousePressed

    private void btn_prove_agre_usuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prove_agre_usuarioMouseReleased
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_prove_agre_usuarioMouseReleased

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?");
        if (JOptionPane.OK_OPTION == exit)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitMousePressed

    private void txt_rut_personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rut_personalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rut_personalActionPerformed

    private void txt_rut_personalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rut_personalKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txt_rut_personalKeyTyped

    private void txt_verificadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_verificadorKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' && n !='k' && n !='K' )evt.consume();
    }//GEN-LAST:event_txt_verificadorKeyTyped

    private void txt_nombre_personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_personalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_personalActionPerformed

    private void txt_nombre_personalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_personalKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if((n<'a' || n>'z') && (n<'A' || n>'Z') && (n<' ' || n>' '))evt.consume();
    }//GEN-LAST:event_txt_nombre_personalKeyTyped

    private void txt_ape_personalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ape_personalKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if((n<'a' || n>'z') && (n<'A' || n>'Z') && (n<' ' || n>' '))evt.consume();
    }//GEN-LAST:event_txt_ape_personalKeyTyped

    private void txt_celularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_celularKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txt_celularKeyTyped

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        try
        {
            Personal per = new Personal();
            per.setRut_personal(txt_rut_personal.getText().trim());
            per.setDigito_v(txt_verificador.getText().trim());
            per.setNombre_p(txt_nombre_personal.getText().trim());
            per.setApellido_p(txt_ape_personal.getText().trim());
            per.setNumero_p(Integer.parseInt(txt_celular.getText().trim()));
            per.setCorreo_p(txt_correo.getText().trim());
            if(cbo_tipo_personal.getSelectedIndex() == 0)
            {
                per.setTip_personal("Sin definir");
            }else {
                per.setTip_personal(cbo_tipo_personal.getSelectedItem().toString());
            }

            if (Manejadora.agregarPersonal(per))
            {
                JOptionPane.showMessageDialog(null, "Se ha creado un registro exitosamente");
                this.txt_rut_personal.setText(null);
                this.txt_verificador.setText(null);
                this.txt_nombre_personal.setText(null);
                this.txt_ape_personal.setText(null);
                this.txt_celular.setText(null);
                this.txt_correo.setText(null);
                this.cbo_tipo_personal.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "no se pudo crear el registro","ERROR",0);
            }

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se han ingresado datos", "Informacion", 1);
        }

    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        Ventanas_Administracion.Administrar_datos_personal dp = new Ventanas_Administracion.Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_recetarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recetarioMouseReleased
        interfaz_Recetario adm_ingre = new interfaz_Recetario();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_recetarioMouseReleased

    private void btn_modulo_documentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulo_documentoMouseReleased
        Interfaz_Factura adm_ingre = new Interfaz_Factura();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modulo_documentoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Agregar_Usuario().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_admmes_agre_usuario;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JPanel btn_datper_agre_usuario;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel btn_ingred_agre_usuario;
    private javax.swing.JPanel btn_inicio_agre_usuario;
    private javax.swing.JPanel btn_modulo_documento;
    private javax.swing.JPanel btn_prove_agre_usuario;
    private javax.swing.JPanel btn_recetario;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cbo_tipo_personal;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_12;
    private javax.swing.JPanel ind_13;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jb_info_apellido;
    private javax.swing.JLabel jb_info_nombre;
    private javax.swing.JLabel jl_info_rut;
    private javax.swing.JLabel lbl_adm_mesa_agre_usuario;
    private javax.swing.JLabel lbl_ape_paterno;
    private javax.swing.JLabel lbl_celular;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_documentos;
    private javax.swing.JLabel lbl_dtos_perso_agre_usuario;
    private javax.swing.JLabel lbl_fondo_interfaz_agre_personal;
    private javax.swing.JLabel lbl_icono_usuario;
    private javax.swing.JLabel lbl_ingre_agre_usuario;
    private javax.swing.JLabel lbl_inicio_agre_usuario;
    private javax.swing.JLabel lbl_logoazul_restau;
    private javax.swing.JLabel lbl_logorojo_restau;
    private javax.swing.JLabel lbl_nombre_personal;
    private javax.swing.JLabel lbl_proveedores_agre_usuario;
    private javax.swing.JLabel lbl_recetario;
    private javax.swing.JLabel lbl_rut_personal;
    private javax.swing.JLabel lbl_tipo_personal;
    private javax.swing.JLabel lbl_tipo_usuario;
    private javax.swing.JLabel lbl_titulo_agre_personal;
    private javax.swing.JPanel side_pane;
    private javax.swing.JPanel side_pane1;
    private javax.swing.JTextField txt_ape_personal;
    private javax.swing.JTextField txt_celular;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nombre_personal;
    private javax.swing.JTextField txt_rut_personal;
    private javax.swing.JTextField txt_verificador;
    // End of variables declaration//GEN-END:variables
}
