/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuario;

//import Ventanas.*;
import java.awt.Color;
import javax.swing.JPanel;
import Clases.Manejadora;
import Clases.Personal;
import Ventanas_Administracion.Administrar_Mesas;
import Ventanas_Administracion.Administrar_Proveedor;
import Ventanas_Administracion.Administrar_datos_personal;
import Ventanas_Administracion.Menu_principal;
import Vista.Factura.Interfaz_Factura;
import Vista.Ingrediente.interfaz_Ingrediente;
import Vista.Recetario.interfaz_Recetario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Interfaz_Modificar_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Interfaz_Modificar_Usuario() {
        initComponents();
        this.setLocationRelativeTo(this);
        setColor(btn_inicio_mod_usuario); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_mod_usuario,btn_ingred_mod_usuario,btn_admmes_mod_usuario}, new JPanel[]{ind_2,ind_3, ind_4});
        //jProgressBar1.setValue(50);
        jl_info_rut_buscar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese su rut y digito verificador.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
                btn_buscar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Busca un personal mediante su rut y digito verificador.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
                btn_volver.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Regresa una ventana atras.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        btn_modificar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Actualiza los datos del personal seleccionado.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
    }
    
    public void mostarPersonal()
    {
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("Rut");
        modelo.addColumn("Digito verificador");
        modelo.addColumn("Nombre personal");
        modelo.addColumn("Apellido personal");
        modelo.addColumn("Correo");
        modelo.addColumn("Celular:");
        modelo.addColumn("Tipo Personal:");
        this.jTable_mostrar.setModel(modelo);

        try {
            ResultSet rs = Manejadora.mostrarPersonal();
            String [] datos = new String[7];
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                modelo.addRow(datos);
                this.jTable_mostrar.setModel(modelo);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_mostrar = new javax.swing.JButton();
        side_pane12 = new javax.swing.JPanel();
        side_pane13 = new javax.swing.JPanel();
        side_pane14 = new javax.swing.JPanel();
        side_pane15 = new javax.swing.JPanel();
        side_pane16 = new javax.swing.JPanel();
        side_pane17 = new javax.swing.JPanel();
        side_pane11 = new javax.swing.JPanel();
        side_pane1 = new javax.swing.JPanel();
        side_pane10 = new javax.swing.JPanel();
        side_pane6 = new javax.swing.JPanel();
        side_pane2 = new javax.swing.JPanel();
        side_pane5 = new javax.swing.JPanel();
        side_pane8 = new javax.swing.JPanel();
        side_pane9 = new javax.swing.JPanel();
        side_pane3 = new javax.swing.JPanel();
        side_pane4 = new javax.swing.JPanel();
        lbl_logoazul_restau = new javax.swing.JLabel();
        side_pane = new javax.swing.JPanel();
        btn_inicio_mod_usuario = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lbl_inicio_mod_usuario = new javax.swing.JLabel();
        btn_datper_mod_usuario = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbl_dtos_perso_mod_usuario = new javax.swing.JLabel();
        btn_ingred_mod_usuario = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbl_ingre_mod_usuario = new javax.swing.JLabel();
        btn_admmes_mod_usuario = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbl_adm_mesa_mod_usuario = new javax.swing.JLabel();
        btn_prove_mod_usuario = new javax.swing.JPanel();
        ind_9 = new javax.swing.JPanel();
        lbl_prove_adm_perso = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        btn_modulo_documento = new javax.swing.JPanel();
        ind_13 = new javax.swing.JPanel();
        lbl_documentos = new javax.swing.JLabel();
        btn_recetario = new javax.swing.JPanel();
        ind_12 = new javax.swing.JPanel();
        lbl_recetario = new javax.swing.JLabel();
        lbl_titulo_mod_usuario = new javax.swing.JPanel();
        lbl_tipo_usuario = new javax.swing.JLabel();
        lbl_icono_usuario = new javax.swing.JLabel();
        lbl_titulo_adm_perso = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        lbl_ape_personal = new javax.swing.JLabel();
        lbl_rut = new javax.swing.JLabel();
        txtape = new javax.swing.JTextField();
        txtrut = new javax.swing.JTextField();
        lbl_correo_personal = new javax.swing.JLabel();
        lbl_celular_personal = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_mostrar = new javax.swing.JTable();
        txtcorreo = new javax.swing.JTextField();
        txtcel = new javax.swing.JTextField();
        btn_modificar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        lbl_rut_usuario = new javax.swing.JLabel();
        txt_rut = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lbl_nombre_personal = new javax.swing.JLabel();
        txtdvrut = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_dvrut = new javax.swing.JTextField();
        jl_info_rut_buscar = new javax.swing.JLabel();
        jl_info_mostrar = new javax.swing.JLabel();
        lbl_tipo_personal = new javax.swing.JLabel();
        jctipo_personal = new javax.swing.JComboBox<>();
        lbl_fondo_interfaz_mod_usuario = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Read.png"))); // NOI18N
        btn_mostrar.setText("Mostrar");
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 110, -1));

        side_pane12.setBackground(new java.awt.Color(251, 243, 0));
        side_pane12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane13.setBackground(new java.awt.Color(251, 243, 0));
        side_pane13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane12.add(side_pane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        getContentPane().add(side_pane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 10, 80));

        side_pane14.setBackground(new java.awt.Color(251, 243, 0));
        side_pane14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane15.setBackground(new java.awt.Color(251, 243, 0));
        side_pane15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane14.add(side_pane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane16.setBackground(new java.awt.Color(251, 243, 0));
        side_pane16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane17.setBackground(new java.awt.Color(251, 243, 0));
        side_pane17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane16.add(side_pane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane14.add(side_pane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 690, 10));

        getContentPane().add(side_pane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 440, 10));

        side_pane11.setBackground(new java.awt.Color(251, 243, 0));
        side_pane11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 10, 80));

        side_pane1.setBackground(new java.awt.Color(251, 243, 0));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 10, 500));

        side_pane10.setBackground(new java.awt.Color(251, 243, 0));
        side_pane10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 450, 10));

        side_pane6.setBackground(new java.awt.Color(251, 243, 0));
        side_pane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 10, 210));

        side_pane2.setBackground(new java.awt.Color(251, 243, 0));
        side_pane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane5.setBackground(new java.awt.Color(251, 243, 0));
        side_pane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane2.add(side_pane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane8.setBackground(new java.awt.Color(251, 243, 0));
        side_pane8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane9.setBackground(new java.awt.Color(251, 243, 0));
        side_pane9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane8.add(side_pane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane2.add(side_pane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 690, 10));

        getContentPane().add(side_pane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 690, 10));

        side_pane3.setBackground(new java.awt.Color(251, 243, 0));
        side_pane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 710, 10));

        side_pane4.setBackground(new java.awt.Color(251, 243, 0));
        side_pane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 10, 210));

        lbl_logoazul_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_superior_blanco.png"))); // NOI18N
        lbl_logoazul_restau.setText("jLabel17");
        getContentPane().add(lbl_logoazul_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 205, -1));

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio_mod_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_inicio_mod_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicio_mod_usuarioMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_inicio_mod_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_inicio_mod_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio_mod_usuario.setText("Inicio");

        javax.swing.GroupLayout btn_inicio_mod_usuarioLayout = new javax.swing.GroupLayout(btn_inicio_mod_usuario);
        btn_inicio_mod_usuario.setLayout(btn_inicio_mod_usuarioLayout);
        btn_inicio_mod_usuarioLayout.setHorizontalGroup(
            btn_inicio_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_mod_usuarioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbl_inicio_mod_usuario)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        btn_inicio_mod_usuarioLayout.setVerticalGroup(
            btn_inicio_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_mod_usuarioLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_inicio_mod_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inicio_mod_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_inicio_mod_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        btn_datper_mod_usuario.setBackground(new java.awt.Color(251, 243, 0));
        btn_datper_mod_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_datper_mod_usuarioMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_dtos_perso_mod_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_dtos_perso_mod_usuario.setText("Datos de personal");

        javax.swing.GroupLayout btn_datper_mod_usuarioLayout = new javax.swing.GroupLayout(btn_datper_mod_usuario);
        btn_datper_mod_usuario.setLayout(btn_datper_mod_usuarioLayout);
        btn_datper_mod_usuarioLayout.setHorizontalGroup(
            btn_datper_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_mod_usuarioLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_dtos_perso_mod_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );
        btn_datper_mod_usuarioLayout.setVerticalGroup(
            btn_datper_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_mod_usuarioLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_datper_mod_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dtos_perso_mod_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_datper_mod_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 130, -1));

        btn_ingred_mod_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_ingred_mod_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingred_mod_usuarioMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_ingre_mod_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_ingre_mod_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingre_mod_usuario.setText("Ingredientes");

        javax.swing.GroupLayout btn_ingred_mod_usuarioLayout = new javax.swing.GroupLayout(btn_ingred_mod_usuario);
        btn_ingred_mod_usuario.setLayout(btn_ingred_mod_usuarioLayout);
        btn_ingred_mod_usuarioLayout.setHorizontalGroup(
            btn_ingred_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_mod_usuarioLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingre_mod_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        btn_ingred_mod_usuarioLayout.setVerticalGroup(
            btn_ingred_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_mod_usuarioLayout.createSequentialGroup()
                .addGroup(btn_ingred_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingre_mod_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_pane.add(btn_ingred_mod_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 120, 40));

        btn_admmes_mod_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_admmes_mod_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_admmes_mod_usuarioMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_adm_mesa_mod_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_adm_mesa_mod_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_adm_mesa_mod_usuario.setText("Administrar Meses");

        javax.swing.GroupLayout btn_admmes_mod_usuarioLayout = new javax.swing.GroupLayout(btn_admmes_mod_usuario);
        btn_admmes_mod_usuario.setLayout(btn_admmes_mod_usuarioLayout);
        btn_admmes_mod_usuarioLayout.setHorizontalGroup(
            btn_admmes_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_mod_usuarioLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_adm_mesa_mod_usuario)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btn_admmes_mod_usuarioLayout.setVerticalGroup(
            btn_admmes_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_mod_usuarioLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_admmes_mod_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adm_mesa_mod_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_admmes_mod_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, -1));

        btn_prove_mod_usuario.setBackground(new java.awt.Color(23, 35, 51));
        btn_prove_mod_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_prove_mod_usuarioMouseReleased(evt);
            }
        });

        ind_9.setOpaque(false);
        ind_9.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_9Layout = new javax.swing.GroupLayout(ind_9);
        ind_9.setLayout(ind_9Layout);
        ind_9Layout.setHorizontalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_9Layout.setVerticalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_prove_adm_perso.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_prove_adm_perso.setForeground(new java.awt.Color(255, 255, 255));
        lbl_prove_adm_perso.setText("Proveedores");

        javax.swing.GroupLayout btn_prove_mod_usuarioLayout = new javax.swing.GroupLayout(btn_prove_mod_usuario);
        btn_prove_mod_usuario.setLayout(btn_prove_mod_usuarioLayout);
        btn_prove_mod_usuarioLayout.setHorizontalGroup(
            btn_prove_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_mod_usuarioLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_prove_adm_perso)
                .addGap(0, 44, Short.MAX_VALUE))
        );
        btn_prove_mod_usuarioLayout.setVerticalGroup(
            btn_prove_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_mod_usuarioLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_prove_mod_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_prove_adm_perso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_prove_mod_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 130, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        side_pane.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 30, 46));

        btn_modulo_documento.setBackground(new java.awt.Color(23, 35, 51));
        btn_modulo_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_modulo_documentoMouseReleased(evt);
            }
        });

        ind_13.setOpaque(false);
        ind_13.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_13Layout = new javax.swing.GroupLayout(ind_13);
        ind_13.setLayout(ind_13Layout);
        ind_13Layout.setHorizontalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_13Layout.setVerticalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_documentos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_documentos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_documentos.setText("Documentos");

        javax.swing.GroupLayout btn_modulo_documentoLayout = new javax.swing.GroupLayout(btn_modulo_documento);
        btn_modulo_documento.setLayout(btn_modulo_documentoLayout);
        btn_modulo_documentoLayout.setHorizontalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btn_modulo_documentoLayout.setVerticalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lbl_documentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_pane.add(btn_modulo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 140, -1));

        btn_recetario.setBackground(new java.awt.Color(23, 35, 51));
        btn_recetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_recetarioMouseReleased(evt);
            }
        });

        ind_12.setOpaque(false);
        ind_12.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_12Layout = new javax.swing.GroupLayout(ind_12);
        ind_12.setLayout(ind_12Layout);
        ind_12Layout.setHorizontalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_12Layout.setVerticalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_recetario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_recetario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_recetario.setText("Recetario");

        javax.swing.GroupLayout btn_recetarioLayout = new javax.swing.GroupLayout(btn_recetario);
        btn_recetario.setLayout(btn_recetarioLayout);
        btn_recetarioLayout.setHorizontalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_recetario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_recetarioLayout.setVerticalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_recetario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_recetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 590));

        lbl_titulo_mod_usuario.setBackground(new java.awt.Color(23, 35, 51));
        lbl_titulo_mod_usuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl_titulo_mod_usuarioMouseDragged(evt);
            }
        });
        lbl_titulo_mod_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_titulo_mod_usuarioMousePressed(evt);
            }
        });

        lbl_tipo_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_tipo_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_usuario.setText("Usuario: Administrador");

        lbl_icono_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_48px.png"))); // NOI18N

        lbl_titulo_adm_perso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo_adm_perso.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo_adm_perso.setText("MODIFICAR USUARIO");

        javax.swing.GroupLayout lbl_titulo_mod_usuarioLayout = new javax.swing.GroupLayout(lbl_titulo_mod_usuario);
        lbl_titulo_mod_usuario.setLayout(lbl_titulo_mod_usuarioLayout);
        lbl_titulo_mod_usuarioLayout.setHorizontalGroup(
            lbl_titulo_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_titulo_mod_usuarioLayout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(lbl_titulo_adm_perso)
                .addGap(179, 179, 179)
                .addComponent(lbl_icono_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lbl_titulo_mod_usuarioLayout.setVerticalGroup(
            lbl_titulo_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbl_titulo_mod_usuarioLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(lbl_titulo_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(lbl_titulo_mod_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_titulo_adm_perso)
                        .addComponent(lbl_icono_usuario)))
                .addContainerGap())
        );

        getContentPane().add(lbl_titulo_mod_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 90));

        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomKeyTyped(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 155, -1));

        lbl_ape_personal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ape_personal.setText("Apellido Personal:");
        getContentPane().add(lbl_ape_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        lbl_rut.setForeground(new java.awt.Color(255, 255, 255));
        lbl_rut.setText("Rut:");
        getContentPane().add(lbl_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        txtape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapeKeyTyped(evt);
            }
        });
        getContentPane().add(txtape, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 155, -1));

        txtrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutKeyTyped(evt);
            }
        });
        getContentPane().add(txtrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 125, -1));

        lbl_correo_personal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_correo_personal.setText("Correo:");
        getContentPane().add(lbl_correo_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        lbl_celular_personal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_celular_personal.setText("Celular:");
        getContentPane().add(lbl_celular_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_P.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 80, -1));

        jTable_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_mostrarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_mostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 690, 190));

        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcorreoKeyTyped(evt);
            }
        });
        getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 140, -1));

        txtcel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcelKeyTyped(evt);
            }
        });
        getContentPane().add(txtcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 140, -1));

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Update.png"))); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 120, -1));

        btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 100, -1));

        lbl_rut_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_rut_usuario.setText("Rut:");
        getContentPane().add(lbl_rut_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 85, -1));

        txt_rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rutKeyTyped(evt);
            }
        });
        getContentPane().add(txt_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 90, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("-");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        lbl_nombre_personal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre_personal.setText("Nombre Personal:");
        getContentPane().add(lbl_nombre_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        txtdvrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdvrutKeyTyped(evt);
            }
        });
        getContentPane().add(txtdvrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 18, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("-");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 7, -1));

        txt_dvrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dvrutKeyTyped(evt);
            }
        });
        getContentPane().add(txt_dvrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 22, -1));

        jl_info_rut_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jl_info_rut_buscar.setText("(?)");
        getContentPane().add(jl_info_rut_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 25, -1));

        jl_info_mostrar.setForeground(new java.awt.Color(255, 255, 255));
        jl_info_mostrar.setText("(?)");
        getContentPane().add(jl_info_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 21, -1));

        lbl_tipo_personal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_personal.setText("Tipo Personal:");
        getContentPane().add(lbl_tipo_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        jctipo_personal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrador", "Jefe Personal", "Guardia", "Garzon/a", "Encargado del bar", "Cocinero" }));
        getContentPane().add(jctipo_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 140, -1));

        lbl_fondo_interfaz_mod_usuario.setBackground(new java.awt.Color(83, 83, 83));
        lbl_fondo_interfaz_mod_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_personal_final.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo_interfaz_mod_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 930, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void lbl_titulo_mod_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_titulo_mod_usuarioMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_lbl_titulo_mod_usuarioMousePressed

    private void lbl_titulo_mod_usuarioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_titulo_mod_usuarioMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_lbl_titulo_mod_usuarioMouseDragged

    private void btn_inicio_mod_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicio_mod_usuarioMousePressed
        // TODO add your handling code here:
       
        Menu_principal mp = new Menu_principal();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicio_mod_usuarioMousePressed

    private void btn_datper_mod_usuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datper_mod_usuarioMouseReleased
        // TODO add your handling code here:
        setColor(btn_datper_mod_usuario);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_inicio_mod_usuario,btn_ingred_mod_usuario,btn_admmes_mod_usuario}, new JPanel[]{ind_1,ind_3, ind_4});
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_datper_mod_usuarioMouseReleased

    private void btn_ingred_mod_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingred_mod_usuarioMousePressed
        // TODO add your handling code here:
        
        interfaz_Ingrediente adm_ingre = new interfaz_Ingrediente();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingred_mod_usuarioMousePressed

    private void btn_admmes_mod_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_admmes_mod_usuarioMousePressed
        // TODO add your handling code here:
        
        Administrar_Mesas adm_mesa = new Administrar_Mesas();
        adm_mesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_admmes_mod_usuarioMousePressed

    private void btn_prove_mod_usuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prove_mod_usuarioMouseReleased
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_prove_mod_usuarioMouseReleased

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?");
        if (JOptionPane.OK_OPTION == exit)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitMousePressed

    private void txtnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if((n<'a' || n>'z') && (n<'A' || n>'Z') && (n<' ' || n>' '))evt.consume();
    }//GEN-LAST:event_txtnomKeyTyped

    private void txtapeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapeKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if((n<'a' || n>'z') && (n<'A' || n>'Z') && (n<' ' || n>' '))evt.consume();
    }//GEN-LAST:event_txtapeKeyTyped

    private void txtrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txtrutKeyTyped

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        try
        {
            DefaultTableModel modelo= new DefaultTableModel();
            modelo.addColumn("Rut");
            modelo.addColumn("Digito verificador");
            modelo.addColumn("Nombre personal");
            modelo.addColumn("Apellido personal");
            modelo.addColumn("Celular");
            modelo.addColumn("Correo");
            modelo.addColumn("Tipo Personal");
            this.jTable_mostrar.setModel(modelo);
            try {
                ResultSet rs = Manejadora.buscarPersonal(this.txtrut.getText());
                String [] datos = new String[7];
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    modelo.addRow(datos);
                    this.jTable_mostrar.setModel(modelo);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se ha ingresado un rut");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void jTable_mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_mostrarMouseClicked
        // TODO add your handling code here:
        try
        {
            int x = jTable_mostrar.getSelectedRow();
            String rut = (String)jTable_mostrar.getValueAt(x, 0);
            String dvrut = (String)jTable_mostrar.getValueAt(x, 1);
            String nombre = (String)jTable_mostrar.getValueAt(x, 2);
            String apellido = (String)jTable_mostrar.getValueAt(x, 3);
            String celular = (String)jTable_mostrar.getValueAt(x, 4);
            String correo = (String)jTable_mostrar.getValueAt(x, 5);
            String tipo_pers = (String)jTable_mostrar.getValueAt(x, 6);

            txt_rut.setText(rut);
            txt_dvrut.setText(dvrut);
            txtnom.setText(nombre);
            txtape.setText(apellido);
            txtcorreo.setText(celular);
            txtcel.setText(correo);
            jctipo_personal.setSelectedItem(tipo_pers);

        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se ha seleccionado ninguna fila");
        }

    }//GEN-LAST:event_jTable_mostrarMouseClicked

    private void txtcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoKeyTyped

    private void txtcelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txtcelKeyTyped

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:

        try
        {
            Personal per = new Personal();
            per.setRut_personal(txt_rut.getText().trim());
            per.setDigito_v(txt_dvrut.getText().trim());
            per.setNombre_p(txtnom.getText().trim());
            per.setApellido_p(txtape.getText().trim());
            per.setCorreo_p(txtcorreo.getText().trim());
            per.setNumero_p(Integer.parseInt(txtcel.getText().trim()));
             if(jctipo_personal.getSelectedIndex() == 0)
            {
                per.setTip_personal("Sin definir");
            }else {
                per.setTip_personal(jctipo_personal.getSelectedItem().toString());
            }
            if (Manejadora.actualizarPersonal(per))
            {
                JOptionPane.showMessageDialog(null, "Se Modifico Exitosamente");
                txt_rut.setText("");
                txt_dvrut.setText("");
                txtnom.setText("");
                txtape.setText("");
                txtcorreo.setText("");
                txtcel.setText("");
                jctipo_personal.setSelectedIndex(0);
                mostarPersonal();

            } else {
                JOptionPane.showMessageDialog(null, "no se pudo modificar el registro");
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ingrese Todos los Campos restantes.");
        }

    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void txt_rutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rutKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txt_rutKeyTyped

    private void txtdvrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdvrutKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' && n !='k' && n !='K' )evt.consume();
    }//GEN-LAST:event_txtdvrutKeyTyped

    private void txt_dvrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dvrutKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' && n !='k' && n !='K' )evt.consume();
    }//GEN-LAST:event_txt_dvrutKeyTyped

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("Rut");
        modelo.addColumn("Digito verificador");
        modelo.addColumn("Nombre personal");
        modelo.addColumn("Apellido personal");
        modelo.addColumn("Correo");
        modelo.addColumn("Celular:");
        modelo.addColumn("Tipo Personal:");
        this.jTable_mostrar.setModel(modelo);

        try {
            ResultSet rs = Manejadora.mostrarPersonal();
            String [] datos = new String[7];
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                modelo.addRow(datos);
                this.jTable_mostrar.setModel(modelo);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_mostrarActionPerformed

    private void btn_modulo_documentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulo_documentoMouseReleased
        Interfaz_Factura adm_ingre = new Interfaz_Factura();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modulo_documentoMouseReleased

    private void btn_recetarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recetarioMouseReleased
        interfaz_Recetario adm_ingre = new interfaz_Recetario();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_recetarioMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Modificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Modificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Modificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Modificar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Modificar_Usuario().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_admmes_mod_usuario;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JPanel btn_datper_mod_usuario;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel btn_ingred_mod_usuario;
    private javax.swing.JPanel btn_inicio_mod_usuario;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JPanel btn_modulo_documento;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JPanel btn_prove_mod_usuario;
    private javax.swing.JPanel btn_recetario;
    private javax.swing.JButton btn_volver;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_12;
    private javax.swing.JPanel ind_13;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_9;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_mostrar;
    private javax.swing.JComboBox<String> jctipo_personal;
    private javax.swing.JLabel jl_info_mostrar;
    private javax.swing.JLabel jl_info_rut_buscar;
    private javax.swing.JLabel lbl_adm_mesa_mod_usuario;
    private javax.swing.JLabel lbl_ape_personal;
    private javax.swing.JLabel lbl_celular_personal;
    private javax.swing.JLabel lbl_correo_personal;
    private javax.swing.JLabel lbl_documentos;
    private javax.swing.JLabel lbl_dtos_perso_mod_usuario;
    private javax.swing.JLabel lbl_fondo_interfaz_mod_usuario;
    private javax.swing.JLabel lbl_icono_usuario;
    private javax.swing.JLabel lbl_ingre_mod_usuario;
    private javax.swing.JLabel lbl_inicio_mod_usuario;
    private javax.swing.JLabel lbl_logoazul_restau;
    private javax.swing.JLabel lbl_nombre_personal;
    private javax.swing.JLabel lbl_prove_adm_perso;
    private javax.swing.JLabel lbl_recetario;
    private javax.swing.JLabel lbl_rut;
    private javax.swing.JLabel lbl_rut_usuario;
    private javax.swing.JLabel lbl_tipo_personal;
    private javax.swing.JLabel lbl_tipo_usuario;
    private javax.swing.JLabel lbl_titulo_adm_perso;
    private javax.swing.JPanel lbl_titulo_mod_usuario;
    private javax.swing.JPanel side_pane;
    private javax.swing.JPanel side_pane1;
    private javax.swing.JPanel side_pane10;
    private javax.swing.JPanel side_pane11;
    private javax.swing.JPanel side_pane12;
    private javax.swing.JPanel side_pane13;
    private javax.swing.JPanel side_pane14;
    private javax.swing.JPanel side_pane15;
    private javax.swing.JPanel side_pane16;
    private javax.swing.JPanel side_pane17;
    private javax.swing.JPanel side_pane2;
    private javax.swing.JPanel side_pane3;
    private javax.swing.JPanel side_pane4;
    private javax.swing.JPanel side_pane5;
    private javax.swing.JPanel side_pane6;
    private javax.swing.JPanel side_pane8;
    private javax.swing.JPanel side_pane9;
    private javax.swing.JTextField txt_dvrut;
    private javax.swing.JTextField txt_rut;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtcel;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdvrut;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables
}
