/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Mesas;

import Vista.Usuario.*;
import Clases.Manejadora;
import Clases.Mesa;
import Clases.Personal;

//import Ventanas.*;
import Ventanas_Administracion.Administrar_Mesas;
import Ventanas_Administracion.Administrar_Proveedor;
import Ventanas_Administracion.Administrar_datos_personal;
import Ventanas_Administracion.Menu_principal;
import Vista.Factura.Interfaz_Factura;
import Vista.Ingrediente.interfaz_Ingrediente;
import Vista.Recetario.interfaz_Recetario;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Admin
 */
public class Agregar_Mesa extends javax.swing.JFrame {

    
             int lastid;      
            Connection con;
            ResultSet rs;
            Statement st;
            PreparedStatement pst;
    
    
    
        
    public Agregar_Mesa() {
        initComponents();
        getlastid();
        this.setLocationRelativeTo(this);
        setColor(btn_inicio_agre_mesa); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_agre_mesa,btn_ingred_adm_mesa,btn_admmes_agre_mesa}, new JPanel[]{ind_2,ind_3, ind_4});
        //jProgressBar1.setValue(50);
        jb_info_nombre.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese el numero de mesa POR EJEMPLO MESA 5.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        jb_info_apellido.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese su primer apellido o los dos apellido.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        btn_agregar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Agrega los datos ingresados.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        btn_volver.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Regresa una ventana atras.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
   }
    
    
    public void getlastid()
    {
         try {
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            String DB="jdbc:oracle:thin:@localhost:1521:orcl";
            String user = "portafolio_tobal";
            String pass = "toballxd";
            String sql = "Select max(ID_MESA) from MESA";
          Connection con = DriverManager.getConnection(DB, user, pass);  
            st = con.createStatement();
            rs = st.executeQuery(sql);
            if(rs.next())
            {
                lastid = rs.getInt(1);
                lastid++;
                txtrut.setText(Integer.toString(lastid));
            }
            
        }catch (SQLException e) {
            
            System.out.println(e.getMessage());
            
        }catch (ClassNotFoundException cs) {
            
            System.out.println(cs.getMessage());
            
        }       
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_id_mesa = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        lbl_num_mesa = new javax.swing.JLabel();
        txt_numero_mesa = new javax.swing.JTextField();
        jb_info_nombre = new javax.swing.JLabel();
        lbl_logoazul_restau = new javax.swing.JLabel();
        lbl_capaci_mesa = new javax.swing.JLabel();
        cbo_estilo_mesa = new javax.swing.JComboBox<>();
        txt_capacidad_mesa = new javax.swing.JTextField();
        txt_fecha_registro_mesa = new javax.swing.JFormattedTextField();
        jb_info_apellido = new javax.swing.JLabel();
        lbl_estilo_mesa = new javax.swing.JLabel();
        lbl_fecha_regist_mesa = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        pnl_barra_lateral_agre_mesa = new javax.swing.JPanel();
        btn_inicio_agre_mesa = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lbl_inicio_agre_mesa = new javax.swing.JLabel();
        pnl_barra_amarilla_agre_mesa = new javax.swing.JPanel();
        btn_prove_agre_mesa = new javax.swing.JPanel();
        ind_11 = new javax.swing.JPanel();
        lbl_proveedores_agre_mesa = new javax.swing.JLabel();
        btn_datper_agre_mesa = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbl_dtos_perso_agre_mesa = new javax.swing.JLabel();
        btn_admmes_agre_mesa = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbl_adm_mesa_agre_mesa = new javax.swing.JLabel();
        btn_ingred_adm_mesa = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbl_ingre_agre_mesa = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        btn_recetario = new javax.swing.JPanel();
        ind_12 = new javax.swing.JPanel();
        lbl_recetario = new javax.swing.JLabel();
        btn_modulo_documento = new javax.swing.JPanel();
        ind_13 = new javax.swing.JPanel();
        lbl_documentos = new javax.swing.JLabel();
        lbl_estado_mesa = new javax.swing.JLabel();
        pnl_barra_superior_agre_mesa = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbo_estado_mesa = new javax.swing.JComboBox<>();
        lbl_logorojo_restau = new javax.swing.JLabel();
        lbl_fondo_interfaz_agre_mesa = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_id_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id_mesa.setText("ID MESA:");
        getContentPane().add(lbl_id_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 50, 10));

        txtrut.setEditable(false);
        txtrut.setEnabled(false);
        txtrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutActionPerformed(evt);
            }
        });
        txtrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutKeyTyped(evt);
            }
        });
        getContentPane().add(txtrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 80, -1));

        lbl_num_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_num_mesa.setText("NUMERO MESA:");
        getContentPane().add(lbl_num_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        txt_numero_mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numero_mesaActionPerformed(evt);
            }
        });
        txt_numero_mesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numero_mesaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_numero_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 190, -1));

        jb_info_nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_info_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jb_info_nombre.setText("(?)");
        getContentPane().add(jb_info_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 21, -1));

        lbl_logoazul_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_superior_blanco.png"))); // NOI18N
        getContentPane().add(lbl_logoazul_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 90));

        lbl_capaci_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_capaci_mesa.setText("CAPACIDAD MESA:");
        getContentPane().add(lbl_capaci_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 111, -1));

        cbo_estilo_mesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Premium", "Familiar", "Ejecutiva", "Personal", "Casual" }));
        cbo_estilo_mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_estilo_mesaActionPerformed(evt);
            }
        });
        getContentPane().add(cbo_estilo_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 190, -1));

        txt_capacidad_mesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_capacidad_mesaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_capacidad_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 190, -1));

        try {
            txt_fecha_registro_mesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fecha_registro_mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha_registro_mesaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fecha_registro_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 190, -1));

        jb_info_apellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_info_apellido.setForeground(new java.awt.Color(255, 255, 255));
        jb_info_apellido.setText("(?)");
        getContentPane().add(jb_info_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        lbl_estilo_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_estilo_mesa.setText("ESTILO MESA:");
        getContentPane().add(lbl_estilo_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        lbl_fecha_regist_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fecha_regist_mesa.setText("FECHA REGISTRO MESA:");
        getContentPane().add(lbl_fecha_regist_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save.png"))); // NOI18N
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 110, -1));

        btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 80, -1));

        pnl_barra_lateral_agre_mesa.setBackground(new java.awt.Color(23, 35, 51));
        pnl_barra_lateral_agre_mesa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio_agre_mesa.setBackground(new java.awt.Color(23, 35, 51));
        btn_inicio_agre_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicio_agre_mesaMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_inicio_agre_mesa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_inicio_agre_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio_agre_mesa.setText("Inicio");

        javax.swing.GroupLayout btn_inicio_agre_mesaLayout = new javax.swing.GroupLayout(btn_inicio_agre_mesa);
        btn_inicio_agre_mesa.setLayout(btn_inicio_agre_mesaLayout);
        btn_inicio_agre_mesaLayout.setHorizontalGroup(
            btn_inicio_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_agre_mesaLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbl_inicio_agre_mesa)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_inicio_agre_mesaLayout.setVerticalGroup(
            btn_inicio_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_agre_mesaLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_inicio_agre_mesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inicio_agre_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_agre_mesa.add(btn_inicio_agre_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        pnl_barra_amarilla_agre_mesa.setBackground(new java.awt.Color(251, 243, 0));
        pnl_barra_amarilla_agre_mesa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnl_barra_lateral_agre_mesa.add(pnl_barra_amarilla_agre_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 10, 500));

        btn_prove_agre_mesa.setBackground(new java.awt.Color(23, 35, 51));
        btn_prove_agre_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_prove_agre_mesaMouseReleased(evt);
            }
        });

        ind_11.setOpaque(false);
        ind_11.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_11Layout = new javax.swing.GroupLayout(ind_11);
        ind_11.setLayout(ind_11Layout);
        ind_11Layout.setHorizontalGroup(
            ind_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_11Layout.setVerticalGroup(
            ind_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_proveedores_agre_mesa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_proveedores_agre_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_proveedores_agre_mesa.setText("Proveedores");

        javax.swing.GroupLayout btn_prove_agre_mesaLayout = new javax.swing.GroupLayout(btn_prove_agre_mesa);
        btn_prove_agre_mesa.setLayout(btn_prove_agre_mesaLayout);
        btn_prove_agre_mesaLayout.setHorizontalGroup(
            btn_prove_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_agre_mesaLayout.createSequentialGroup()
                .addComponent(ind_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_proveedores_agre_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_prove_agre_mesaLayout.setVerticalGroup(
            btn_prove_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_agre_mesaLayout.createSequentialGroup()
                .addComponent(ind_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_prove_agre_mesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_proveedores_agre_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_agre_mesa.add(btn_prove_agre_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, -1));

        btn_datper_agre_mesa.setBackground(new java.awt.Color(23, 35, 51));
        btn_datper_agre_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_datper_agre_mesaMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_dtos_perso_agre_mesa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_dtos_perso_agre_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dtos_perso_agre_mesa.setText("Datos de personal");

        javax.swing.GroupLayout btn_datper_agre_mesaLayout = new javax.swing.GroupLayout(btn_datper_agre_mesa);
        btn_datper_agre_mesa.setLayout(btn_datper_agre_mesaLayout);
        btn_datper_agre_mesaLayout.setHorizontalGroup(
            btn_datper_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_agre_mesaLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_dtos_perso_agre_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );
        btn_datper_agre_mesaLayout.setVerticalGroup(
            btn_datper_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_agre_mesaLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_datper_agre_mesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dtos_perso_agre_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_agre_mesa.add(btn_datper_agre_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, -1));

        btn_admmes_agre_mesa.setBackground(new java.awt.Color(251, 243, 0));
        btn_admmes_agre_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_admmes_agre_mesaMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_adm_mesa_agre_mesa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_adm_mesa_agre_mesa.setText("Administrar Mesas");

        javax.swing.GroupLayout btn_admmes_agre_mesaLayout = new javax.swing.GroupLayout(btn_admmes_agre_mesa);
        btn_admmes_agre_mesa.setLayout(btn_admmes_agre_mesaLayout);
        btn_admmes_agre_mesaLayout.setHorizontalGroup(
            btn_admmes_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_agre_mesaLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_adm_mesa_agre_mesa)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        btn_admmes_agre_mesaLayout.setVerticalGroup(
            btn_admmes_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_agre_mesaLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_admmes_agre_mesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adm_mesa_agre_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_agre_mesa.add(btn_admmes_agre_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 140, -1));

        btn_ingred_adm_mesa.setBackground(new java.awt.Color(23, 35, 51));
        btn_ingred_adm_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingred_adm_mesaMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_ingre_agre_mesa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_ingre_agre_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingre_agre_mesa.setText("Ingredientes");

        javax.swing.GroupLayout btn_ingred_adm_mesaLayout = new javax.swing.GroupLayout(btn_ingred_adm_mesa);
        btn_ingred_adm_mesa.setLayout(btn_ingred_adm_mesaLayout);
        btn_ingred_adm_mesaLayout.setHorizontalGroup(
            btn_ingred_adm_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_adm_mesaLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingre_agre_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        btn_ingred_adm_mesaLayout.setVerticalGroup(
            btn_ingred_adm_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_adm_mesaLayout.createSequentialGroup()
                .addGroup(btn_ingred_adm_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingre_agre_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_barra_lateral_agre_mesa.add(btn_ingred_adm_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        pnl_barra_lateral_agre_mesa.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 30, 46));

        btn_recetario.setBackground(new java.awt.Color(23, 35, 51));
        btn_recetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_recetarioMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_recetarioMouseReleased(evt);
            }
        });

        ind_12.setOpaque(false);
        ind_12.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_12Layout = new javax.swing.GroupLayout(ind_12);
        ind_12.setLayout(ind_12Layout);
        ind_12Layout.setHorizontalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_12Layout.setVerticalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_recetario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_recetario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_recetario.setText("Recetario");
        lbl_recetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_recetarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_recetarioLayout = new javax.swing.GroupLayout(btn_recetario);
        btn_recetario.setLayout(btn_recetarioLayout);
        btn_recetarioLayout.setHorizontalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_recetario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_recetarioLayout.setVerticalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_recetario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_agre_mesa.add(btn_recetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, -1));

        btn_modulo_documento.setBackground(new java.awt.Color(23, 35, 51));
        btn_modulo_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_modulo_documentoMouseReleased(evt);
            }
        });

        ind_13.setOpaque(false);
        ind_13.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_13Layout = new javax.swing.GroupLayout(ind_13);
        ind_13.setLayout(ind_13Layout);
        ind_13Layout.setHorizontalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_13Layout.setVerticalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_documentos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_documentos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_documentos.setText("Documentos");

        javax.swing.GroupLayout btn_modulo_documentoLayout = new javax.swing.GroupLayout(btn_modulo_documento);
        btn_modulo_documento.setLayout(btn_modulo_documentoLayout);
        btn_modulo_documentoLayout.setHorizontalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btn_modulo_documentoLayout.setVerticalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_documentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_agre_mesa.add(btn_modulo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 140, -1));

        getContentPane().add(pnl_barra_lateral_agre_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 590));

        lbl_estado_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_estado_mesa.setText("ESTADO DE MESA:");
        getContentPane().add(lbl_estado_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        pnl_barra_superior_agre_mesa.setBackground(new java.awt.Color(23, 35, 51));
        pnl_barra_superior_agre_mesa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barra_superior_agre_mesaMouseDragged(evt);
            }
        });
        pnl_barra_superior_agre_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barra_superior_agre_mesaMousePressed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(123, 156, 225));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuario: Administrador");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_48px.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("AGREGAR MESAS");

        javax.swing.GroupLayout pnl_barra_superior_agre_mesaLayout = new javax.swing.GroupLayout(pnl_barra_superior_agre_mesa);
        pnl_barra_superior_agre_mesa.setLayout(pnl_barra_superior_agre_mesaLayout);
        pnl_barra_superior_agre_mesaLayout.setHorizontalGroup(
            pnl_barra_superior_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barra_superior_agre_mesaLayout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addGroup(pnl_barra_superior_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_agre_mesaLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_agre_mesaLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(159, 159, 159)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        pnl_barra_superior_agre_mesaLayout.setVerticalGroup(
            pnl_barra_superior_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_agre_mesaLayout.createSequentialGroup()
                .addGroup(pnl_barra_superior_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_barra_superior_agre_mesaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pnl_barra_superior_agre_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_barra_superior_agre_mesaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_barra_superior_agre_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 90));

        cbo_estado_mesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "EN BODEGA", "EN LOCAL" }));
        cbo_estado_mesa.setDoubleBuffered(true);
        getContentPane().add(cbo_estado_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 190, -1));

        lbl_logorojo_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_final.png"))); // NOI18N
        lbl_logorojo_restau.setText("jLabel17");
        getContentPane().add(lbl_logorojo_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 260, 320));

        lbl_fondo_interfaz_agre_mesa.setBackground(new java.awt.Color(83, 83, 83));
        lbl_fondo_interfaz_agre_mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_personal_final.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo_interfaz_agre_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 920, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void pnl_barra_superior_agre_mesaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_superior_agre_mesaMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnl_barra_superior_agre_mesaMousePressed

    private void pnl_barra_superior_agre_mesaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_superior_agre_mesaMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_pnl_barra_superior_agre_mesaMouseDragged

    private void btn_inicio_agre_mesaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicio_agre_mesaMousePressed
        // TODO add your handling code here:
        setColor(btn_inicio_agre_mesa);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_agre_mesa,btn_ingred_adm_mesa,btn_admmes_agre_mesa}, new JPanel[]{ind_2,ind_3, ind_4});
        Menu_principal mp = new Menu_principal();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicio_agre_mesaMousePressed

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?");
        if (JOptionPane.OK_OPTION == exit)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitMousePressed

    private void txtrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtrutActionPerformed

    private void txtrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyTyped
        // TODO add your handling code here:
        txtrut.setEditable(false);
       txtrut.setEnabled(false);
    
    }//GEN-LAST:event_txtrutKeyTyped

    private void txt_numero_mesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numero_mesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numero_mesaActionPerformed

    private void txt_numero_mesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numero_mesaKeyTyped
        // TODO add your handling code here:
      /*  char n = evt.getKeyChar();
        if((n<'a' || n>'z') && (n<'A' || n>'Z') && (n<' ' || n>' '))evt.consume();*/  
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txt_numero_mesaKeyTyped

    private void txt_capacidad_mesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_capacidad_mesaKeyTyped
        // TODO add your handling code here:
       /* char n = evt.getKeyChar();
        if((n<'a' || n>'z') && (n<'A' || n>'Z') && (n<' ' || n>' '))evt.consume();*/
         char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txt_capacidad_mesaKeyTyped

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        try
        {
            Mesa per = new Mesa();
            per.setId_mesa(txtrut.getText().trim());
            per.setNumero_mesa(Integer.parseInt(txt_numero_mesa.getText().trim()));
            per.setCapacidad_mesa(Integer.parseInt(txt_capacidad_mesa.getText().trim()));
            
              if(cbo_estilo_mesa.getSelectedIndex() == 0)
            {
                per.setEn_uso("Sin definir");
            }else {
                per.setEstilo_mesa(cbo_estilo_mesa.getSelectedItem().toString());
            }
            per.setFecha_registro(txt_fecha_registro_mesa.getText().trim());
            if(cbo_estado_mesa.getSelectedIndex() == 0)
            {
                per.setEn_uso("Sin definir");
            }else {
                per.setEn_uso(cbo_estado_mesa.getSelectedItem().toString());
            }

            if (Manejadora.agregarMesa(per))
            {
                JOptionPane.showMessageDialog(null, "Se ha creado un registro exitosamente");
                getlastid();
                this.txt_numero_mesa.setText(null);
                this.txt_capacidad_mesa.setText(null);
                this.cbo_estilo_mesa.setSelectedIndex(0);
                this.txt_fecha_registro_mesa.setText(null);
                this.cbo_estado_mesa.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "no se pudo crear el registro","ERROR",0);
            }

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se han ingresado datos", "Informacion", 1);
        }

    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        Administrar_Mesas dp = new Administrar_Mesas();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void cbo_estilo_mesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_estilo_mesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_estilo_mesaActionPerformed

    private void btn_prove_agre_mesaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prove_agre_mesaMouseReleased
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_prove_agre_mesaMouseReleased

    private void btn_datper_agre_mesaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datper_agre_mesaMouseReleased
        // TODO add your handling code here:
        setColor(btn_datper_agre_mesa);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_inicio_agre_mesa,btn_ingred_adm_mesa,btn_admmes_agre_mesa}, new JPanel[]{ind_1,ind_3, ind_4});
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_datper_agre_mesaMouseReleased

    private void btn_admmes_agre_mesaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_admmes_agre_mesaMousePressed
        // TODO add your handling code here:
        setColor(btn_admmes_agre_mesa);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_agre_mesa,btn_ingred_adm_mesa,btn_inicio_agre_mesa}, new JPanel[]{ind_2,ind_3, ind_1});
        Administrar_Mesas adm_mesa = new Administrar_Mesas();
        adm_mesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_admmes_agre_mesaMousePressed

    private void btn_ingred_adm_mesaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingred_adm_mesaMousePressed
        // TODO add your handling code here:
        setColor(btn_ingred_adm_mesa);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_agre_mesa,btn_inicio_agre_mesa,btn_admmes_agre_mesa}, new JPanel[]{ind_2,ind_1, ind_4});
        interfaz_Ingrediente adm_ingre = new interfaz_Ingrediente();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingred_adm_mesaMousePressed

    private void txt_fecha_registro_mesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha_registro_mesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha_registro_mesaActionPerformed

    private void btn_recetarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recetarioMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_recetarioMouseReleased

    private void btn_modulo_documentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulo_documentoMouseReleased
        Interfaz_Factura adm_ingre = new Interfaz_Factura();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modulo_documentoMouseReleased

    private void btn_recetarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recetarioMouseClicked
         interfaz_Recetario recetario = new interfaz_Recetario();
        recetario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_recetarioMouseClicked

    private void lbl_recetarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_recetarioMouseClicked
          interfaz_Recetario adm_ingre_2 = new interfaz_Recetario();
        adm_ingre_2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_recetarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Mesa().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_admmes_agre_mesa;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JPanel btn_datper_agre_mesa;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel btn_ingred_adm_mesa;
    private javax.swing.JPanel btn_inicio_agre_mesa;
    private javax.swing.JPanel btn_modulo_documento;
    private javax.swing.JPanel btn_prove_agre_mesa;
    private javax.swing.JPanel btn_recetario;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cbo_estado_mesa;
    private javax.swing.JComboBox<String> cbo_estilo_mesa;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_11;
    private javax.swing.JPanel ind_12;
    private javax.swing.JPanel ind_13;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jb_info_apellido;
    private javax.swing.JLabel jb_info_nombre;
    private javax.swing.JLabel lbl_adm_mesa_agre_mesa;
    private javax.swing.JLabel lbl_capaci_mesa;
    private javax.swing.JLabel lbl_documentos;
    private javax.swing.JLabel lbl_dtos_perso_agre_mesa;
    private javax.swing.JLabel lbl_estado_mesa;
    private javax.swing.JLabel lbl_estilo_mesa;
    private javax.swing.JLabel lbl_fecha_regist_mesa;
    private javax.swing.JLabel lbl_fondo_interfaz_agre_mesa;
    private javax.swing.JLabel lbl_id_mesa;
    private javax.swing.JLabel lbl_ingre_agre_mesa;
    private javax.swing.JLabel lbl_inicio_agre_mesa;
    private javax.swing.JLabel lbl_logoazul_restau;
    private javax.swing.JLabel lbl_logorojo_restau;
    private javax.swing.JLabel lbl_num_mesa;
    private javax.swing.JLabel lbl_proveedores_agre_mesa;
    private javax.swing.JLabel lbl_recetario;
    private javax.swing.JPanel pnl_barra_amarilla_agre_mesa;
    private javax.swing.JPanel pnl_barra_lateral_agre_mesa;
    private javax.swing.JPanel pnl_barra_superior_agre_mesa;
    private javax.swing.JTextField txt_capacidad_mesa;
    private javax.swing.JFormattedTextField txt_fecha_registro_mesa;
    private javax.swing.JTextField txt_numero_mesa;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables
}
