/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Mesas;

//import Ventanas.*;
import java.awt.Color;
import javax.swing.JPanel;
import Clases.Manejadora;
import Clases.Mesa;
import Clases.Personal;
import Ventanas_Administracion.Administrar_Mesas;
import Ventanas_Administracion.Administrar_Proveedor;
import Ventanas_Administracion.Administrar_datos_personal;
import Ventanas_Administracion.Menu_principal;
import Vista.Factura.Interfaz_Factura;
import Vista.Ingrediente.interfaz_Ingrediente;
import Vista.Recetario.interfaz_Recetario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Modificar_Mesa extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Modificar_Mesa() {
        initComponents();
        this.setLocationRelativeTo(this);
        setColor(btn_inicio_mod_mesa); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_mod_mesa,btn_ingred_med_mesa,btn_admmes_mod_mesa}, new JPanel[]{ind_2,ind_3, ind_4});
        //jProgressBar1.setValue(50);
        jl_info_rut_buscar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese su rut y digito verificador.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
                btn_buscar_mod_mesa.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Busca un personal mediante su rut y digito verificador.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
                btn_volver_mod_mesa.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Regresa una ventana atras.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        btn_modificar_mod_mesa.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Actualiza los datos del personal seleccionado.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_mostrar = new javax.swing.JButton();
        side_pane12 = new javax.swing.JPanel();
        side_pane13 = new javax.swing.JPanel();
        side_pane14 = new javax.swing.JPanel();
        side_pane15 = new javax.swing.JPanel();
        side_pane16 = new javax.swing.JPanel();
        side_pane17 = new javax.swing.JPanel();
        side_pane11 = new javax.swing.JPanel();
        side_pane1 = new javax.swing.JPanel();
        side_pane10 = new javax.swing.JPanel();
        side_pane6 = new javax.swing.JPanel();
        side_pane2 = new javax.swing.JPanel();
        side_pane5 = new javax.swing.JPanel();
        side_pane8 = new javax.swing.JPanel();
        side_pane9 = new javax.swing.JPanel();
        side_pane3 = new javax.swing.JPanel();
        side_pane4 = new javax.swing.JPanel();
        lbl_logoazul_restau = new javax.swing.JLabel();
        side_pane = new javax.swing.JPanel();
        btn_inicio_mod_mesa = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lbl_inicio_med_mesa = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        btn_prove_mod_mesa = new javax.swing.JPanel();
        ind_11 = new javax.swing.JPanel();
        lbl_proveedores_mod_mesa = new javax.swing.JLabel();
        btn_datper_mod_mesa = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbl_dtos_perso_mod_mesa = new javax.swing.JLabel();
        btn_admmes_mod_mesa = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbl_adm_mesa_mod_mesa = new javax.swing.JLabel();
        btn_ingred_med_mesa = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbl_ingre_mod_mesa = new javax.swing.JLabel();
        btn_recetario = new javax.swing.JPanel();
        ind_12 = new javax.swing.JPanel();
        lbl_recetario = new javax.swing.JLabel();
        btn_modulo_documento = new javax.swing.JPanel();
        ind_13 = new javax.swing.JPanel();
        lbl_documentos = new javax.swing.JLabel();
        pnl_barra_superior_mod_mesa = new javax.swing.JPanel();
        lbl_tipo_usuario = new javax.swing.JLabel();
        lbl_icono_usuario = new javax.swing.JLabel();
        lbl_titulo_mod_mesa = new javax.swing.JLabel();
        txt_numero_mesa = new javax.swing.JTextField();
        lbl_capacidad_mod_mesa = new javax.swing.JLabel();
        lbl_numero_mesa = new javax.swing.JLabel();
        txt_capacidad_mod_mesa = new javax.swing.JTextField();
        txt_fecha_registro_mod_mesa = new javax.swing.JFormattedTextField();
        txt_numero_mesa_mod_mesa = new javax.swing.JTextField();
        lbl_estilo_mesa_mod_mesa = new javax.swing.JLabel();
        lbl_fecha_registro_mod_mesa = new javax.swing.JLabel();
        btn_buscar_mod_mesa = new javax.swing.JButton();
        cbo_estilo_mesa_mod_mesa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_mostrar = new javax.swing.JTable();
        btn_modificar_mod_mesa = new javax.swing.JButton();
        btn_volver_mod_mesa = new javax.swing.JButton();
        lbl_id_mesa_mod_mesa = new javax.swing.JLabel();
        txt_id_mesa_mod_mesa = new javax.swing.JTextField();
        lbl_numero_mesa_mod_mesa = new javax.swing.JLabel();
        jl_info_rut_buscar = new javax.swing.JLabel();
        jl_info_mostrar = new javax.swing.JLabel();
        lbl_estado_mesa_mod_mesa = new javax.swing.JLabel();
        cbo_estado_mesa_mod_mesa = new javax.swing.JComboBox<>();
        lbl_fondo_interfaz_mod_mesa = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Read.png"))); // NOI18N
        jButton_mostrar.setText("Mostrar");
        jButton_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 110, -1));

        side_pane12.setBackground(new java.awt.Color(251, 243, 0));
        side_pane12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane13.setBackground(new java.awt.Color(251, 243, 0));
        side_pane13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane12.add(side_pane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        getContentPane().add(side_pane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 10, 80));

        side_pane14.setBackground(new java.awt.Color(251, 243, 0));
        side_pane14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane15.setBackground(new java.awt.Color(251, 243, 0));
        side_pane15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane14.add(side_pane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane16.setBackground(new java.awt.Color(251, 243, 0));
        side_pane16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane17.setBackground(new java.awt.Color(251, 243, 0));
        side_pane17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane16.add(side_pane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane14.add(side_pane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 690, 10));

        getContentPane().add(side_pane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 460, 10));

        side_pane11.setBackground(new java.awt.Color(251, 243, 0));
        side_pane11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 10, 80));

        side_pane1.setBackground(new java.awt.Color(251, 243, 0));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 10, 500));

        side_pane10.setBackground(new java.awt.Color(251, 243, 0));
        side_pane10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 480, 10));

        side_pane6.setBackground(new java.awt.Color(251, 243, 0));
        side_pane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 10, 210));

        side_pane2.setBackground(new java.awt.Color(251, 243, 0));
        side_pane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane5.setBackground(new java.awt.Color(251, 243, 0));
        side_pane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane2.add(side_pane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane8.setBackground(new java.awt.Color(251, 243, 0));
        side_pane8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane9.setBackground(new java.awt.Color(251, 243, 0));
        side_pane9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane8.add(side_pane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane2.add(side_pane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 690, 10));

        getContentPane().add(side_pane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 690, 10));

        side_pane3.setBackground(new java.awt.Color(251, 243, 0));
        side_pane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 710, 10));

        side_pane4.setBackground(new java.awt.Color(251, 243, 0));
        side_pane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 10, 210));

        lbl_logoazul_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_superior_blanco.png"))); // NOI18N
        lbl_logoazul_restau.setText("jLabel17");
        getContentPane().add(lbl_logoazul_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 100));

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio_mod_mesa.setBackground(new java.awt.Color(23, 35, 51));
        btn_inicio_mod_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicio_mod_mesaMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_inicio_med_mesa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_inicio_med_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio_med_mesa.setText("Inicio");

        javax.swing.GroupLayout btn_inicio_mod_mesaLayout = new javax.swing.GroupLayout(btn_inicio_mod_mesa);
        btn_inicio_mod_mesa.setLayout(btn_inicio_mod_mesaLayout);
        btn_inicio_mod_mesaLayout.setHorizontalGroup(
            btn_inicio_mod_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_mod_mesaLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbl_inicio_med_mesa)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_inicio_mod_mesaLayout.setVerticalGroup(
            btn_inicio_mod_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_mod_mesaLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_inicio_mod_mesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inicio_med_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_inicio_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        side_pane.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 30, 46));

        btn_prove_mod_mesa.setBackground(new java.awt.Color(23, 35, 51));
        btn_prove_mod_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_prove_mod_mesaMouseReleased(evt);
            }
        });

        ind_11.setOpaque(false);
        ind_11.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_11Layout = new javax.swing.GroupLayout(ind_11);
        ind_11.setLayout(ind_11Layout);
        ind_11Layout.setHorizontalGroup(
            ind_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_11Layout.setVerticalGroup(
            ind_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_proveedores_mod_mesa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_proveedores_mod_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_proveedores_mod_mesa.setText("Proveedores");

        javax.swing.GroupLayout btn_prove_mod_mesaLayout = new javax.swing.GroupLayout(btn_prove_mod_mesa);
        btn_prove_mod_mesa.setLayout(btn_prove_mod_mesaLayout);
        btn_prove_mod_mesaLayout.setHorizontalGroup(
            btn_prove_mod_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_mod_mesaLayout.createSequentialGroup()
                .addComponent(ind_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_proveedores_mod_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_prove_mod_mesaLayout.setVerticalGroup(
            btn_prove_mod_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prove_mod_mesaLayout.createSequentialGroup()
                .addComponent(ind_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_prove_mod_mesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_proveedores_mod_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_prove_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, -1));

        btn_datper_mod_mesa.setBackground(new java.awt.Color(23, 35, 51));
        btn_datper_mod_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_datper_mod_mesaMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_dtos_perso_mod_mesa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_dtos_perso_mod_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dtos_perso_mod_mesa.setText("Datos de personal");

        javax.swing.GroupLayout btn_datper_mod_mesaLayout = new javax.swing.GroupLayout(btn_datper_mod_mesa);
        btn_datper_mod_mesa.setLayout(btn_datper_mod_mesaLayout);
        btn_datper_mod_mesaLayout.setHorizontalGroup(
            btn_datper_mod_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_mod_mesaLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_dtos_perso_mod_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );
        btn_datper_mod_mesaLayout.setVerticalGroup(
            btn_datper_mod_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datper_mod_mesaLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_datper_mod_mesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dtos_perso_mod_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_datper_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, -1));

        btn_admmes_mod_mesa.setBackground(new java.awt.Color(251, 243, 0));
        btn_admmes_mod_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_admmes_mod_mesaMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_adm_mesa_mod_mesa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_adm_mesa_mod_mesa.setText("Administrar Mesas");

        javax.swing.GroupLayout btn_admmes_mod_mesaLayout = new javax.swing.GroupLayout(btn_admmes_mod_mesa);
        btn_admmes_mod_mesa.setLayout(btn_admmes_mod_mesaLayout);
        btn_admmes_mod_mesaLayout.setHorizontalGroup(
            btn_admmes_mod_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_mod_mesaLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_adm_mesa_mod_mesa)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btn_admmes_mod_mesaLayout.setVerticalGroup(
            btn_admmes_mod_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admmes_mod_mesaLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_admmes_mod_mesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adm_mesa_mod_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_admmes_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, -1));

        btn_ingred_med_mesa.setBackground(new java.awt.Color(23, 35, 51));
        btn_ingred_med_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingred_med_mesaMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_ingre_mod_mesa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_ingre_mod_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingre_mod_mesa.setText("Ingredientes");

        javax.swing.GroupLayout btn_ingred_med_mesaLayout = new javax.swing.GroupLayout(btn_ingred_med_mesa);
        btn_ingred_med_mesa.setLayout(btn_ingred_med_mesaLayout);
        btn_ingred_med_mesaLayout.setHorizontalGroup(
            btn_ingred_med_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_med_mesaLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingre_mod_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        btn_ingred_med_mesaLayout.setVerticalGroup(
            btn_ingred_med_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_med_mesaLayout.createSequentialGroup()
                .addGroup(btn_ingred_med_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingre_mod_mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_pane.add(btn_ingred_med_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));

        btn_recetario.setBackground(new java.awt.Color(23, 35, 51));
        btn_recetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_recetarioMouseReleased(evt);
            }
        });

        ind_12.setOpaque(false);
        ind_12.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_12Layout = new javax.swing.GroupLayout(ind_12);
        ind_12.setLayout(ind_12Layout);
        ind_12Layout.setHorizontalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_12Layout.setVerticalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_recetario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_recetario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_recetario.setText("Recetario");

        javax.swing.GroupLayout btn_recetarioLayout = new javax.swing.GroupLayout(btn_recetario);
        btn_recetario.setLayout(btn_recetarioLayout);
        btn_recetarioLayout.setHorizontalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_recetario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_recetarioLayout.setVerticalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_recetario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_recetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, -1));

        btn_modulo_documento.setBackground(new java.awt.Color(23, 35, 51));
        btn_modulo_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_modulo_documentoMouseReleased(evt);
            }
        });

        ind_13.setOpaque(false);
        ind_13.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_13Layout = new javax.swing.GroupLayout(ind_13);
        ind_13.setLayout(ind_13Layout);
        ind_13Layout.setHorizontalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_13Layout.setVerticalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_documentos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_documentos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_documentos.setText("Documentos");

        javax.swing.GroupLayout btn_modulo_documentoLayout = new javax.swing.GroupLayout(btn_modulo_documento);
        btn_modulo_documento.setLayout(btn_modulo_documentoLayout);
        btn_modulo_documentoLayout.setHorizontalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btn_modulo_documentoLayout.setVerticalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_documentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_modulo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 140, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 590));

        pnl_barra_superior_mod_mesa.setBackground(new java.awt.Color(23, 35, 51));
        pnl_barra_superior_mod_mesa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barra_superior_mod_mesaMouseDragged(evt);
            }
        });
        pnl_barra_superior_mod_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barra_superior_mod_mesaMousePressed(evt);
            }
        });

        lbl_tipo_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_tipo_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_usuario.setText("Usuario: Administrador");

        lbl_icono_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_48px.png"))); // NOI18N

        lbl_titulo_mod_mesa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo_mod_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo_mod_mesa.setText("Modificar Mesas");

        javax.swing.GroupLayout pnl_barra_superior_mod_mesaLayout = new javax.swing.GroupLayout(pnl_barra_superior_mod_mesa);
        pnl_barra_superior_mod_mesa.setLayout(pnl_barra_superior_mod_mesaLayout);
        pnl_barra_superior_mod_mesaLayout.setHorizontalGroup(
            pnl_barra_superior_mod_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barra_superior_mod_mesaLayout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(lbl_titulo_mod_mesa)
                .addGap(216, 216, 216)
                .addComponent(lbl_icono_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_barra_superior_mod_mesaLayout.setVerticalGroup(
            pnl_barra_superior_mod_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_mod_mesaLayout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(pnl_barra_superior_mod_mesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_icono_usuario)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_mod_mesaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_titulo_mod_mesa)
                .addGap(29, 29, 29))
        );

        getContentPane().add(pnl_barra_superior_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 90));

        txt_numero_mesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numero_mesaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_numero_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 155, -1));

        lbl_capacidad_mod_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_capacidad_mod_mesa.setText("CAPACIDAD:");
        getContentPane().add(lbl_capacidad_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        lbl_numero_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_numero_mesa.setText("Numero mesa:");
        getContentPane().add(lbl_numero_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, 20));

        txt_capacidad_mod_mesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_capacidad_mod_mesaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_capacidad_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 155, -1));

        try {
            txt_fecha_registro_mod_mesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txt_fecha_registro_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 140, -1));

        txt_numero_mesa_mod_mesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numero_mesa_mod_mesaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_numero_mesa_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 125, -1));

        lbl_estilo_mesa_mod_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_estilo_mesa_mod_mesa.setText("ESTILO MESA:");
        getContentPane().add(lbl_estilo_mesa_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        lbl_fecha_registro_mod_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fecha_registro_mod_mesa.setText("FECHA REGISTRO:");
        getContentPane().add(lbl_fecha_registro_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        btn_buscar_mod_mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_P.png"))); // NOI18N
        btn_buscar_mod_mesa.setText("Buscar");
        btn_buscar_mod_mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_mod_mesaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 120, 30));

        cbo_estilo_mesa_mod_mesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Premium", "Familiar", "Ejecutiva", "Personal", "Casual" }));
        getContentPane().add(cbo_estilo_mesa_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 140, -1));

        jTable_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_mostrarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_mostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 690, 190));

        btn_modificar_mod_mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Update.png"))); // NOI18N
        btn_modificar_mod_mesa.setText("Modificar");
        btn_modificar_mod_mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar_mod_mesaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 120, -1));

        btn_volver_mod_mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        btn_volver_mod_mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volver_mod_mesaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 100, -1));

        lbl_id_mesa_mod_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id_mesa_mod_mesa.setText("ID MESA:");
        getContentPane().add(lbl_id_mesa_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 85, -1));

        txt_id_mesa_mod_mesa.setEditable(false);
        txt_id_mesa_mod_mesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_id_mesa_mod_mesaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_id_mesa_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 60, -1));

        lbl_numero_mesa_mod_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_numero_mesa_mod_mesa.setText("NUMERO MESA:");
        getContentPane().add(lbl_numero_mesa_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jl_info_rut_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jl_info_rut_buscar.setText("(?)");
        getContentPane().add(jl_info_rut_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 25, -1));

        jl_info_mostrar.setForeground(new java.awt.Color(255, 255, 255));
        jl_info_mostrar.setText("(?)");
        getContentPane().add(jl_info_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 21, -1));

        lbl_estado_mesa_mod_mesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_estado_mesa_mod_mesa.setText("ESTADO MESA");
        getContentPane().add(lbl_estado_mesa_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        cbo_estado_mesa_mod_mesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "EN BODEGA", "EN LOCAL" }));
        getContentPane().add(cbo_estado_mesa_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 140, -1));

        lbl_fondo_interfaz_mod_mesa.setBackground(new java.awt.Color(83, 83, 83));
        lbl_fondo_interfaz_mod_mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_personal_final.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo_interfaz_mod_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 930, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void pnl_barra_superior_mod_mesaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_superior_mod_mesaMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnl_barra_superior_mod_mesaMousePressed

    private void pnl_barra_superior_mod_mesaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_superior_mod_mesaMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_pnl_barra_superior_mod_mesaMouseDragged

    private void btn_inicio_mod_mesaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicio_mod_mesaMousePressed
        // TODO add your handling code here:
       
        Menu_principal evento = new Menu_principal();
        evento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicio_mod_mesaMousePressed

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?");
        if (JOptionPane.OK_OPTION == exit)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitMousePressed

    private void txt_numero_mesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numero_mesaKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_numero_mesaKeyTyped

    private void txt_capacidad_mod_mesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_capacidad_mod_mesaKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txt_capacidad_mod_mesaKeyTyped

    private void txt_numero_mesa_mod_mesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numero_mesa_mod_mesaKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txt_numero_mesa_mod_mesaKeyTyped

    private void btn_buscar_mod_mesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_mod_mesaActionPerformed
        // TODO add your handling code here:
        try
        {
            DefaultTableModel modelo= new DefaultTableModel();
                 modelo.addColumn("ID_MESA");
                modelo.addColumn("Numero Mesa");
                modelo.addColumn("Capacidad Mesa");
                modelo.addColumn("Estilo Mesa");
                modelo.addColumn("Fecha Registro");
                modelo.addColumn("Estado de mesa");
            this.jTable_mostrar.setModel(modelo);
            try {
                ResultSet rs = Manejadora.buscarMesa(this.txt_numero_mesa_mod_mesa.getText());
                String [] datos = new String[6];
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    modelo.addRow(datos);
                    this.jTable_mostrar.setModel(modelo);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se ha ingresado rut");
        }
    }//GEN-LAST:event_btn_buscar_mod_mesaActionPerformed

    private void jTable_mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_mostrarMouseClicked
        // TODO add your handling code here:
        try
        {
            int x = jTable_mostrar.getSelectedRow();
            String rut = (String)jTable_mostrar.getValueAt(x, 0);
            String nombre = (String)jTable_mostrar.getValueAt(x, 1);
            String apellido = (String)jTable_mostrar.getValueAt(x, 2);
            String celular = (String)jTable_mostrar.getValueAt(x, 3);
            String correo = (String)jTable_mostrar.getValueAt(x, 4);
            String tipo_pers = (String)jTable_mostrar.getValueAt(x, 5);

            txt_id_mesa_mod_mesa.setText(rut);
            txt_numero_mesa.setText(nombre);
            txt_capacidad_mod_mesa.setText(apellido);
            cbo_estilo_mesa_mod_mesa.setSelectedItem(celular);
            txt_fecha_registro_mod_mesa.setText(correo);
            cbo_estado_mesa_mod_mesa.setSelectedItem(tipo_pers);
            

        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se ha seleccionado ninguna fila");
        }

    }//GEN-LAST:event_jTable_mostrarMouseClicked

    private void btn_modificar_mod_mesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar_mod_mesaActionPerformed

        try
        {
            Mesa per = new Mesa();
            per.setId_mesa(txt_id_mesa_mod_mesa.getText().trim());
            per.setNumero_mesa(Integer.parseInt(txt_numero_mesa.getText().trim()));
            per.setCapacidad_mesa(Integer.parseInt(txt_capacidad_mod_mesa.getText().trim()));
            
              if(cbo_estilo_mesa_mod_mesa.getSelectedIndex() == 0)
            {
                per.setEstilo_mesa("Sin definir");
            }else {
                per.setEstilo_mesa(cbo_estilo_mesa_mod_mesa.getSelectedItem().toString());
            }
              
               if(  cbo_estado_mesa_mod_mesa.getSelectedIndex() == 0)
            {
                per.setEn_uso("Sin definir");
            }else {
                per.setEn_uso(cbo_estado_mesa_mod_mesa.getSelectedItem().toString());
            }  
               
               
               
            per.setFecha_registro(txt_fecha_registro_mod_mesa.getText().trim());
           
            if (Manejadora.actualizarMesa(per))
            {
                JOptionPane.showMessageDialog(null, "Se Modifico Exitosamente");
               // txtrut.setText("");
                txt_numero_mesa.setText("");
                txt_capacidad_mod_mesa.setText("");
                txt_fecha_registro_mod_mesa.setText("");
         //       jctipo_personal.setSelectedIndex(0);
                cbo_estilo_mesa_mod_mesa.setSelectedIndex(0);

            } else {
                JOptionPane.showMessageDialog(null, "no se pudo modificar el registro");
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ingrese Todos los Campos restantes.");
        }

    }//GEN-LAST:event_btn_modificar_mod_mesaActionPerformed

    private void btn_volver_mod_mesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volver_mod_mesaActionPerformed
        // TODO add your handling code here:
        Administrar_Mesas adm_mesa = new Administrar_Mesas();
        adm_mesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_volver_mod_mesaActionPerformed

    private void txt_id_mesa_mod_mesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_mesa_mod_mesaKeyTyped
        // TODO add your handling code here:
       txt_id_mesa_mod_mesa.setEditable(false);
       txt_id_mesa_mod_mesa.setEnabled(false);
    }//GEN-LAST:event_txt_id_mesa_mod_mesaKeyTyped

    private void jButton_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mostrarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("ID MESA");
        modelo.addColumn("NUMERO MESA");
        modelo.addColumn("CAPACIDAD MESA ");
        modelo.addColumn("ESTILO ");
        modelo.addColumn("FECHA REGISTRO");
        modelo.addColumn("EN USO :");
        this.jTable_mostrar.setModel(modelo);

        try {
            ResultSet rs = Manejadora.mostrarMesa();
            String [] datos = new String[7];
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                modelo.addRow(datos);
                this.jTable_mostrar.setModel(modelo);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_mostrarActionPerformed

    private void btn_prove_mod_mesaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prove_mod_mesaMouseReleased
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_prove_mod_mesaMouseReleased

    private void btn_datper_mod_mesaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datper_mod_mesaMouseReleased
        // TODO add your handling code here:
        setColor(btn_datper_mod_mesa);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_inicio_mod_mesa,btn_ingred_med_mesa,btn_admmes_mod_mesa}, new JPanel[]{ind_1,ind_3, ind_4});
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_datper_mod_mesaMouseReleased

    private void btn_admmes_mod_mesaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_admmes_mod_mesaMousePressed
        // TODO add your handling code here:
        setColor(btn_admmes_mod_mesa);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_mod_mesa,btn_ingred_med_mesa,btn_inicio_mod_mesa}, new JPanel[]{ind_2,ind_3, ind_1});
        Administrar_Mesas adm_mesa = new Administrar_Mesas();
        adm_mesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_admmes_mod_mesaMousePressed

    private void btn_ingred_med_mesaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingred_med_mesaMousePressed
        // TODO add your handling code here:
        setColor(btn_ingred_med_mesa);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_datper_mod_mesa,btn_inicio_mod_mesa,btn_admmes_mod_mesa}, new JPanel[]{ind_2,ind_1, ind_4});
       interfaz_Ingrediente evento = new interfaz_Ingrediente();
        evento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingred_med_mesaMousePressed

    private void btn_recetarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recetarioMouseReleased
        interfaz_Recetario adm_ingre = new interfaz_Recetario();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_recetarioMouseReleased

    private void btn_modulo_documentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulo_documentoMouseReleased
        Interfaz_Factura adm_ingre = new Interfaz_Factura();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modulo_documentoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_Mesa().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_admmes_mod_mesa;
    private javax.swing.JButton btn_buscar_mod_mesa;
    private javax.swing.JPanel btn_datper_mod_mesa;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel btn_ingred_med_mesa;
    private javax.swing.JPanel btn_inicio_mod_mesa;
    private javax.swing.JButton btn_modificar_mod_mesa;
    private javax.swing.JPanel btn_modulo_documento;
    private javax.swing.JPanel btn_prove_mod_mesa;
    private javax.swing.JPanel btn_recetario;
    private javax.swing.JButton btn_volver_mod_mesa;
    private javax.swing.JComboBox<String> cbo_estado_mesa_mod_mesa;
    private javax.swing.JComboBox<String> cbo_estilo_mesa_mod_mesa;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_11;
    private javax.swing.JPanel ind_12;
    private javax.swing.JPanel ind_13;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JButton jButton_mostrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_mostrar;
    private javax.swing.JLabel jl_info_mostrar;
    private javax.swing.JLabel jl_info_rut_buscar;
    private javax.swing.JLabel lbl_adm_mesa_mod_mesa;
    private javax.swing.JLabel lbl_capacidad_mod_mesa;
    private javax.swing.JLabel lbl_documentos;
    private javax.swing.JLabel lbl_dtos_perso_mod_mesa;
    private javax.swing.JLabel lbl_estado_mesa_mod_mesa;
    private javax.swing.JLabel lbl_estilo_mesa_mod_mesa;
    private javax.swing.JLabel lbl_fecha_registro_mod_mesa;
    private javax.swing.JLabel lbl_fondo_interfaz_mod_mesa;
    private javax.swing.JLabel lbl_icono_usuario;
    private javax.swing.JLabel lbl_id_mesa_mod_mesa;
    private javax.swing.JLabel lbl_ingre_mod_mesa;
    private javax.swing.JLabel lbl_inicio_med_mesa;
    private javax.swing.JLabel lbl_logoazul_restau;
    private javax.swing.JLabel lbl_numero_mesa;
    private javax.swing.JLabel lbl_numero_mesa_mod_mesa;
    private javax.swing.JLabel lbl_proveedores_mod_mesa;
    private javax.swing.JLabel lbl_recetario;
    private javax.swing.JLabel lbl_tipo_usuario;
    private javax.swing.JLabel lbl_titulo_mod_mesa;
    private javax.swing.JPanel pnl_barra_superior_mod_mesa;
    private javax.swing.JPanel side_pane;
    private javax.swing.JPanel side_pane1;
    private javax.swing.JPanel side_pane10;
    private javax.swing.JPanel side_pane11;
    private javax.swing.JPanel side_pane12;
    private javax.swing.JPanel side_pane13;
    private javax.swing.JPanel side_pane14;
    private javax.swing.JPanel side_pane15;
    private javax.swing.JPanel side_pane16;
    private javax.swing.JPanel side_pane17;
    private javax.swing.JPanel side_pane2;
    private javax.swing.JPanel side_pane3;
    private javax.swing.JPanel side_pane4;
    private javax.swing.JPanel side_pane5;
    private javax.swing.JPanel side_pane6;
    private javax.swing.JPanel side_pane8;
    private javax.swing.JPanel side_pane9;
    private javax.swing.JTextField txt_capacidad_mod_mesa;
    private javax.swing.JFormattedTextField txt_fecha_registro_mod_mesa;
    private javax.swing.JTextField txt_id_mesa_mod_mesa;
    private javax.swing.JTextField txt_numero_mesa;
    private javax.swing.JTextField txt_numero_mesa_mod_mesa;
    // End of variables declaration//GEN-END:variables
}
