/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.proveedor;

import Clases.Manejadora;
import Clases.Proveedor;
//import Ventanas.*;
import Ventanas_Administracion.Administrar_Mesas;
import Ventanas_Administracion.Administrar_Proveedor;
import Ventanas_Administracion.Administrar_datos_personal;
import Ventanas_Administracion.Menu_principal;
import Vista.Factura.Interfaz_Factura;
import Vista.Ingrediente.interfaz_Ingrediente;
import Vista.Recetario.interfaz_Recetario;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Agregar_Proveedor extends javax.swing.JFrame {

   
             int lastid;      
            Connection con;
            ResultSet rs;
            Statement st;
            PreparedStatement pst;
    
    
    
    public Agregar_Proveedor() {
        initComponents();
        getlastid();
        this.setLocationRelativeTo(this);
        setColor(btn_inicio_agre_prove); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_agre_prove,btn_ingre_agre_prove,btn_adm_mesa_agre_prove}, new JPanel[]{ind_2,ind_3, ind_4});
        //jProgressBar1.setValue(50);
        jl_info_rut.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese su rut con digito verificador.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        jb_info_nombre.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese su primer nombre o los dos nombres.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        jb_info_apellido.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese su primer apellido o los dos apellido.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        jButton_agregar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Agrega los datos ingresados.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        jButton_volver.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Regresa una ventana atras.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        txt_nombre_prove = new javax.swing.JTextField();
        jl_info_rut = new javax.swing.JLabel();
        lbl_telefono_prove = new javax.swing.JLabel();
        lbl_tipo_prove = new javax.swing.JLabel();
        txt_telefono_prove = new javax.swing.JTextField();
        jctipo_proveedor = new javax.swing.JComboBox<>();
        jb_info_nombre = new javax.swing.JLabel();
        lbl_direccion_prove = new javax.swing.JLabel();
        txt_direccion_prove = new javax.swing.JTextField();
        jb_info_apellido = new javax.swing.JLabel();
        lbl_nombre_prove = new javax.swing.JLabel();
        lbl_descripcion_prove = new javax.swing.JLabel();
        txt_descripcion_prove = new javax.swing.JTextField();
        lbl_email_prove = new javax.swing.JLabel();
        txt_email_prove = new javax.swing.JTextField();
        jButton_agregar = new javax.swing.JButton();
        jButton_volver = new javax.swing.JButton();
        lbl_logoazul_restau = new javax.swing.JLabel();
        side_pane = new javax.swing.JPanel();
        btn_inicio_agre_prove = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lbl_inicio_agre_provee = new javax.swing.JLabel();
        btn_dtosper_agre_prove = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbl_dtos_perso_agre_prove = new javax.swing.JLabel();
        btn_ingre_agre_prove = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbl_ingre_agre_prove = new javax.swing.JLabel();
        btn_adm_mesa_agre_prove = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbl_adm_mesa_agre_prove = new javax.swing.JLabel();
        btn_provee_agre_prove = new javax.swing.JPanel();
        ind_9 = new javax.swing.JPanel();
        lbl_proveedores_agre_prove = new javax.swing.JLabel();
        side_pane1 = new javax.swing.JPanel();
        btn_modulo_documento = new javax.swing.JPanel();
        ind_13 = new javax.swing.JPanel();
        lbl_documentos = new javax.swing.JLabel();
        btn_recetario = new javax.swing.JPanel();
        ind_12 = new javax.swing.JPanel();
        lbl_recetario = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        pnl_barra_superior_prove = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        lbl_tipo_usuario = new javax.swing.JLabel();
        lbl_icono_usuario = new javax.swing.JLabel();
        lbl_titulo_agre_proveedor = new javax.swing.JLabel();
        lbl_logorojo_restau = new javax.swing.JLabel();
        lbl_fondo_interfaz_prove = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id.setEditable(false);
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 80, -1));

        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("ID:");
        getContentPane().add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 40, -1));

        txt_nombre_prove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_proveActionPerformed(evt);
            }
        });
        txt_nombre_prove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_proveKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 190, -1));

        jl_info_rut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jl_info_rut.setForeground(new java.awt.Color(255, 255, 255));
        jl_info_rut.setText("(?)");
        getContentPane().add(jl_info_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        lbl_telefono_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefono_prove.setText("Telefono Proveedor");
        getContentPane().add(lbl_telefono_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        lbl_tipo_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_prove.setText("Tipo de proveedor");
        getContentPane().add(lbl_tipo_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        txt_telefono_prove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefono_proveActionPerformed(evt);
            }
        });
        txt_telefono_prove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefono_proveKeyTyped(evt);
            }
        });
        getContentPane().add(txt_telefono_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 190, -1));

        jctipo_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "CONGELADOS", "ADEREZOS", "ESPECIAS", "INSUMOS COCINA", "INFORMATICA" }));
        jctipo_proveedor.setDoubleBuffered(true);
        getContentPane().add(jctipo_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 190, -1));

        jb_info_nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_info_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jb_info_nombre.setText("(?)");
        getContentPane().add(jb_info_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 21, -1));

        lbl_direccion_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_direccion_prove.setText("Direccion Proveedor");
        getContentPane().add(lbl_direccion_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 120, -1));

        txt_direccion_prove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direccion_proveKeyTyped(evt);
            }
        });
        getContentPane().add(txt_direccion_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 190, -1));

        jb_info_apellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_info_apellido.setForeground(new java.awt.Color(255, 255, 255));
        jb_info_apellido.setText("(?)");
        getContentPane().add(jb_info_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, -1, -1));

        lbl_nombre_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre_prove.setText("Nombre Proveedor");
        getContentPane().add(lbl_nombre_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 110, -1));

        lbl_descripcion_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_descripcion_prove.setText("Descripcion");
        getContentPane().add(lbl_descripcion_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        txt_descripcion_prove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcion_proveActionPerformed(evt);
            }
        });
        txt_descripcion_prove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_descripcion_proveKeyTyped(evt);
            }
        });
        getContentPane().add(txt_descripcion_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 190, -1));

        lbl_email_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email_prove.setText("Email:");
        getContentPane().add(lbl_email_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));
        getContentPane().add(txt_email_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 190, -1));

        jButton_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save.png"))); // NOI18N
        jButton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 110, -1));

        jButton_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 80, -1));

        lbl_logoazul_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_superior_blanco.png"))); // NOI18N
        getContentPane().add(lbl_logoazul_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 90));

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio_agre_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_inicio_agre_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicio_agre_proveMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_inicio_agre_provee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_inicio_agre_provee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio_agre_provee.setText("Inicio");

        javax.swing.GroupLayout btn_inicio_agre_proveLayout = new javax.swing.GroupLayout(btn_inicio_agre_prove);
        btn_inicio_agre_prove.setLayout(btn_inicio_agre_proveLayout);
        btn_inicio_agre_proveLayout.setHorizontalGroup(
            btn_inicio_agre_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_agre_proveLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbl_inicio_agre_provee)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        btn_inicio_agre_proveLayout.setVerticalGroup(
            btn_inicio_agre_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_agre_proveLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_inicio_agre_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inicio_agre_provee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_inicio_agre_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        btn_dtosper_agre_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_dtosper_agre_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_dtosper_agre_proveMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_dtos_perso_agre_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_dtos_perso_agre_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dtos_perso_agre_prove.setText("Datos de personal");

        javax.swing.GroupLayout btn_dtosper_agre_proveLayout = new javax.swing.GroupLayout(btn_dtosper_agre_prove);
        btn_dtosper_agre_prove.setLayout(btn_dtosper_agre_proveLayout);
        btn_dtosper_agre_proveLayout.setHorizontalGroup(
            btn_dtosper_agre_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dtosper_agre_proveLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_dtos_perso_agre_prove, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );
        btn_dtosper_agre_proveLayout.setVerticalGroup(
            btn_dtosper_agre_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dtosper_agre_proveLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_dtosper_agre_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dtos_perso_agre_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_dtosper_agre_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, -1));

        btn_ingre_agre_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_ingre_agre_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingre_agre_proveMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_ingre_agre_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_ingre_agre_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingre_agre_prove.setText("Ingredientes");

        javax.swing.GroupLayout btn_ingre_agre_proveLayout = new javax.swing.GroupLayout(btn_ingre_agre_prove);
        btn_ingre_agre_prove.setLayout(btn_ingre_agre_proveLayout);
        btn_ingre_agre_proveLayout.setHorizontalGroup(
            btn_ingre_agre_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingre_agre_proveLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingre_agre_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        btn_ingre_agre_proveLayout.setVerticalGroup(
            btn_ingre_agre_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingre_agre_proveLayout.createSequentialGroup()
                .addGroup(btn_ingre_agre_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingre_agre_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_pane.add(btn_ingre_agre_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));

        btn_adm_mesa_agre_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_adm_mesa_agre_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_adm_mesa_agre_proveMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_adm_mesa_agre_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_adm_mesa_agre_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_adm_mesa_agre_prove.setText("Administrar Mesas");

        javax.swing.GroupLayout btn_adm_mesa_agre_proveLayout = new javax.swing.GroupLayout(btn_adm_mesa_agre_prove);
        btn_adm_mesa_agre_prove.setLayout(btn_adm_mesa_agre_proveLayout);
        btn_adm_mesa_agre_proveLayout.setHorizontalGroup(
            btn_adm_mesa_agre_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adm_mesa_agre_proveLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_adm_mesa_agre_prove)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btn_adm_mesa_agre_proveLayout.setVerticalGroup(
            btn_adm_mesa_agre_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adm_mesa_agre_proveLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_adm_mesa_agre_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adm_mesa_agre_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_adm_mesa_agre_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, -1));

        btn_provee_agre_prove.setBackground(new java.awt.Color(255, 255, 51));
        btn_provee_agre_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_provee_agre_proveMouseReleased(evt);
            }
        });

        ind_9.setOpaque(false);
        ind_9.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_9Layout = new javax.swing.GroupLayout(ind_9);
        ind_9.setLayout(ind_9Layout);
        ind_9Layout.setHorizontalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_9Layout.setVerticalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_proveedores_agre_prove.setBackground(new java.awt.Color(0, 0, 0));
        lbl_proveedores_agre_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_proveedores_agre_prove.setText("Proveedores");

        javax.swing.GroupLayout btn_provee_agre_proveLayout = new javax.swing.GroupLayout(btn_provee_agre_prove);
        btn_provee_agre_prove.setLayout(btn_provee_agre_proveLayout);
        btn_provee_agre_proveLayout.setHorizontalGroup(
            btn_provee_agre_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_provee_agre_proveLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_proveedores_agre_prove, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_provee_agre_proveLayout.setVerticalGroup(
            btn_provee_agre_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_provee_agre_proveLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_provee_agre_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_proveedores_agre_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_provee_agre_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, -1));

        side_pane1.setBackground(new java.awt.Color(251, 243, 0));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane.add(side_pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 10, 500));

        btn_modulo_documento.setBackground(new java.awt.Color(23, 35, 51));
        btn_modulo_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_modulo_documentoMouseReleased(evt);
            }
        });

        ind_13.setOpaque(false);
        ind_13.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_13Layout = new javax.swing.GroupLayout(ind_13);
        ind_13.setLayout(ind_13Layout);
        ind_13Layout.setHorizontalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_13Layout.setVerticalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_documentos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_documentos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_documentos.setText("Documentos");

        javax.swing.GroupLayout btn_modulo_documentoLayout = new javax.swing.GroupLayout(btn_modulo_documento);
        btn_modulo_documento.setLayout(btn_modulo_documentoLayout);
        btn_modulo_documentoLayout.setHorizontalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btn_modulo_documentoLayout.setVerticalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_documentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_modulo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 140, -1));

        btn_recetario.setBackground(new java.awt.Color(23, 35, 51));
        btn_recetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_recetarioMouseReleased(evt);
            }
        });

        ind_12.setOpaque(false);
        ind_12.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_12Layout = new javax.swing.GroupLayout(ind_12);
        ind_12.setLayout(ind_12Layout);
        ind_12Layout.setHorizontalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_12Layout.setVerticalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_recetario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_recetario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_recetario.setText("Recetario");

        javax.swing.GroupLayout btn_recetarioLayout = new javax.swing.GroupLayout(btn_recetario);
        btn_recetario.setLayout(btn_recetarioLayout);
        btn_recetarioLayout.setHorizontalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_recetario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_recetarioLayout.setVerticalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_recetario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_recetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        side_pane.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 30, 46));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 590));

        pnl_barra_superior_prove.setBackground(new java.awt.Color(23, 35, 51));
        pnl_barra_superior_prove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barra_superior_proveMouseDragged(evt);
            }
        });
        pnl_barra_superior_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barra_superior_proveMousePressed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(123, 156, 225));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setPreferredSize(new java.awt.Dimension(2, 20));

        lbl_tipo_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_tipo_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_usuario.setText("Usuario: Administrador");

        lbl_icono_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_48px.png"))); // NOI18N

        lbl_titulo_agre_proveedor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo_agre_proveedor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo_agre_proveedor.setText("AGREGAR PROVEEDORES");

        javax.swing.GroupLayout pnl_barra_superior_proveLayout = new javax.swing.GroupLayout(pnl_barra_superior_prove);
        pnl_barra_superior_prove.setLayout(pnl_barra_superior_proveLayout);
        pnl_barra_superior_proveLayout.setHorizontalGroup(
            pnl_barra_superior_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barra_superior_proveLayout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addGroup(pnl_barra_superior_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_proveLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_proveLayout.createSequentialGroup()
                        .addComponent(lbl_titulo_agre_proveedor)
                        .addGap(159, 159, 159)
                        .addComponent(lbl_icono_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnl_barra_superior_proveLayout.setVerticalGroup(
            pnl_barra_superior_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_proveLayout.createSequentialGroup()
                .addGroup(pnl_barra_superior_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_barra_superior_proveLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pnl_barra_superior_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_icono_usuario)
                            .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_barra_superior_proveLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbl_titulo_agre_proveedor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_barra_superior_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 90));

        lbl_logorojo_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_final.png"))); // NOI18N
        lbl_logorojo_restau.setText("jLabel17");
        getContentPane().add(lbl_logorojo_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 260, 320));

        lbl_fondo_interfaz_prove.setBackground(new java.awt.Color(83, 83, 83));
        lbl_fondo_interfaz_prove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_personal_final.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo_interfaz_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 920, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     public void getlastid()
    {
         try {
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            String DB="jdbc:oracle:thin:@localhost:1521:orcl";
            String user = "portafolio_tobal";
            String pass = "toballxd";
            String sql = "Select max(ID_PROVEEDOR) from PROVEEDOR";
          Connection con = DriverManager.getConnection(DB, user, pass);  
            st = con.createStatement();
            rs = st.executeQuery(sql);
            if(rs.next())
            {
                lastid = rs.getInt(1);
                lastid++;
                txt_id.setText(Integer.toString(lastid));
            }
            
        }catch (SQLException e) {
            
            System.out.println(e.getMessage());
            
        }catch (ClassNotFoundException cs) {
            
            System.out.println(cs.getMessage());
            
        }       
    }
    
    
        
    
    int xx,xy;
    private void pnl_barra_superior_proveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_superior_proveMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnl_barra_superior_proveMousePressed

    private void pnl_barra_superior_proveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_superior_proveMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_pnl_barra_superior_proveMouseDragged

    private void btn_inicio_agre_proveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicio_agre_proveMousePressed
        // TODO add your handling code here:
        setColor(btn_inicio_agre_prove);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_agre_prove,btn_ingre_agre_prove,btn_adm_mesa_agre_prove}, new JPanel[]{ind_2,ind_3, ind_4});
        Menu_principal mp = new Menu_principal();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicio_agre_proveMousePressed

    private void btn_dtosper_agre_proveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dtosper_agre_proveMouseReleased
        // TODO add your handling code here:
        setColor(btn_dtosper_agre_prove);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_inicio_agre_prove,btn_ingre_agre_prove,btn_adm_mesa_agre_prove}, new JPanel[]{ind_1,ind_3, ind_4});
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_dtosper_agre_proveMouseReleased

    private void btn_ingre_agre_proveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingre_agre_proveMousePressed
        // TODO add your handling code here:
        setColor(btn_ingre_agre_prove);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_agre_prove,btn_inicio_agre_prove,btn_adm_mesa_agre_prove}, new JPanel[]{ind_2,ind_1, ind_4});
        interfaz_Ingrediente adm_ingre = new interfaz_Ingrediente();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingre_agre_proveMousePressed

    private void btn_adm_mesa_agre_proveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adm_mesa_agre_proveMousePressed
        // TODO add your handling code here:
        setColor(btn_adm_mesa_agre_prove);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_agre_prove,btn_ingre_agre_prove,btn_inicio_agre_prove}, new JPanel[]{ind_2,ind_3, ind_1});
        Administrar_Mesas adm_mesa = new Administrar_Mesas();
        adm_mesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_adm_mesa_agre_proveMousePressed

    private void btn_provee_agre_proveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_provee_agre_proveMouseReleased
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_provee_agre_proveMouseReleased

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?");
        if (JOptionPane.OK_OPTION == exit)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitMousePressed

    private void txt_telefono_proveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefono_proveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefono_proveActionPerformed

    private void txt_telefono_proveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono_proveKeyTyped
        // TODO add your handling code here:
       char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txt_telefono_proveKeyTyped

    private void txt_direccion_proveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccion_proveKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if((n<'a' || n>'z') && (n<'A' || n>'Z') && (n<' ' || n>' '))evt.consume();
    }//GEN-LAST:event_txt_direccion_proveKeyTyped

    private void jButton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarActionPerformed
        // TODO add your handling code here:
        try
        {
            Proveedor per = new Proveedor();
            per.setId_proveedor(Integer.parseInt(txt_id.getText().trim()));
            per.setNom_proveedor(txt_nombre_prove.getText().trim());
            per.setTelefono_proveedor(Integer.parseInt(txt_telefono_prove.getText().trim()));
            per.setDireccion_proveedor(txt_direccion_prove.getText().trim());
            per.setDescripcion_proveedor(txt_descripcion_prove.getText().trim());
            per.setEmail_proveedor(txt_email_prove.getText().trim());
            
             if(jctipo_proveedor.getSelectedIndex() == 0)
            {
                per.setTipo_proveedor("Sin definir");
            }else {
                per.setTipo_proveedor(jctipo_proveedor.getSelectedItem().toString());
            }

            if (Manejadora.agregarProveedor(per))
            {
                JOptionPane.showMessageDialog(null, "Se ha creado un registro exitosamente");
                this.txt_nombre_prove.setText(null);
                this.txt_nombre_prove.setText(null);
                this.txt_telefono_prove.setText(null);
                this.txt_direccion_prove.setText(null);
                this.txt_descripcion_prove.setText(null);
                this.txt_email_prove.setText(null);
                this.jctipo_proveedor.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "no se pudo crear el registro","ERROR",0);
            }

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se han ingresado datos", "Informacion", 1);
        }

    }//GEN-LAST:event_jButton_agregarActionPerformed

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void txt_nombre_proveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_proveKeyTyped
        // TODO add your handling code here:
       /* char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();*/
    }//GEN-LAST:event_txt_nombre_proveKeyTyped

    private void txt_nombre_proveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_proveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_proveActionPerformed

    private void txt_descripcion_proveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcion_proveKeyTyped
        // TODO add your handling code here:
        /*char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();*/
    }//GEN-LAST:event_txt_descripcion_proveKeyTyped

    private void txt_descripcion_proveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcion_proveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcion_proveActionPerformed

    private void btn_modulo_documentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulo_documentoMouseReleased
        Interfaz_Factura adm_ingre = new Interfaz_Factura();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modulo_documentoMouseReleased

    private void btn_recetarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recetarioMouseReleased
        interfaz_Recetario adm_ingre = new interfaz_Recetario();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_recetarioMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
 
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Proveedor().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_adm_mesa_agre_prove;
    private javax.swing.JPanel btn_dtosper_agre_prove;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel btn_ingre_agre_prove;
    private javax.swing.JPanel btn_inicio_agre_prove;
    private javax.swing.JPanel btn_modulo_documento;
    private javax.swing.JPanel btn_provee_agre_prove;
    private javax.swing.JPanel btn_recetario;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_12;
    private javax.swing.JPanel ind_13;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_9;
    private javax.swing.JButton jButton_agregar;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jb_info_apellido;
    private javax.swing.JLabel jb_info_nombre;
    private javax.swing.JComboBox<String> jctipo_proveedor;
    private javax.swing.JLabel jl_info_rut;
    private javax.swing.JLabel lbl_adm_mesa_agre_prove;
    private javax.swing.JLabel lbl_descripcion_prove;
    private javax.swing.JLabel lbl_direccion_prove;
    private javax.swing.JLabel lbl_documentos;
    private javax.swing.JLabel lbl_dtos_perso_agre_prove;
    private javax.swing.JLabel lbl_email_prove;
    private javax.swing.JLabel lbl_fondo_interfaz_prove;
    private javax.swing.JLabel lbl_icono_usuario;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_ingre_agre_prove;
    private javax.swing.JLabel lbl_inicio_agre_provee;
    private javax.swing.JLabel lbl_logoazul_restau;
    private javax.swing.JLabel lbl_logorojo_restau;
    private javax.swing.JLabel lbl_nombre_prove;
    private javax.swing.JLabel lbl_proveedores_agre_prove;
    private javax.swing.JLabel lbl_recetario;
    private javax.swing.JLabel lbl_telefono_prove;
    private javax.swing.JLabel lbl_tipo_prove;
    private javax.swing.JLabel lbl_tipo_usuario;
    private javax.swing.JLabel lbl_titulo_agre_proveedor;
    private javax.swing.JPanel pnl_barra_superior_prove;
    private javax.swing.JPanel side_pane;
    private javax.swing.JPanel side_pane1;
    private javax.swing.JTextField txt_descripcion_prove;
    private javax.swing.JTextField txt_direccion_prove;
    private javax.swing.JTextField txt_email_prove;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre_prove;
    private javax.swing.JTextField txt_telefono_prove;
    // End of variables declaration//GEN-END:variables
}
