/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.proveedor;

import Vista.Mesas.*;
//import Ventanas.*;
import java.awt.Color;
import javax.swing.JPanel;
import Clases.Manejadora;
import Clases.Personal;
import Ventanas_Administracion.Administrar_Mesas;
import Ventanas_Administracion.Administrar_Proveedor;
import Ventanas_Administracion.Administrar_datos_personal;
import Ventanas_Administracion.Menu_principal;
import Vista.Factura.Interfaz_Factura;
import Vista.Ingrediente.interfaz_Ingrediente;
import Vista.Recetario.interfaz_Recetario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Eliminar_Proveedor extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Eliminar_Proveedor() {
        initComponents();
        this.setLocationRelativeTo(this);
        setColor(btn_inicio_elim_prove); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_elim_prove,btn_ingred_elim_prove,btn_adm_mesa_elim_prove}, new JPanel[]{ind_2,ind_3, ind_4});
        //jProgressBar1.setValue(50);
        jl_info_rut.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese su rut con digito verificador.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        jButton_buscar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Busca a un personal mediante su rut.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        jButton_volver.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Regresa una ventana atras.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        jButton_eliminar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Elimina el personal seleccionado.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        side_pane6 = new javax.swing.JPanel();
        side_pane3 = new javax.swing.JPanel();
        side_pane5 = new javax.swing.JPanel();
        side_pane4 = new javax.swing.JPanel();
        side_pane7 = new javax.swing.JPanel();
        side_pane1 = new javax.swing.JPanel();
        lbl_logoazul_restau = new javax.swing.JLabel();
        jButton_mostrar = new javax.swing.JButton();
        pnl_barra_lateral_prove = new javax.swing.JPanel();
        btn_inicio_elim_prove = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lbl_inicio_elim_prove = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        btn_provee_elim_prove = new javax.swing.JPanel();
        ind_11 = new javax.swing.JPanel();
        lbl_proveedores_elim_prove = new javax.swing.JLabel();
        btn_dtosper_elim_prove = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbl_dtos_perso_elim_prove = new javax.swing.JLabel();
        btn_adm_mesa_elim_prove = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbl_adm_mesa_elim_prove = new javax.swing.JLabel();
        btn_ingred_elim_prove = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbl_ingred_elim_prove = new javax.swing.JLabel();
        btn_recetario = new javax.swing.JPanel();
        ind_12 = new javax.swing.JPanel();
        lbl_recetario = new javax.swing.JLabel();
        btn_modulo_documento = new javax.swing.JPanel();
        ind_13 = new javax.swing.JPanel();
        lbl_documentos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_tipo_usuario = new javax.swing.JLabel();
        lbl_icono_usuario = new javax.swing.JLabel();
        lbl_titulo_adm_prove = new javax.swing.JLabel();
        jButton_eliminar = new javax.swing.JButton();
        jl_info_rut = new javax.swing.JLabel();
        jButton_volver = new javax.swing.JButton();
        lbl_nombre_prove = new javax.swing.JLabel();
        txt_nombre_prove = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_mostrar = new javax.swing.JTable();
        lbl_fondo_interfaz_prove = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane6.setBackground(new java.awt.Color(251, 243, 0));
        side_pane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 10, 290));

        side_pane3.setBackground(new java.awt.Color(251, 243, 0));
        side_pane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane5.setBackground(new java.awt.Color(251, 243, 0));
        side_pane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane3.add(side_pane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        getContentPane().add(side_pane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 740, 10));

        side_pane4.setBackground(new java.awt.Color(251, 243, 0));
        side_pane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 730, 10));

        side_pane7.setBackground(new java.awt.Color(251, 243, 0));
        side_pane7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 10, 290));

        side_pane1.setBackground(new java.awt.Color(251, 243, 0));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 10, 500));

        lbl_logoazul_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_superior_blanco.png"))); // NOI18N
        lbl_logoazul_restau.setText("jLabel17");
        getContentPane().add(lbl_logoazul_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 205, 110));

        jButton_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Read.png"))); // NOI18N
        jButton_mostrar.setText("Mostrar");
        jButton_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 140, -1));

        pnl_barra_lateral_prove.setBackground(new java.awt.Color(23, 35, 51));
        pnl_barra_lateral_prove.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio_elim_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_inicio_elim_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicio_elim_proveMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_inicio_elim_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_inicio_elim_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio_elim_prove.setText("Inicio");

        javax.swing.GroupLayout btn_inicio_elim_proveLayout = new javax.swing.GroupLayout(btn_inicio_elim_prove);
        btn_inicio_elim_prove.setLayout(btn_inicio_elim_proveLayout);
        btn_inicio_elim_proveLayout.setHorizontalGroup(
            btn_inicio_elim_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_elim_proveLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbl_inicio_elim_prove)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        btn_inicio_elim_proveLayout.setVerticalGroup(
            btn_inicio_elim_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_elim_proveLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_inicio_elim_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inicio_elim_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_inicio_elim_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        pnl_barra_lateral_prove.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 30, 46));

        btn_provee_elim_prove.setBackground(new java.awt.Color(251, 243, 0));
        btn_provee_elim_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_provee_elim_proveMouseReleased(evt);
            }
        });

        ind_11.setOpaque(false);
        ind_11.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_11Layout = new javax.swing.GroupLayout(ind_11);
        ind_11.setLayout(ind_11Layout);
        ind_11Layout.setHorizontalGroup(
            ind_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_11Layout.setVerticalGroup(
            ind_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_proveedores_elim_prove.setBackground(new java.awt.Color(0, 0, 0));
        lbl_proveedores_elim_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_proveedores_elim_prove.setText("Proveedores");

        javax.swing.GroupLayout btn_provee_elim_proveLayout = new javax.swing.GroupLayout(btn_provee_elim_prove);
        btn_provee_elim_prove.setLayout(btn_provee_elim_proveLayout);
        btn_provee_elim_proveLayout.setHorizontalGroup(
            btn_provee_elim_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_provee_elim_proveLayout.createSequentialGroup()
                .addComponent(ind_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_proveedores_elim_prove, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_provee_elim_proveLayout.setVerticalGroup(
            btn_provee_elim_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_provee_elim_proveLayout.createSequentialGroup()
                .addComponent(ind_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_provee_elim_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_proveedores_elim_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_provee_elim_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, -1));

        btn_dtosper_elim_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_dtosper_elim_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_dtosper_elim_proveMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_dtos_perso_elim_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_dtos_perso_elim_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dtos_perso_elim_prove.setText("Datos de personal");

        javax.swing.GroupLayout btn_dtosper_elim_proveLayout = new javax.swing.GroupLayout(btn_dtosper_elim_prove);
        btn_dtosper_elim_prove.setLayout(btn_dtosper_elim_proveLayout);
        btn_dtosper_elim_proveLayout.setHorizontalGroup(
            btn_dtosper_elim_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dtosper_elim_proveLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_dtos_perso_elim_prove, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );
        btn_dtosper_elim_proveLayout.setVerticalGroup(
            btn_dtosper_elim_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dtosper_elim_proveLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_dtosper_elim_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dtos_perso_elim_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_dtosper_elim_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, -1));

        btn_adm_mesa_elim_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_adm_mesa_elim_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_adm_mesa_elim_proveMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_adm_mesa_elim_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_adm_mesa_elim_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_adm_mesa_elim_prove.setText("Administrar Mesas");

        javax.swing.GroupLayout btn_adm_mesa_elim_proveLayout = new javax.swing.GroupLayout(btn_adm_mesa_elim_prove);
        btn_adm_mesa_elim_prove.setLayout(btn_adm_mesa_elim_proveLayout);
        btn_adm_mesa_elim_proveLayout.setHorizontalGroup(
            btn_adm_mesa_elim_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adm_mesa_elim_proveLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_adm_mesa_elim_prove)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btn_adm_mesa_elim_proveLayout.setVerticalGroup(
            btn_adm_mesa_elim_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adm_mesa_elim_proveLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_adm_mesa_elim_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adm_mesa_elim_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_adm_mesa_elim_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, -1));

        btn_ingred_elim_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_ingred_elim_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingred_elim_proveMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_ingred_elim_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_ingred_elim_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingred_elim_prove.setText("Ingredientes");

        javax.swing.GroupLayout btn_ingred_elim_proveLayout = new javax.swing.GroupLayout(btn_ingred_elim_prove);
        btn_ingred_elim_prove.setLayout(btn_ingred_elim_proveLayout);
        btn_ingred_elim_proveLayout.setHorizontalGroup(
            btn_ingred_elim_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_elim_proveLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingred_elim_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        btn_ingred_elim_proveLayout.setVerticalGroup(
            btn_ingred_elim_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_elim_proveLayout.createSequentialGroup()
                .addGroup(btn_ingred_elim_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingred_elim_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_barra_lateral_prove.add(btn_ingred_elim_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));

        btn_recetario.setBackground(new java.awt.Color(23, 35, 51));
        btn_recetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_recetarioMouseReleased(evt);
            }
        });

        ind_12.setOpaque(false);
        ind_12.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_12Layout = new javax.swing.GroupLayout(ind_12);
        ind_12.setLayout(ind_12Layout);
        ind_12Layout.setHorizontalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_12Layout.setVerticalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_recetario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_recetario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_recetario.setText("Recetario");

        javax.swing.GroupLayout btn_recetarioLayout = new javax.swing.GroupLayout(btn_recetario);
        btn_recetario.setLayout(btn_recetarioLayout);
        btn_recetarioLayout.setHorizontalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_recetario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_recetarioLayout.setVerticalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_recetario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_recetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, -1));

        btn_modulo_documento.setBackground(new java.awt.Color(23, 35, 51));
        btn_modulo_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_modulo_documentoMouseReleased(evt);
            }
        });

        ind_13.setOpaque(false);
        ind_13.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_13Layout = new javax.swing.GroupLayout(ind_13);
        ind_13.setLayout(ind_13Layout);
        ind_13Layout.setHorizontalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_13Layout.setVerticalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_documentos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_documentos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_documentos.setText("Documentos");

        javax.swing.GroupLayout btn_modulo_documentoLayout = new javax.swing.GroupLayout(btn_modulo_documento);
        btn_modulo_documento.setLayout(btn_modulo_documentoLayout);
        btn_modulo_documentoLayout.setHorizontalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btn_modulo_documentoLayout.setVerticalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_documentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_modulo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 140, -1));

        getContentPane().add(pnl_barra_lateral_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 590));

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        lbl_tipo_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_tipo_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_usuario.setText("Usuario: Administrador");

        lbl_icono_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_48px.png"))); // NOI18N

        lbl_titulo_adm_prove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo_adm_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo_adm_prove.setText("Eliminar Proveedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addComponent(lbl_titulo_adm_prove)
                .addGap(183, 183, 183)
                .addComponent(lbl_icono_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_icono_usuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_titulo_adm_prove))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 90));

        jButton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete.png"))); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 140, -1));

        jl_info_rut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jl_info_rut.setForeground(new java.awt.Color(255, 255, 255));
        jl_info_rut.setText("(?)");
        getContentPane().add(jl_info_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 20, -1));

        jButton_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 80, -1));

        lbl_nombre_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre_prove.setText("Nombre proveedor");
        getContentPane().add(lbl_nombre_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, 20));

        txt_nombre_prove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_proveActionPerformed(evt);
            }
        });
        txt_nombre_prove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_proveKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 115, -1));

        jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_P.png"))); // NOI18N
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 80, -1));

        jTable_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_mostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 720, 270));

        lbl_fondo_interfaz_prove.setBackground(new java.awt.Color(83, 83, 83));
        lbl_fondo_interfaz_prove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_personal_final.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo_interfaz_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 930, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_inicio_elim_proveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicio_elim_proveMousePressed
        // TODO add your handling code here:
        setColor(btn_inicio_elim_prove);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_elim_prove,btn_ingred_elim_prove,btn_adm_mesa_elim_prove}, new JPanel[]{ind_2,ind_3, ind_4});
        Menu_principal mp = new Menu_principal();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicio_elim_proveMousePressed

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?");
        if (JOptionPane.OK_OPTION == exit)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitMousePressed

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:

        int selec;
        selec = (Integer)this.jTable_mostrar.getSelectedRow();

        if (selec==-1)
        {
            JOptionPane.showMessageDialog(this,"No se ha seleccionado ninguna fila");
        }
        else
        {

            int conf = JOptionPane.showConfirmDialog(this,"Esta seguro de eliminar seleccionado?");
            if (JOptionPane.OK_OPTION == conf) {

                selec = (Integer)this.jTable_mostrar.getSelectedRow();
                String rut;
                rut = this.jTable_mostrar.getValueAt(selec, 0).toString();
                try {
                    Manejadora.eliminarProveedor(conf, rut);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Eliminar_Mesa.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this,"Registro eliminado");
                this.txt_nombre_prove.setText(null);
                this.txt_nombre_prove.setText(null);
            }
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        try
        {
            DefaultTableModel modelo= new DefaultTableModel();
                 modelo.addColumn("ID PROVEEDOR");
                modelo.addColumn("NOMBRE PROVEEDOR");
                modelo.addColumn("Telefono");
                modelo.addColumn("Direccion");
                modelo.addColumn("Descripcion Proveedor");
                modelo.addColumn("Email Proveedor ");
            this.jTable_mostrar.setModel(modelo);
            try {
                ResultSet rs = Manejadora.buscarProveedor(this.txt_nombre_prove.getText());
                String [] datos = new String[6];
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);   
                    modelo.addRow(datos);
                    this.jTable_mostrar.setModel(modelo);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se ha ingresado rut");
        }

    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void txt_nombre_proveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_proveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_proveActionPerformed

    private void txt_nombre_proveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_proveKeyTyped
        // TODO add your handling code here:
        /*char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();*/
    }//GEN-LAST:event_txt_nombre_proveKeyTyped

    private void jButton_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mostrarActionPerformed
        // TODO add your handling code here:
        
    
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("ID PROVEEDOR");
        modelo.addColumn("NOMBRE PROVEEDOR");
        modelo.addColumn("Telefono");
        modelo.addColumn("Direccion");
        modelo.addColumn("Descripcion Proveedor");
        modelo.addColumn("Email Proveedor ");
        this.jTable_mostrar.setModel(modelo);

        try {
            ResultSet rs = Manejadora.mostrarProveedor();
            String [] datos = new String[6];
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                modelo.addRow(datos);
                this.jTable_mostrar.setModel(modelo);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_mostrarActionPerformed

    private void btn_provee_elim_proveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_provee_elim_proveMouseReleased
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_provee_elim_proveMouseReleased

    private void btn_dtosper_elim_proveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dtosper_elim_proveMouseReleased
        // TODO add your handling code here:
        setColor(btn_dtosper_elim_prove);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_inicio_elim_prove,btn_ingred_elim_prove,btn_adm_mesa_elim_prove}, new JPanel[]{ind_1,ind_3, ind_4});
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_dtosper_elim_proveMouseReleased

    private void btn_adm_mesa_elim_proveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adm_mesa_elim_proveMousePressed
        // TODO add your handling code here:
        setColor(btn_adm_mesa_elim_prove);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_elim_prove,btn_ingred_elim_prove,btn_inicio_elim_prove}, new JPanel[]{ind_2,ind_3, ind_1});
        Administrar_Mesas adm_mesa = new Administrar_Mesas();
        adm_mesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_adm_mesa_elim_proveMousePressed

    private void btn_ingred_elim_proveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingred_elim_proveMousePressed
        // TODO add your handling code here:
        setColor(btn_ingred_elim_prove);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_elim_prove,btn_inicio_elim_prove,btn_adm_mesa_elim_prove}, new JPanel[]{ind_2,ind_1, ind_4});
        interfaz_Ingrediente adm_ingre = new interfaz_Ingrediente();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingred_elim_proveMousePressed

    private void btn_recetarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recetarioMouseReleased
        interfaz_Recetario adm_ingre = new interfaz_Recetario();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_recetarioMouseReleased

    private void btn_modulo_documentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulo_documentoMouseReleased
        Interfaz_Factura adm_ingre = new Interfaz_Factura();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modulo_documentoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar_Proveedor().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_adm_mesa_elim_prove;
    private javax.swing.JPanel btn_dtosper_elim_prove;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel btn_ingred_elim_prove;
    private javax.swing.JPanel btn_inicio_elim_prove;
    private javax.swing.JPanel btn_modulo_documento;
    private javax.swing.JPanel btn_provee_elim_prove;
    private javax.swing.JPanel btn_recetario;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_11;
    private javax.swing.JPanel ind_12;
    private javax.swing.JPanel ind_13;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_mostrar;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_mostrar;
    private javax.swing.JLabel jl_info_rut;
    private javax.swing.JLabel lbl_adm_mesa_elim_prove;
    private javax.swing.JLabel lbl_documentos;
    private javax.swing.JLabel lbl_dtos_perso_elim_prove;
    private javax.swing.JLabel lbl_fondo_interfaz_prove;
    private javax.swing.JLabel lbl_icono_usuario;
    private javax.swing.JLabel lbl_ingred_elim_prove;
    private javax.swing.JLabel lbl_inicio_elim_prove;
    private javax.swing.JLabel lbl_logoazul_restau;
    private javax.swing.JLabel lbl_nombre_prove;
    private javax.swing.JLabel lbl_proveedores_elim_prove;
    private javax.swing.JLabel lbl_recetario;
    private javax.swing.JLabel lbl_tipo_usuario;
    private javax.swing.JLabel lbl_titulo_adm_prove;
    private javax.swing.JPanel pnl_barra_lateral_prove;
    private javax.swing.JPanel side_pane1;
    private javax.swing.JPanel side_pane3;
    private javax.swing.JPanel side_pane4;
    private javax.swing.JPanel side_pane5;
    private javax.swing.JPanel side_pane6;
    private javax.swing.JPanel side_pane7;
    private javax.swing.JTextField txt_nombre_prove;
    // End of variables declaration//GEN-END:variables
}
