/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.proveedor;

//import Ventanas.*;
import java.awt.Color;
import javax.swing.JPanel;
import Clases.Manejadora;
import Clases.Proveedor;
import Ventanas_Administracion.Administrar_Mesas;
import Ventanas_Administracion.Administrar_Proveedor;
import Ventanas_Administracion.Administrar_datos_personal;
import Ventanas_Administracion.Menu_principal;
import Vista.Factura.Interfaz_Factura;
import Vista.Ingrediente.interfaz_Ingrediente;
import Vista.Recetario.interfaz_Recetario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Modificar_Proveedor extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Modificar_Proveedor() {
        initComponents();
        this.setLocationRelativeTo(this);
        setColor(btn_inicio_mod_prove); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_mod_prove,btn_ingred_mod_prove,btn_adm_mesa_mod_prove}, new JPanel[]{ind_2,ind_3, ind_4});
        //jProgressBar1.setValue(50);
        jl_info_rut_buscar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Ingrese su rut y digito verificador.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
                jButton_buscar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Busca un personal mediante su rut y digito verificador.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
                jButton_volver.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Regresa una ventana atras.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
        jButton_modificar.setToolTipText(""
                + "<html>"
                + "<head>"
                + "<style>"
                + "#contenido{"
                + "backgroun: #f60;"
                + "color: black"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div id = 'contenido'>"
                + "<strong>Actualiza los datos del personal seleccionado.</strong>"
                + "</div>"
                + "</body>"
                + "</html>"
                +"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_mostrar = new javax.swing.JButton();
        side_pane12 = new javax.swing.JPanel();
        side_pane13 = new javax.swing.JPanel();
        side_pane14 = new javax.swing.JPanel();
        side_pane15 = new javax.swing.JPanel();
        side_pane16 = new javax.swing.JPanel();
        side_pane17 = new javax.swing.JPanel();
        side_pane11 = new javax.swing.JPanel();
        side_pane1 = new javax.swing.JPanel();
        side_pane10 = new javax.swing.JPanel();
        side_pane6 = new javax.swing.JPanel();
        side_pane2 = new javax.swing.JPanel();
        side_pane5 = new javax.swing.JPanel();
        side_pane8 = new javax.swing.JPanel();
        side_pane9 = new javax.swing.JPanel();
        side_pane3 = new javax.swing.JPanel();
        side_pane4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pnl_barra_lateral_prove = new javax.swing.JPanel();
        btn_inicio_mod_prove = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lbl_inicio_mod_prove = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        btn_proveedores_adm_prove = new javax.swing.JPanel();
        ind_11 = new javax.swing.JPanel();
        lbl_proveedores_adm_prove = new javax.swing.JLabel();
        btn_dtosper_mod_prove = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbl_dtos_perso_mod_prove = new javax.swing.JLabel();
        btn_adm_mesa_mod_prove = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbl_adm_mesa_mod_prove = new javax.swing.JLabel();
        btn_ingred_mod_prove = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbl_ingre_mod_prove = new javax.swing.JLabel();
        btn_recetario = new javax.swing.JPanel();
        ind_12 = new javax.swing.JPanel();
        lbl_recetario = new javax.swing.JLabel();
        btn_modulo_documento = new javax.swing.JPanel();
        ind_13 = new javax.swing.JPanel();
        lbl_documentos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_nombre_prove = new javax.swing.JTextField();
        lbl_descripcion_prove = new javax.swing.JLabel();
        txt_descripcion_prove = new javax.swing.JTextField();
        lbl_telefono_prove = new javax.swing.JLabel();
        lbl_buscar_prove = new javax.swing.JLabel();
        txt_telefono_prove = new javax.swing.JTextField();
        txtrut = new javax.swing.JTextField();
        lbl_direccion_prove = new javax.swing.JLabel();
        lbl_tipo_prove = new javax.swing.JLabel();
        txt_direccion_prove = new javax.swing.JTextField();
        txt_email_prove = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_mostrar = new javax.swing.JTable();
        jButton_modificar = new javax.swing.JButton();
        jButton_volver = new javax.swing.JButton();
        lbl_id_prove = new javax.swing.JLabel();
        txt_id_prove = new javax.swing.JTextField();
        lbl_nombre_prove = new javax.swing.JLabel();
        jl_info_rut_buscar = new javax.swing.JLabel();
        jl_info_mostrar = new javax.swing.JLabel();
        lbl_email_prove = new javax.swing.JLabel();
        jctipo_prove = new javax.swing.JComboBox<>();
        lbl_fondo_interfaz_prove = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Read.png"))); // NOI18N
        jButton_mostrar.setText("Mostrar");
        jButton_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 150, 40));

        side_pane12.setBackground(new java.awt.Color(251, 243, 0));
        side_pane12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane13.setBackground(new java.awt.Color(251, 243, 0));
        side_pane13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane12.add(side_pane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        getContentPane().add(side_pane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 10, 80));

        side_pane14.setBackground(new java.awt.Color(251, 243, 0));
        side_pane14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane15.setBackground(new java.awt.Color(251, 243, 0));
        side_pane15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane14.add(side_pane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane16.setBackground(new java.awt.Color(251, 243, 0));
        side_pane16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane17.setBackground(new java.awt.Color(251, 243, 0));
        side_pane17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane16.add(side_pane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane14.add(side_pane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 690, 10));

        getContentPane().add(side_pane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 460, 10));

        side_pane11.setBackground(new java.awt.Color(251, 243, 0));
        side_pane11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 10, 80));

        side_pane1.setBackground(new java.awt.Color(251, 243, 0));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 10, 500));

        side_pane10.setBackground(new java.awt.Color(251, 243, 0));
        side_pane10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 480, 10));

        side_pane6.setBackground(new java.awt.Color(251, 243, 0));
        side_pane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 10, 210));

        side_pane2.setBackground(new java.awt.Color(251, 243, 0));
        side_pane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane5.setBackground(new java.awt.Color(251, 243, 0));
        side_pane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane2.add(side_pane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane8.setBackground(new java.awt.Color(251, 243, 0));
        side_pane8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane9.setBackground(new java.awt.Color(251, 243, 0));
        side_pane9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane8.add(side_pane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 710, 10));

        side_pane2.add(side_pane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 690, 10));

        getContentPane().add(side_pane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 830, 10));

        side_pane3.setBackground(new java.awt.Color(251, 243, 0));
        side_pane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 830, 10));

        side_pane4.setBackground(new java.awt.Color(251, 243, 0));
        side_pane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(side_pane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 310, 10, 210));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_superior_blanco.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 205, 100));

        pnl_barra_lateral_prove.setBackground(new java.awt.Color(23, 35, 51));
        pnl_barra_lateral_prove.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio_mod_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_inicio_mod_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicio_mod_proveMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_inicio_mod_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_inicio_mod_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio_mod_prove.setText("Inicio");

        javax.swing.GroupLayout btn_inicio_mod_proveLayout = new javax.swing.GroupLayout(btn_inicio_mod_prove);
        btn_inicio_mod_prove.setLayout(btn_inicio_mod_proveLayout);
        btn_inicio_mod_proveLayout.setHorizontalGroup(
            btn_inicio_mod_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_mod_proveLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbl_inicio_mod_prove)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_inicio_mod_proveLayout.setVerticalGroup(
            btn_inicio_mod_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_mod_proveLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_inicio_mod_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inicio_mod_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_inicio_mod_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        pnl_barra_lateral_prove.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 30, 46));

        btn_proveedores_adm_prove.setBackground(new java.awt.Color(251, 243, 0));
        btn_proveedores_adm_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_proveedores_adm_proveMouseReleased(evt);
            }
        });

        ind_11.setOpaque(false);
        ind_11.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_11Layout = new javax.swing.GroupLayout(ind_11);
        ind_11.setLayout(ind_11Layout);
        ind_11Layout.setHorizontalGroup(
            ind_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_11Layout.setVerticalGroup(
            ind_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_proveedores_adm_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_proveedores_adm_prove.setText("Proveedores");

        javax.swing.GroupLayout btn_proveedores_adm_proveLayout = new javax.swing.GroupLayout(btn_proveedores_adm_prove);
        btn_proveedores_adm_prove.setLayout(btn_proveedores_adm_proveLayout);
        btn_proveedores_adm_proveLayout.setHorizontalGroup(
            btn_proveedores_adm_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_proveedores_adm_proveLayout.createSequentialGroup()
                .addComponent(ind_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_proveedores_adm_prove, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_proveedores_adm_proveLayout.setVerticalGroup(
            btn_proveedores_adm_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_proveedores_adm_proveLayout.createSequentialGroup()
                .addComponent(ind_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_proveedores_adm_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_proveedores_adm_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_proveedores_adm_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, -1));

        btn_dtosper_mod_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_dtosper_mod_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_dtosper_mod_proveMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_dtos_perso_mod_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_dtos_perso_mod_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dtos_perso_mod_prove.setText("Datos de personal");

        javax.swing.GroupLayout btn_dtosper_mod_proveLayout = new javax.swing.GroupLayout(btn_dtosper_mod_prove);
        btn_dtosper_mod_prove.setLayout(btn_dtosper_mod_proveLayout);
        btn_dtosper_mod_proveLayout.setHorizontalGroup(
            btn_dtosper_mod_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dtosper_mod_proveLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_dtos_perso_mod_prove, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );
        btn_dtosper_mod_proveLayout.setVerticalGroup(
            btn_dtosper_mod_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dtosper_mod_proveLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_dtosper_mod_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dtos_perso_mod_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_dtosper_mod_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, -1));

        btn_adm_mesa_mod_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_adm_mesa_mod_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_adm_mesa_mod_proveMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_adm_mesa_mod_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_adm_mesa_mod_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_adm_mesa_mod_prove.setText("Administrar Mesas");

        javax.swing.GroupLayout btn_adm_mesa_mod_proveLayout = new javax.swing.GroupLayout(btn_adm_mesa_mod_prove);
        btn_adm_mesa_mod_prove.setLayout(btn_adm_mesa_mod_proveLayout);
        btn_adm_mesa_mod_proveLayout.setHorizontalGroup(
            btn_adm_mesa_mod_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adm_mesa_mod_proveLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_adm_mesa_mod_prove)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btn_adm_mesa_mod_proveLayout.setVerticalGroup(
            btn_adm_mesa_mod_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adm_mesa_mod_proveLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_adm_mesa_mod_proveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adm_mesa_mod_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_adm_mesa_mod_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, -1));

        btn_ingred_mod_prove.setBackground(new java.awt.Color(23, 35, 51));
        btn_ingred_mod_prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingred_mod_proveMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_ingre_mod_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_ingre_mod_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingre_mod_prove.setText("Ingredientes");

        javax.swing.GroupLayout btn_ingred_mod_proveLayout = new javax.swing.GroupLayout(btn_ingred_mod_prove);
        btn_ingred_mod_prove.setLayout(btn_ingred_mod_proveLayout);
        btn_ingred_mod_proveLayout.setHorizontalGroup(
            btn_ingred_mod_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_mod_proveLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingre_mod_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        btn_ingred_mod_proveLayout.setVerticalGroup(
            btn_ingred_mod_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_mod_proveLayout.createSequentialGroup()
                .addGroup(btn_ingred_mod_proveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingre_mod_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_barra_lateral_prove.add(btn_ingred_mod_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));

        btn_recetario.setBackground(new java.awt.Color(23, 35, 51));
        btn_recetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_recetarioMouseReleased(evt);
            }
        });

        ind_12.setOpaque(false);
        ind_12.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_12Layout = new javax.swing.GroupLayout(ind_12);
        ind_12.setLayout(ind_12Layout);
        ind_12Layout.setHorizontalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_12Layout.setVerticalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_recetario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_recetario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_recetario.setText("Recetario");

        javax.swing.GroupLayout btn_recetarioLayout = new javax.swing.GroupLayout(btn_recetario);
        btn_recetario.setLayout(btn_recetarioLayout);
        btn_recetarioLayout.setHorizontalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_recetario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_recetarioLayout.setVerticalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_recetario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_recetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, -1));

        btn_modulo_documento.setBackground(new java.awt.Color(23, 35, 51));
        btn_modulo_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_modulo_documentoMouseReleased(evt);
            }
        });

        ind_13.setOpaque(false);
        ind_13.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_13Layout = new javax.swing.GroupLayout(ind_13);
        ind_13.setLayout(ind_13Layout);
        ind_13Layout.setHorizontalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_13Layout.setVerticalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_documentos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_documentos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_documentos.setText("Documentos");

        javax.swing.GroupLayout btn_modulo_documentoLayout = new javax.swing.GroupLayout(btn_modulo_documento);
        btn_modulo_documento.setLayout(btn_modulo_documentoLayout);
        btn_modulo_documentoLayout.setHorizontalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btn_modulo_documentoLayout.setVerticalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_documentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_prove.add(btn_modulo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 140, -1));

        getContentPane().add(pnl_barra_lateral_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 590));

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuario: Administrador");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_48px.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Modificar Proveedores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(179, 179, 179)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 90));

        txt_nombre_prove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_proveKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 155, -1));

        lbl_descripcion_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_descripcion_prove.setText("Descripción");
        getContentPane().add(lbl_descripcion_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));
        getContentPane().add(txt_descripcion_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 140, 20));

        lbl_telefono_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefono_prove.setText("TELEFONO:");
        getContentPane().add(lbl_telefono_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        lbl_buscar_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_buscar_prove.setText("Busca proveedor");
        getContentPane().add(lbl_buscar_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 20));

        txt_telefono_prove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefono_proveKeyTyped(evt);
            }
        });
        getContentPane().add(txt_telefono_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 155, -1));

        txtrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutKeyTyped(evt);
            }
        });
        getContentPane().add(txtrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 130, 140, -1));

        lbl_direccion_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_direccion_prove.setText("DIRECCION");
        getContentPane().add(lbl_direccion_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        lbl_tipo_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipo_prove.setText("TIPO PROVEEDOR");
        getContentPane().add(lbl_tipo_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));
        getContentPane().add(txt_direccion_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 160, -1));
        getContentPane().add(txt_email_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 140, 20));

        jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar_P.png"))); // NOI18N
        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 120, 30));

        jTable_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_mostrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable_mostrarMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_mostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 830, 190));

        jButton_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Update.png"))); // NOI18N
        jButton_modificar.setText("Modificar");
        jButton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 150, -1));

        jButton_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 530, 100, -1));

        lbl_id_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id_prove.setText("ID PROVEEDOR:");
        getContentPane().add(lbl_id_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 100, -1));

        txt_id_prove.setEditable(false);
        txt_id_prove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_id_proveKeyTyped(evt);
            }
        });
        getContentPane().add(txt_id_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 60, -1));

        lbl_nombre_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre_prove.setText("NOMBRE PROVEEDOR");
        getContentPane().add(lbl_nombre_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, 20));

        jl_info_rut_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jl_info_rut_buscar.setText("(?)");
        getContentPane().add(jl_info_rut_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 25, -1));

        jl_info_mostrar.setForeground(new java.awt.Color(255, 255, 255));
        jl_info_mostrar.setText("(?)");
        getContentPane().add(jl_info_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 21, -1));

        lbl_email_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email_prove.setText("EMAIL");
        getContentPane().add(lbl_email_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, 10));

        jctipo_prove.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione", "CONGELADOS", "ADEREZOS", "ESPECIAS", "INSUMOS COCINA", "INFORMATICA" }));
        getContentPane().add(jctipo_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 140, -1));

        lbl_fondo_interfaz_prove.setBackground(new java.awt.Color(83, 83, 83));
        lbl_fondo_interfaz_prove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_personal_final.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo_interfaz_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 930, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_inicio_mod_proveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicio_mod_proveMousePressed
        // TODO add your handling code here:
       
        Menu_principal evento = new Menu_principal();
        evento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicio_mod_proveMousePressed

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?");
        if (JOptionPane.OK_OPTION == exit)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitMousePressed

    private void txt_nombre_proveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_proveKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if((n<'a' || n>'z') && (n<'A' || n>'Z') && (n<' ' || n>' '))evt.consume();
    }//GEN-LAST:event_txt_nombre_proveKeyTyped

    private void txt_telefono_proveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono_proveKeyTyped
        // TODO add your handling code here:
       /* char n = evt.getKeyChar();
        if((n<'a' || n>'z') && (n<'A' || n>'Z') && (n<' ' || n>' '))evt.consume();*/
    }//GEN-LAST:event_txt_telefono_proveKeyTyped

    private void txtrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyTyped
        // TODO add your handling code here:
       /* char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();*/
    }//GEN-LAST:event_txtrutKeyTyped

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        try
        {
            DefaultTableModel modelo= new DefaultTableModel();
                 modelo.addColumn("ID PROVEEDOR");
                modelo.addColumn("Nombre Proveedor");
                modelo.addColumn("Telefono");
                modelo.addColumn("Direccion");
                modelo.addColumn("Tipo de Proveedor");
                modelo.addColumn("Email");
            this.jTable_mostrar.setModel(modelo);
            try {
                ResultSet rs = Manejadora.buscarProveedor(this.txtrut.getText().toUpperCase());
                String [] datos = new String[6];
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    modelo.addRow(datos);
                    this.jTable_mostrar.setModel(modelo);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se ha ingresado Proveedor");
        }
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jTable_mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_mostrarMouseClicked
        // TODO add your handling code here:
        try
        {
            int x = jTable_mostrar.getSelectedRow();
            String rut = (String)jTable_mostrar.getValueAt(x, 0);
            String nombre = (String)jTable_mostrar.getValueAt(x, 1);
            String apellido = (String)jTable_mostrar.getValueAt(x, 2);
            String celular = (String)jTable_mostrar.getValueAt(x, 3);
            String descripcion = (String)jTable_mostrar.getValueAt(x, 4);
            String correo = (String)jTable_mostrar.getValueAt(x, 5);
            String tipo_pers = (String)jTable_mostrar.getValueAt(x, 6);
         

            txt_id_prove.setText(rut);
            txt_nombre_prove.setText(nombre);
            txt_telefono_prove.setText(apellido);
            txt_direccion_prove.setText(celular);
            txt_descripcion_prove.setText(descripcion);
            txt_email_prove.setText(correo);
            jctipo_prove.setSelectedItem(tipo_pers);

        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se ha seleccionado ninguna fila");
        }

    }//GEN-LAST:event_jTable_mostrarMouseClicked

    private void jButton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modificarActionPerformed
        // TODO add your handling code here:

        try
        {
            Proveedor per = new Proveedor();
            per.setId_proveedor(Integer.parseInt(txt_id_prove.getText().trim()));
            per.setNom_proveedor(txt_nombre_prove.getText().trim());
            per.setTelefono_proveedor(Integer.parseInt(txt_telefono_prove.getText().trim()));
            per.setDireccion_proveedor(txt_direccion_prove.getText().trim());
            per.setDescripcion_proveedor(txt_descripcion_prove.getText().trim());
            per.setEmail_proveedor(txt_email_prove.getText().trim());
         
            if(jctipo_prove.getSelectedIndex() == 0)
            {
                per.setTipo_proveedor("Sin definir");
            }else {
                per.setTipo_proveedor(jctipo_prove.getSelectedItem().toString());
            }
            
            
            
            if (Manejadora.actualizarProveedor(per))
            {
                JOptionPane.showMessageDialog(null, "Se Modifico Exitosamente");
               /* txt_id_prove.setText("");
                txt_nombre_prove.setText("");
                txt_telefono_prove.setText("");
                jctipo_prove.setSelectedIndex(0);*/
            } else {
                JOptionPane.showMessageDialog(null, "no se pudo modificar el registro");
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ingrese Todos los Campos restantes.");
        }

    }//GEN-LAST:event_jButton_modificarActionPerformed

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void txt_id_proveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_proveKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
        if( n<'0' || n>'9' )evt.consume();
    }//GEN-LAST:event_txt_id_proveKeyTyped

    private void jButton_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mostrarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo= new DefaultTableModel();
                 modelo.addColumn("ID PROVEEDOR");
                modelo.addColumn("Nombre Proveedor");
                modelo.addColumn("Telefono");
                modelo.addColumn("Direccion");
                modelo.addColumn("Descripcion");
                modelo.addColumn("Email");
                modelo.addColumn("Tipo de Proveedor");
        this.jTable_mostrar.setModel(modelo);

        try {
            ResultSet rs = Manejadora.mostrarProveedor();
            String [] datos = new String[7];
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                modelo.addRow(datos);
                this.jTable_mostrar.setModel(modelo);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_mostrarActionPerformed

    private void btn_proveedores_adm_proveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedores_adm_proveMouseReleased
        // TODO add your handling code here:
        Administrar_Proveedor adm_prove = new Administrar_Proveedor();
        adm_prove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_proveedores_adm_proveMouseReleased

    private void btn_dtosper_mod_proveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dtosper_mod_proveMouseReleased
        // TODO add your handling code here:
        setColor(btn_dtosper_mod_prove);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_inicio_mod_prove,btn_ingred_mod_prove,btn_adm_mesa_mod_prove}, new JPanel[]{ind_1,ind_3, ind_4});
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_dtosper_mod_proveMouseReleased

    private void btn_adm_mesa_mod_proveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adm_mesa_mod_proveMousePressed
        // TODO add your handling code here:
        setColor(btn_adm_mesa_mod_prove);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_mod_prove,btn_ingred_mod_prove,btn_inicio_mod_prove}, new JPanel[]{ind_2,ind_3, ind_1});
        Administrar_Mesas adm_mesa = new Administrar_Mesas();
        adm_mesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_adm_mesa_mod_proveMousePressed

    private void btn_ingred_mod_proveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingred_mod_proveMousePressed
        // TODO add your handling code here:
        setColor(btn_ingred_mod_prove);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_mod_prove,btn_inicio_mod_prove,btn_adm_mesa_mod_prove}, new JPanel[]{ind_2,ind_1, ind_4});
        interfaz_Ingrediente adm_ingre = new interfaz_Ingrediente();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingred_mod_proveMousePressed

    private void jTable_mostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_mostrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_mostrarMouseEntered

    private void btn_recetarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recetarioMouseReleased
        interfaz_Recetario adm_ingre = new interfaz_Recetario();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_recetarioMouseReleased

    private void btn_modulo_documentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulo_documentoMouseReleased
        Interfaz_Factura adm_ingre = new Interfaz_Factura();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modulo_documentoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_Proveedor().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_adm_mesa_mod_prove;
    private javax.swing.JPanel btn_dtosper_mod_prove;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel btn_ingred_mod_prove;
    private javax.swing.JPanel btn_inicio_mod_prove;
    private javax.swing.JPanel btn_modulo_documento;
    private javax.swing.JPanel btn_proveedores_adm_prove;
    private javax.swing.JPanel btn_recetario;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_11;
    private javax.swing.JPanel ind_12;
    private javax.swing.JPanel ind_13;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_modificar;
    private javax.swing.JButton jButton_mostrar;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_mostrar;
    private javax.swing.JComboBox<String> jctipo_prove;
    private javax.swing.JLabel jl_info_mostrar;
    private javax.swing.JLabel jl_info_rut_buscar;
    private javax.swing.JLabel lbl_adm_mesa_mod_prove;
    private javax.swing.JLabel lbl_buscar_prove;
    private javax.swing.JLabel lbl_descripcion_prove;
    private javax.swing.JLabel lbl_direccion_prove;
    private javax.swing.JLabel lbl_documentos;
    private javax.swing.JLabel lbl_dtos_perso_mod_prove;
    private javax.swing.JLabel lbl_email_prove;
    private javax.swing.JLabel lbl_fondo_interfaz_prove;
    private javax.swing.JLabel lbl_id_prove;
    private javax.swing.JLabel lbl_ingre_mod_prove;
    private javax.swing.JLabel lbl_inicio_mod_prove;
    private javax.swing.JLabel lbl_nombre_prove;
    private javax.swing.JLabel lbl_proveedores_adm_prove;
    private javax.swing.JLabel lbl_recetario;
    private javax.swing.JLabel lbl_telefono_prove;
    private javax.swing.JLabel lbl_tipo_prove;
    private javax.swing.JPanel pnl_barra_lateral_prove;
    private javax.swing.JPanel side_pane1;
    private javax.swing.JPanel side_pane10;
    private javax.swing.JPanel side_pane11;
    private javax.swing.JPanel side_pane12;
    private javax.swing.JPanel side_pane13;
    private javax.swing.JPanel side_pane14;
    private javax.swing.JPanel side_pane15;
    private javax.swing.JPanel side_pane16;
    private javax.swing.JPanel side_pane17;
    private javax.swing.JPanel side_pane2;
    private javax.swing.JPanel side_pane3;
    private javax.swing.JPanel side_pane4;
    private javax.swing.JPanel side_pane5;
    private javax.swing.JPanel side_pane6;
    private javax.swing.JPanel side_pane8;
    private javax.swing.JPanel side_pane9;
    private javax.swing.JTextField txt_descripcion_prove;
    private javax.swing.JTextField txt_direccion_prove;
    private javax.swing.JTextField txt_email_prove;
    private javax.swing.JTextField txt_id_prove;
    private javax.swing.JTextField txt_nombre_prove;
    private javax.swing.JTextField txt_telefono_prove;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables
}
