/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_Administracion;

import Vista.Usuario.Interfaz_Agregar_Usuario;
import Vista.Usuario.*;
import Vista.proveedor.Agregar_Proveedor;
import Vista.proveedor.Eliminar_Proveedor;
import Vista.proveedor.Modificar_Proveedor;
import Vista.proveedor.Mostrar_Proveedor;
import Ventanas_Administracion.Administrar_datos_personal;
import Vista.Factura.Interfaz_Factura;
import Vista.Ingrediente.interfaz_Ingrediente;
import Vista.Recetario.interfaz_Recetario;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Administrar_Proveedor extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Administrar_Proveedor() {
        initComponents();
        this.setLocationRelativeTo(this);
     
        //jProgressBar1.setValue(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ico_elim_provee = new javax.swing.JLabel();
        lbl_ico_mod_provee = new javax.swing.JLabel();
        lbl_ico_agr_provee = new javax.swing.JLabel();
        lbl_logoazul_restau = new javax.swing.JLabel();
        lbl_mod_provee = new javax.swing.JLabel();
        lbl_agr_provee = new javax.swing.JLabel();
        lbl_somb_agre_provee = new javax.swing.JLabel();
        lbl_ico_mos_provee = new javax.swing.JLabel();
        lbl_somb_mod_provee = new javax.swing.JLabel();
        lbl_mos_provee = new javax.swing.JLabel();
        lbl_somb_mos_provee = new javax.swing.JLabel();
        lbl_logorojo_restau = new javax.swing.JLabel();
        lbl_elm_provee = new javax.swing.JLabel();
        lbl_somb_elm_provee = new javax.swing.JLabel();
        pnl_barra_amarilla_provee = new javax.swing.JPanel();
        pnl_barra_lateral_provee = new javax.swing.JPanel();
        btn_inicio_adm_provee = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lbl_inicio_adm_provee = new javax.swing.JLabel();
        btn_ingred_adm_provee = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbl_ingre_adm_provee = new javax.swing.JLabel();
        btn_adm_mesa_adm_provee = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbl_adm_mesa_adm_provee = new javax.swing.JLabel();
        btn_dtosper_adm_provee = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbl_dtos_perso_adm_provee = new javax.swing.JLabel();
        btn_provee_adm_provee = new javax.swing.JPanel();
        ind_11 = new javax.swing.JPanel();
        lbl_proveedores_adm_prove = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        btn_recetario = new javax.swing.JPanel();
        ind_12 = new javax.swing.JPanel();
        lbl_recetario = new javax.swing.JLabel();
        btn_modulo_documento = new javax.swing.JPanel();
        ind_13 = new javax.swing.JPanel();
        lbl_documentos = new javax.swing.JLabel();
        pnl_barra_superior_provee = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_titulo_adm_prove = new javax.swing.JLabel();
        lbl_fondo_interfaz_provee = new javax.swing.JLabel();
        btn_Agregar_provee = new javax.swing.JPanel();
        ind_7 = new javax.swing.JPanel();
        btn_Modificar_provee = new javax.swing.JPanel();
        ind_8 = new javax.swing.JPanel();
        btn_Mostrar_provee = new javax.swing.JPanel();
        ind_9 = new javax.swing.JPanel();
        btn_Eliminar_provee = new javax.swing.JPanel();
        ind_10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ico_elim_provee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/icons8-eliminar-64.png"))); // NOI18N
        getContentPane().add(lbl_ico_elim_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        lbl_ico_mod_provee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/icons8-editar-propiedad-64.png"))); // NOI18N
        getContentPane().add(lbl_ico_mod_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 70, -1));

        lbl_ico_agr_provee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/icons8-añadir-64.png"))); // NOI18N
        getContentPane().add(lbl_ico_agr_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        lbl_logoazul_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_superior_blanco.png"))); // NOI18N
        lbl_logoazul_restau.setText("jLabel17");
        getContentPane().add(lbl_logoazul_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 205, 80));

        lbl_mod_provee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mod_provee.setText("Modificar Proveedor");
        getContentPane().add(lbl_mod_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 120, 20));

        lbl_agr_provee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_agr_provee.setText("Agregar Proveedor");
        getContentPane().add(lbl_agr_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 130, -1));

        lbl_somb_agre_provee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/transparencia_button_FINALL.png"))); // NOI18N
        getContentPane().add(lbl_somb_agre_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 100, -1));

        lbl_ico_mos_provee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/icons8-mostrar-propiedad-64.png"))); // NOI18N
        getContentPane().add(lbl_ico_mos_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        lbl_somb_mod_provee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/transparencia_button_FINALL.png"))); // NOI18N
        getContentPane().add(lbl_somb_mod_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 100, -1));

        lbl_mos_provee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mos_provee.setText("Mostrar Proveedores");
        getContentPane().add(lbl_mos_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 110, 20));

        lbl_somb_mos_provee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/transparencia_button_FINALL.png"))); // NOI18N
        getContentPane().add(lbl_somb_mos_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 100, -1));

        lbl_logorojo_restau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_final.png"))); // NOI18N
        lbl_logorojo_restau.setText("jLabel17");
        getContentPane().add(lbl_logorojo_restau, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 260, 320));

        lbl_elm_provee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_elm_provee.setText("Eliminar Proveedores");
        getContentPane().add(lbl_elm_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 100, 20));

        lbl_somb_elm_provee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/transparencia_button_FINALL.png"))); // NOI18N
        getContentPane().add(lbl_somb_elm_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 100, -1));

        pnl_barra_amarilla_provee.setBackground(new java.awt.Color(251, 243, 0));
        pnl_barra_amarilla_provee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnl_barra_amarilla_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 10, 500));

        pnl_barra_lateral_provee.setBackground(new java.awt.Color(23, 35, 51));
        pnl_barra_lateral_provee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio_adm_provee.setBackground(new java.awt.Color(23, 35, 51));
        btn_inicio_adm_provee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicio_adm_proveeMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_inicio_adm_provee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_inicio_adm_provee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio_adm_provee.setText("Inicio");

        javax.swing.GroupLayout btn_inicio_adm_proveeLayout = new javax.swing.GroupLayout(btn_inicio_adm_provee);
        btn_inicio_adm_provee.setLayout(btn_inicio_adm_proveeLayout);
        btn_inicio_adm_proveeLayout.setHorizontalGroup(
            btn_inicio_adm_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_adm_proveeLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbl_inicio_adm_provee)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_inicio_adm_proveeLayout.setVerticalGroup(
            btn_inicio_adm_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inicio_adm_proveeLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_inicio_adm_proveeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inicio_adm_provee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_provee.add(btn_inicio_adm_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        btn_ingred_adm_provee.setBackground(new java.awt.Color(23, 35, 51));
        btn_ingred_adm_provee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingred_adm_proveeMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_ingre_adm_provee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_ingre_adm_provee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingre_adm_provee.setText("Ingredientes");

        javax.swing.GroupLayout btn_ingred_adm_proveeLayout = new javax.swing.GroupLayout(btn_ingred_adm_provee);
        btn_ingred_adm_provee.setLayout(btn_ingred_adm_proveeLayout);
        btn_ingred_adm_proveeLayout.setHorizontalGroup(
            btn_ingred_adm_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_adm_proveeLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingre_adm_provee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        btn_ingred_adm_proveeLayout.setVerticalGroup(
            btn_ingred_adm_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingred_adm_proveeLayout.createSequentialGroup()
                .addGroup(btn_ingred_adm_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingre_adm_provee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_barra_lateral_provee.add(btn_ingred_adm_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));

        btn_adm_mesa_adm_provee.setBackground(new java.awt.Color(23, 35, 51));
        btn_adm_mesa_adm_provee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_adm_mesa_adm_proveeMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_adm_mesa_adm_provee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_adm_mesa_adm_provee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_adm_mesa_adm_provee.setText("Administrar Mesas");

        javax.swing.GroupLayout btn_adm_mesa_adm_proveeLayout = new javax.swing.GroupLayout(btn_adm_mesa_adm_provee);
        btn_adm_mesa_adm_provee.setLayout(btn_adm_mesa_adm_proveeLayout);
        btn_adm_mesa_adm_proveeLayout.setHorizontalGroup(
            btn_adm_mesa_adm_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adm_mesa_adm_proveeLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_adm_mesa_adm_provee)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btn_adm_mesa_adm_proveeLayout.setVerticalGroup(
            btn_adm_mesa_adm_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adm_mesa_adm_proveeLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_adm_mesa_adm_proveeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_adm_mesa_adm_provee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_provee.add(btn_adm_mesa_adm_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, -1));

        btn_dtosper_adm_provee.setBackground(new java.awt.Color(23, 35, 51));
        btn_dtosper_adm_provee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_dtosper_adm_proveeMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_dtos_perso_adm_provee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_dtos_perso_adm_provee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dtos_perso_adm_provee.setText("Datos de personal");

        javax.swing.GroupLayout btn_dtosper_adm_proveeLayout = new javax.swing.GroupLayout(btn_dtosper_adm_provee);
        btn_dtosper_adm_provee.setLayout(btn_dtosper_adm_proveeLayout);
        btn_dtosper_adm_proveeLayout.setHorizontalGroup(
            btn_dtosper_adm_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dtosper_adm_proveeLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_dtos_perso_adm_provee, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );
        btn_dtosper_adm_proveeLayout.setVerticalGroup(
            btn_dtosper_adm_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dtosper_adm_proveeLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_dtosper_adm_proveeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dtos_perso_adm_provee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_provee.add(btn_dtosper_adm_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, -1));

        btn_provee_adm_provee.setBackground(new java.awt.Color(251, 243, 0));
        btn_provee_adm_provee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_provee_adm_proveeMouseReleased(evt);
            }
        });

        ind_11.setOpaque(false);
        ind_11.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_11Layout = new javax.swing.GroupLayout(ind_11);
        ind_11.setLayout(ind_11Layout);
        ind_11Layout.setHorizontalGroup(
            ind_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_11Layout.setVerticalGroup(
            ind_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_proveedores_adm_prove.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_proveedores_adm_prove.setText("Proveedores");

        javax.swing.GroupLayout btn_provee_adm_proveeLayout = new javax.swing.GroupLayout(btn_provee_adm_provee);
        btn_provee_adm_provee.setLayout(btn_provee_adm_proveeLayout);
        btn_provee_adm_proveeLayout.setHorizontalGroup(
            btn_provee_adm_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_provee_adm_proveeLayout.createSequentialGroup()
                .addComponent(ind_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_proveedores_adm_prove, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_provee_adm_proveeLayout.setVerticalGroup(
            btn_provee_adm_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_provee_adm_proveeLayout.createSequentialGroup()
                .addComponent(ind_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_provee_adm_proveeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_proveedores_adm_prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_provee.add(btn_provee_adm_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 140, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        pnl_barra_lateral_provee.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 30, 46));

        btn_recetario.setBackground(new java.awt.Color(23, 35, 51));
        btn_recetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_recetarioMouseReleased(evt);
            }
        });

        ind_12.setOpaque(false);
        ind_12.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_12Layout = new javax.swing.GroupLayout(ind_12);
        ind_12.setLayout(ind_12Layout);
        ind_12Layout.setHorizontalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_12Layout.setVerticalGroup(
            ind_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_recetario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_recetario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_recetario.setText("Recetario");

        javax.swing.GroupLayout btn_recetarioLayout = new javax.swing.GroupLayout(btn_recetario);
        btn_recetario.setLayout(btn_recetarioLayout);
        btn_recetarioLayout.setHorizontalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_recetario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_recetarioLayout.setVerticalGroup(
            btn_recetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addComponent(ind_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_recetarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_recetario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_provee.add(btn_recetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 140, -1));

        btn_modulo_documento.setBackground(new java.awt.Color(23, 35, 51));
        btn_modulo_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_modulo_documentoMouseReleased(evt);
            }
        });

        ind_13.setOpaque(false);
        ind_13.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_13Layout = new javax.swing.GroupLayout(ind_13);
        ind_13.setLayout(ind_13Layout);
        ind_13Layout.setHorizontalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_13Layout.setVerticalGroup(
            ind_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl_documentos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_documentos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_documentos.setText("Documentos");

        javax.swing.GroupLayout btn_modulo_documentoLayout = new javax.swing.GroupLayout(btn_modulo_documento);
        btn_modulo_documento.setLayout(btn_modulo_documentoLayout);
        btn_modulo_documentoLayout.setHorizontalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btn_modulo_documentoLayout.setVerticalGroup(
            btn_modulo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addComponent(ind_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_modulo_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_documentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_barra_lateral_provee.add(btn_modulo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 140, -1));

        getContentPane().add(pnl_barra_lateral_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 590));

        pnl_barra_superior_provee.setBackground(new java.awt.Color(23, 35, 51));
        pnl_barra_superior_provee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barra_superior_proveeMouseDragged(evt);
            }
        });
        pnl_barra_superior_provee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barra_superior_proveeMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuario: Administrador");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_48px.png"))); // NOI18N

        lbl_titulo_adm_prove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo_adm_prove.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo_adm_prove.setText("ADMINISTRAR PROVEEDORES");

        javax.swing.GroupLayout pnl_barra_superior_proveeLayout = new javax.swing.GroupLayout(pnl_barra_superior_provee);
        pnl_barra_superior_provee.setLayout(pnl_barra_superior_proveeLayout);
        pnl_barra_superior_proveeLayout.setHorizontalGroup(
            pnl_barra_superior_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barra_superior_proveeLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(lbl_titulo_adm_prove)
                .addGap(142, 142, 142)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_barra_superior_proveeLayout.setVerticalGroup(
            pnl_barra_superior_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_proveeLayout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addGroup(pnl_barra_superior_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_superior_proveeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_titulo_adm_prove)
                .addGap(27, 27, 27))
        );

        getContentPane().add(pnl_barra_superior_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 90));

        lbl_fondo_interfaz_provee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_personal_final.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo_interfaz_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 500));

        btn_Agregar_provee.setBackground(new java.awt.Color(26, 146, 167));
        btn_Agregar_provee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Agregar_proveeMousePressed(evt);
            }
        });

        ind_7.setOpaque(false);
        ind_7.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_7Layout = new javax.swing.GroupLayout(ind_7);
        ind_7.setLayout(ind_7Layout);
        ind_7Layout.setHorizontalGroup(
            ind_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_7Layout.setVerticalGroup(
            ind_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_Agregar_proveeLayout = new javax.swing.GroupLayout(btn_Agregar_provee);
        btn_Agregar_provee.setLayout(btn_Agregar_proveeLayout);
        btn_Agregar_proveeLayout.setHorizontalGroup(
            btn_Agregar_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_Agregar_proveeLayout.createSequentialGroup()
                .addComponent(ind_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        btn_Agregar_proveeLayout.setVerticalGroup(
            btn_Agregar_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_Agregar_proveeLayout.createSequentialGroup()
                .addComponent(ind_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(btn_Agregar_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 110, 80));

        btn_Modificar_provee.setBackground(new java.awt.Color(26, 146, 167));
        btn_Modificar_provee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Modificar_proveeMousePressed(evt);
            }
        });

        ind_8.setOpaque(false);
        ind_8.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_8Layout = new javax.swing.GroupLayout(ind_8);
        ind_8.setLayout(ind_8Layout);
        ind_8Layout.setHorizontalGroup(
            ind_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_8Layout.setVerticalGroup(
            ind_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_Modificar_proveeLayout = new javax.swing.GroupLayout(btn_Modificar_provee);
        btn_Modificar_provee.setLayout(btn_Modificar_proveeLayout);
        btn_Modificar_proveeLayout.setHorizontalGroup(
            btn_Modificar_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_Modificar_proveeLayout.createSequentialGroup()
                .addComponent(ind_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        btn_Modificar_proveeLayout.setVerticalGroup(
            btn_Modificar_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_Modificar_proveeLayout.createSequentialGroup()
                .addComponent(ind_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(btn_Modificar_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 100, 80));

        btn_Mostrar_provee.setBackground(new java.awt.Color(26, 146, 167));
        btn_Mostrar_provee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Mostrar_proveeMousePressed(evt);
            }
        });

        ind_9.setOpaque(false);
        ind_9.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_9Layout = new javax.swing.GroupLayout(ind_9);
        ind_9.setLayout(ind_9Layout);
        ind_9Layout.setHorizontalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_9Layout.setVerticalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_Mostrar_proveeLayout = new javax.swing.GroupLayout(btn_Mostrar_provee);
        btn_Mostrar_provee.setLayout(btn_Mostrar_proveeLayout);
        btn_Mostrar_proveeLayout.setHorizontalGroup(
            btn_Mostrar_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_Mostrar_proveeLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        btn_Mostrar_proveeLayout.setVerticalGroup(
            btn_Mostrar_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_Mostrar_proveeLayout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(btn_Mostrar_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 110, 80));

        btn_Eliminar_provee.setBackground(new java.awt.Color(26, 146, 167));
        btn_Eliminar_provee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Eliminar_proveeMousePressed(evt);
            }
        });

        ind_10.setOpaque(false);
        ind_10.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_10Layout = new javax.swing.GroupLayout(ind_10);
        ind_10.setLayout(ind_10Layout);
        ind_10Layout.setHorizontalGroup(
            ind_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_10Layout.setVerticalGroup(
            ind_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_Eliminar_proveeLayout = new javax.swing.GroupLayout(btn_Eliminar_provee);
        btn_Eliminar_provee.setLayout(btn_Eliminar_proveeLayout);
        btn_Eliminar_proveeLayout.setHorizontalGroup(
            btn_Eliminar_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_Eliminar_proveeLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(ind_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_Eliminar_proveeLayout.setVerticalGroup(
            btn_Eliminar_proveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_Eliminar_proveeLayout.createSequentialGroup()
                .addComponent(ind_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(btn_Eliminar_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 100, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void pnl_barra_superior_proveeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_superior_proveeMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnl_barra_superior_proveeMousePressed

    private void pnl_barra_superior_proveeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_superior_proveeMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_pnl_barra_superior_proveeMouseDragged

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?");
        if (JOptionPane.OK_OPTION == exit)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitMousePressed

    private void btn_Agregar_proveeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Agregar_proveeMousePressed
        // TODO add your handling code here:
        Agregar_Proveedor ap = new Agregar_Proveedor();
        ap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Agregar_proveeMousePressed

    private void btn_Modificar_proveeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Modificar_proveeMousePressed
       
        Modificar_Proveedor mp = new Modificar_Proveedor();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Modificar_proveeMousePressed

    private void btn_Mostrar_proveeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Mostrar_proveeMousePressed
        Mostrar_Proveedor mp = new Mostrar_Proveedor();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Mostrar_proveeMousePressed

    private void btn_Eliminar_proveeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Eliminar_proveeMousePressed
      Eliminar_Proveedor ep = new  Eliminar_Proveedor();
        ep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Eliminar_proveeMousePressed

    private void btn_provee_adm_proveeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_provee_adm_proveeMouseReleased
        // TODO add your handling code here:
        Administrar_Proveedor ap = new Administrar_Proveedor();
        ap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_provee_adm_proveeMouseReleased

    private void btn_adm_mesa_adm_proveeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adm_mesa_adm_proveeMousePressed
        // TODO add your handling code here:
        setColor(btn_adm_mesa_adm_provee);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_adm_provee,btn_ingred_adm_provee,btn_inicio_adm_provee}, new JPanel[]{ind_2,ind_3, ind_1});
        Ventanas_Administracion.Administrar_Mesas adm_mesa = new Ventanas_Administracion.Administrar_Mesas();
        adm_mesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_adm_mesa_adm_proveeMousePressed

    private void btn_ingred_adm_proveeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingred_adm_proveeMousePressed
        // TODO add your handling code here:
        setColor(btn_ingred_adm_provee);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_dtosper_adm_provee,btn_inicio_adm_provee,btn_adm_mesa_adm_provee}, new JPanel[]{ind_2,ind_1, ind_4});
       interfaz_Ingrediente adm_ingre = new interfaz_Ingrediente();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ingred_adm_proveeMousePressed

    private void btn_dtosper_adm_proveeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dtosper_adm_proveeMouseReleased
        // TODO add your handling code here:
        setColor(btn_dtosper_adm_provee);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_inicio_adm_provee,btn_ingred_adm_provee,btn_adm_mesa_adm_provee}, new JPanel[]{ind_1,ind_3, ind_4});
        Administrar_datos_personal dp = new Administrar_datos_personal();
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_dtosper_adm_proveeMouseReleased

    private void btn_inicio_adm_proveeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicio_adm_proveeMousePressed
        // TODO add your handling code here:

        Menu_principal menu_principal = new Menu_principal();
        menu_principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicio_adm_proveeMousePressed

    private void btn_recetarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recetarioMouseReleased
        interfaz_Recetario adm_ingre = new interfaz_Recetario();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_recetarioMouseReleased

    private void btn_modulo_documentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulo_documentoMouseReleased
        Interfaz_Factura adm_ingre = new Interfaz_Factura();
        adm_ingre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_modulo_documentoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrar_Proveedor().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_Agregar_provee;
    private javax.swing.JPanel btn_Eliminar_provee;
    private javax.swing.JPanel btn_Modificar_provee;
    private javax.swing.JPanel btn_Mostrar_provee;
    private javax.swing.JPanel btn_adm_mesa_adm_provee;
    private javax.swing.JPanel btn_dtosper_adm_provee;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel btn_ingred_adm_provee;
    private javax.swing.JPanel btn_inicio_adm_provee;
    private javax.swing.JPanel btn_modulo_documento;
    private javax.swing.JPanel btn_provee_adm_provee;
    private javax.swing.JPanel btn_recetario;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_10;
    private javax.swing.JPanel ind_11;
    private javax.swing.JPanel ind_12;
    private javax.swing.JPanel ind_13;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_7;
    private javax.swing.JPanel ind_8;
    private javax.swing.JPanel ind_9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_adm_mesa_adm_provee;
    private javax.swing.JLabel lbl_agr_provee;
    private javax.swing.JLabel lbl_documentos;
    private javax.swing.JLabel lbl_dtos_perso_adm_provee;
    private javax.swing.JLabel lbl_elm_provee;
    private javax.swing.JLabel lbl_fondo_interfaz_provee;
    private javax.swing.JLabel lbl_ico_agr_provee;
    private javax.swing.JLabel lbl_ico_elim_provee;
    private javax.swing.JLabel lbl_ico_mod_provee;
    private javax.swing.JLabel lbl_ico_mos_provee;
    private javax.swing.JLabel lbl_ingre_adm_provee;
    private javax.swing.JLabel lbl_inicio_adm_provee;
    private javax.swing.JLabel lbl_logoazul_restau;
    private javax.swing.JLabel lbl_logorojo_restau;
    private javax.swing.JLabel lbl_mod_provee;
    private javax.swing.JLabel lbl_mos_provee;
    private javax.swing.JLabel lbl_proveedores_adm_prove;
    private javax.swing.JLabel lbl_recetario;
    private javax.swing.JLabel lbl_somb_agre_provee;
    private javax.swing.JLabel lbl_somb_elm_provee;
    private javax.swing.JLabel lbl_somb_mod_provee;
    private javax.swing.JLabel lbl_somb_mos_provee;
    private javax.swing.JLabel lbl_titulo_adm_prove;
    private javax.swing.JPanel pnl_barra_amarilla_provee;
    private javax.swing.JPanel pnl_barra_lateral_provee;
    private javax.swing.JPanel pnl_barra_superior_provee;
    // End of variables declaration//GEN-END:variables
}
